<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Features\Measures\Secondary\Ks4CoreSubjects\**" />
    <Compile Remove="Features\Measures\Secondary\Ks4HeadlineMeasures\**" />
    <Compile Remove="Model\KS4\**" />
    <Compile Remove="Model\Search\**" />
    <EmbeddedResource Remove="Features\Measures\Secondary\Ks4CoreSubjects\**" />
    <EmbeddedResource Remove="Features\Measures\Secondary\Ks4HeadlineMeasures\**" />
    <EmbeddedResource Remove="Model\KS4\**" />
    <EmbeddedResource Remove="Model\Search\**" />
    <None Remove="Features\Measures\Secondary\Ks4CoreSubjects\**" />
    <None Remove="Features\Measures\Secondary\Ks4HeadlineMeasures\**" />
    <None Remove="Model\KS4\**" />
    <None Remove="Model\Search\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Model\Establishment.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="IeuanWalker.GeoUK" Version="1.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.0" />
	<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Data\SAPSec.Data\SAPSec.Data.csproj" />
  </ItemGroup>

</Project>
