using System.Text;
using System.Text.RegularExpressions;

namespace SAPData;

// The scripts around the generated tables and views: 00_cleanup.sql (with the helper functions) and run_all.sql.
internal partial class Program
{
    // Helper functions the generated views call. Part of each view's fingerprint, so changing one rebuilds the views.
    private static string HelperFunctionsSql()
    {
        var helpers = new StringBuilder();
        helpers.AppendLine("-- =========================");
        helpers.AppendLine("-- Cleaning helpers");
        helpers.AppendLine("-- =========================");
        helpers.AppendLine();
        helpers.AppendLine("CREATE OR REPLACE FUNCTION clean_int(value TEXT)");
        helpers.AppendLine("RETURNS INT");
        helpers.AppendLine("LANGUAGE plpgsql");
        helpers.AppendLine("IMMUTABLE");
        helpers.AppendLine("AS $$");
        helpers.AppendLine("BEGIN");
        helpers.AppendLine("    IF value IS NULL OR trim(value) IN ('', 'NE', 'N', 'na', 'n/a', 'N/A', 'SUPP', '.', '-', '--', 'z') THEN");
        helpers.AppendLine("        RETURN NULL;");
        helpers.AppendLine("    END IF;");
        helpers.AppendLine();
        helpers.AppendLine("    RETURN value::INT;");
        helpers.AppendLine();
        helpers.AppendLine("EXCEPTION WHEN others THEN");
        helpers.AppendLine("    RETURN NULL;");
        helpers.AppendLine("END;");
        helpers.AppendLine("$$;");
        helpers.AppendLine();
        helpers.AppendLine("CREATE OR REPLACE FUNCTION clean_numeric(value TEXT)");
        helpers.AppendLine("RETURNS NUMERIC");
        helpers.AppendLine("LANGUAGE plpgsql");
        helpers.AppendLine("IMMUTABLE");
        helpers.AppendLine("AS $$");
        helpers.AppendLine("DECLARE");
        helpers.AppendLine("    result NUMERIC;");
        helpers.AppendLine("BEGIN");
        helpers.AppendLine("    IF value IS NULL OR trim(value) IN ('', 'NE', 'N', 'na', 'n/a', 'N/A', 'SUPP', '.', '-', '--', 'z') THEN");
        helpers.AppendLine("        RETURN NULL;");
        helpers.AppendLine("    END IF;");
        helpers.AppendLine();
        helpers.AppendLine("    -- Same rules as the website's parser (SAPSec.Core MeasureHelper.ParseNullableDecimal):");
        helpers.AppendLine("    -- a trailing '%' is ignored, and anything that isn't a finite number is NULL.");
        helpers.AppendLine("    result := regexp_replace(trim(value), '%$', '')::NUMERIC;");
        helpers.AppendLine();
        helpers.AppendLine("    IF result IN ('NaN'::NUMERIC, 'Infinity'::NUMERIC, '-Infinity'::NUMERIC) THEN");
        helpers.AppendLine("        RETURN NULL;");
        helpers.AppendLine("    END IF;");
        helpers.AppendLine();
        helpers.AppendLine("    RETURN result;");
        helpers.AppendLine();
        helpers.AppendLine("EXCEPTION WHEN others THEN");
        helpers.AppendLine("    RETURN NULL;");
        helpers.AppendLine("END;");
        helpers.AppendLine("$$;");
        helpers.AppendLine();
        helpers.AppendLine("CREATE OR REPLACE FUNCTION clean_date(value TEXT)");
        helpers.AppendLine("RETURNS DATE");
        helpers.AppendLine("LANGUAGE plpgsql");
        helpers.AppendLine("IMMUTABLE");
        helpers.AppendLine("AS $$");
        helpers.AppendLine("BEGIN");
        helpers.AppendLine("    IF value IS NULL OR trim(value) IN ('', 'na', 'n/a', 'N/A', '.', '-', '--') THEN");
        helpers.AppendLine("        RETURN NULL;");
        helpers.AppendLine("    END IF;");
        helpers.AppendLine();
        helpers.AppendLine("    RETURN value::DATE;");
        helpers.AppendLine();
        helpers.AppendLine("EXCEPTION WHEN others THEN");
        helpers.AppendLine("    RETURN NULL;");
        helpers.AppendLine("END;");
        helpers.AppendLine("$$;");
        helpers.AppendLine();
        return helpers.ToString();
    }

    [GeneratedRegex(@"^(03|04|50)_(?<view>v_\w+)\.sql$")]
    private static partial Regex ViewFile();

    private static void WriteCleanupSql(string path, IEnumerable<string> tableNamesToRebuild, bool rebuildAllRawTables, bool incremental)
    {
        var tablesToRebuild = tableNamesToRebuild
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(name => name, StringComparer.OrdinalIgnoreCase)
            .ToList();

        var sql = new StringBuilder();
        sql.AppendLine("-- ================================================================");
        sql.AppendLine("-- 00_cleanup.sql");
        sql.AppendLine("-- Auto-generated by SAPData/Program.cs");
        sql.AppendLine("-- Drops only explicitly listed raw tables before regeneration.");
        sql.AppendLine("-- Recreates helper functions used by generated views.");
        sql.AppendLine("-- ================================================================");
        sql.AppendLine();
        sql.AppendLine(@"\echo 'Cleaning up listed raw tables and regenerating helper functions...'");
        sql.AppendLine();
        sql.AppendLine("DO $$");
        sql.AppendLine("DECLARE");
        sql.AppendLine("  v_schema text := current_schema();");
        sql.AppendLine("  r record;");
        if (tablesToRebuild.Count > 0)
        {
            sql.AppendLine($"  tables_to_rebuild text[] := ARRAY[{string.Join(", ", tablesToRebuild.Select(name => $"'{name}'"))}];");
        }
        else
        {
            sql.AppendLine("  tables_to_rebuild text[] := ARRAY[]::text[];");
        }
        sql.AppendLine("BEGIN");
        sql.AppendLine("  EXECUTE format('SET search_path TO %I', v_schema);");
        sql.AppendLine();
        sql.AppendLine("  -- Drop only listed raw tables");
        sql.AppendLine("  FOR r IN");
        sql.AppendLine("    SELECT schemaname, tablename");
        sql.AppendLine("    FROM pg_tables");
        sql.AppendLine("    WHERE schemaname = v_schema");
        if (rebuildAllRawTables)
        {
            sql.AppendLine("      AND tablename LIKE 't\\_%' ESCAPE '\\'");
        }
        else
        {
            sql.AppendLine("      AND tablename = ANY(tables_to_rebuild)");
        }
        sql.AppendLine("  LOOP");
        sql.AppendLine("    EXECUTE format('DROP TABLE IF EXISTS %I.%I CASCADE', r.schemaname, r.tablename);");
        sql.AppendLine("  END LOOP;");
        sql.AppendLine("END $$;");
        sql.AppendLine();
        if (incremental)
        {
            sql.AppendLine("-- Fingerprints of what each raw table and view was last built from (incremental loads).");
            sql.Append(IncrementalLoad.LogTablesSql(rebuildAllRawTables));
            sql.AppendLine();
        }

        sql.Append(HelperFunctionsSql());
        sql.AppendLine(@"\echo 'Cleanup complete.'");

        File.WriteAllText(path, sql.ToString(), new UTF8Encoding(false));
    }

    // run_all.sql runs every generated script in order. In incremental mode each view runs only when it is missing
    // or its SQL changed.
    private static void WriteRunAllSql(string runAllSqlFile, string sqlDir, List<string> sqlFiles, bool incremental)
    {
        var runAllSql = new StringBuilder();
        runAllSql.AppendLine(@"-- ================================================================");
        runAllSql.AppendLine(@"-- run_all.sql");
        runAllSql.AppendLine(@"-- ================================================================");
        runAllSql.AppendLine(@"");
        runAllSql.AppendLine(@"\set ON_ERROR_STOP on");
        runAllSql.AppendLine(@"");
        runAllSql.AppendLine(@"\ir 00_cleanup.sql");

        foreach (var line in sqlFiles.Order())
        {
            var view = ViewFile().Match(line);
            if (incremental && view.Success)
            {
                // A view is rebuilt when it's missing (reloading a raw table drops its views) or its SQL changed.
                var fingerprint = IncrementalLoad.Fingerprint(File.ReadAllText(Path.Combine(sqlDir, line)) + HelperFunctionsSql());
                runAllSql.Append(IncrementalLoad.View(view.Groups["view"].Value, line, fingerprint));
            }
            else
            {
                runAllSql.AppendLine(@$"\ir {line}");
            }
        }

        File.WriteAllText(runAllSqlFile, runAllSql.ToString());
    }
}
