// This file is automatically generated by SAPSec.DtoGenerator.
// Please do not manually edit this file or your changes will be lost when the file is regenerated.

using System.Diagnostics.CodeAnalysis;
using System.Globalization;

namespace SAPSec.Data.Dto.Absence;

[ExcludeFromCodeCoverage]
public class EnglandAbsence
{
    public string Id { get; set; } = string.Empty;

    public string Abs_Persistent_Secondary_Eng_Current_Pct { get; set; } = string.Empty;
    public string Abs_Persistent_Secondary_Eng_Previous_Pct { get; set; } = string.Empty;
    public string Abs_Persistent_Secondary_Eng_Previous2_Pct { get; set; } = string.Empty;
    public string Abs_Tot_Secondary_Eng_Current_Pct { get; set; } = string.Empty;
    public string Abs_Tot_Secondary_Eng_Previous_Pct { get; set; } = string.Empty;
    public string Abs_Tot_Secondary_Eng_Previous2_Pct { get; set; } = string.Empty;
    public string Auth_Tot_Secondary_Eng_Current_Pct { get; set; } = string.Empty;
    public string UnAuth_Tot_Secondary_Eng_Current_Pct { get; set; } = string.Empty;

    public string Abs_Persistent_Primary_Eng_Current_Pct { get; set; } = string.Empty;
    public string Abs_Persistent_Primary_Eng_Previous_Pct { get; set; } = string.Empty;
    public string Abs_Persistent_Primary_Eng_Previous2_Pct { get; set; } = string.Empty;
    public string Abs_Tot_Primary_Eng_Current_Pct { get; set; } = string.Empty;
    public string Abs_Tot_Primary_Eng_Previous_Pct { get; set; } = string.Empty;
    public string Abs_Tot_Primary_Eng_Previous2_Pct { get; set; } = string.Empty;
    public string Auth_Tot_Primary_Eng_Current_Pct { get; set; } = string.Empty;
    public string UnAuth_Tot_Primary_Eng_Current_Pct { get; set; } = string.Empty;

}
