// This file is automatically generated by SAPSec.ModelGenerator.
// Please do not manually edit this file or your changes will be lost when the file is regenerated.

using System.Diagnostics.CodeAnalysis;

namespace SAPSec.Data.Dto.KS2.Performance;

[ExcludeFromCodeCoverage]
public class EnglandPerformance
{
    public string Id { get; set; } = string.Empty;
    public string RwmExpected_Tot_Cohort_Eng_Current_Num { get; set; } = string.Empty;
    public string RwmExpected_Tot_Cohort_Eng_Previous_Num { get; set; } = string.Empty;
    public string RwmExpected_Tot_Cohort_Eng_Previous2_Num { get; set; } = string.Empty;
    public string RwmExpected_Boy_Cohort_Eng_Current_Num { get; set; } = string.Empty;
    public string RwmExpected_Boy_Cohort_Eng_Previous_Num { get; set; } = string.Empty;
    public string RwmExpected_Boy_Cohort_Eng_Previous2_Num { get; set; } = string.Empty;
    public string RwmExpected_Grl_Cohort_Eng_Current_Num { get; set; } = string.Empty;
    public string RwmExpected_Grl_Cohort_Eng_Previous_Num { get; set; } = string.Empty;
    public string RwmExpected_Grl_Cohort_Eng_Previous2_Num { get; set; } = string.Empty;
    public string RwmExpected_Dis_Cohort_Eng_Current_Num { get; set; } = string.Empty;
    public string RwmExpected_Dis_Cohort_Eng_Previous_Num { get; set; } = string.Empty;
    public string RwmExpected_Dis_Cohort_Eng_Previous2_Num { get; set; } = string.Empty;
    public string RwmExpected_NDi_Cohort_Eng_Current_Num { get; set; } = string.Empty;
    public string RwmExpected_NDi_Cohort_Eng_Previous_Num { get; set; } = string.Empty;
    public string RwmExpected_NDi_Cohort_Eng_Previous2_Num { get; set; } = string.Empty;
    public string RwmExpected_SENEHC_Cohort_Eng_Current_Num { get; set; } = string.Empty;
    public string RwmExpected_SENEHC_Cohort_Eng_Previous_Num { get; set; } = string.Empty;
    public string RwmExpected_SENEHC_Cohort_Eng_Previous2_Num { get; set; } = string.Empty;
    public string RwmExpected_SENSup_Cohort_Eng_Current_Num { get; set; } = string.Empty;
    public string RwmExpected_SENSup_Cohort_Eng_Previous_Num { get; set; } = string.Empty;
    public string RwmExpected_SENSup_Cohort_Eng_Previous2_Num { get; set; } = string.Empty;
    public string RwmExpected_NoSEN_Cohort_Eng_Current_Num { get; set; } = string.Empty;
    public string RwmExpected_NoSEN_Cohort_Eng_Previous_Num { get; set; } = string.Empty;
    public string RwmExpected_NoSEN_Cohort_Eng_Previous2_Num { get; set; } = string.Empty;
    public string RwmExpected_EFL_Cohort_Eng_Current_Num { get; set; } = string.Empty;
    public string RwmExpected_EFL_Cohort_Eng_Previous_Num { get; set; } = string.Empty;
    public string RwmExpected_EFL_Cohort_Eng_Previous2_Num { get; set; } = string.Empty;
    public string RwmExpected_EAL_Cohort_Eng_Current_Num { get; set; } = string.Empty;
    public string RwmExpected_EAL_Cohort_Eng_Previous_Num { get; set; } = string.Empty;
    public string RwmExpected_EAL_Cohort_Eng_Previous2_Num { get; set; } = string.Empty;
    public string RwmExpected_NMo_Cohort_Eng_Current_Num { get; set; } = string.Empty;
    public string RwmExpected_NMo_Cohort_Eng_Previous_Num { get; set; } = string.Empty;
    public string RwmExpected_NMo_Cohort_Eng_Previous2_Num { get; set; } = string.Empty;
    public string RwmExpected_Mob_Cohort_Eng_Current_Num { get; set; } = string.Empty;
    public string RwmExpected_Mob_Cohort_Eng_Previous_Num { get; set; } = string.Empty;
    public string RwmExpected_Mob_Cohort_Eng_Previous2_Num { get; set; } = string.Empty;
    public string GpsExpected_Tot_Cohort_Eng_Current_Num { get; set; } = string.Empty;
    public string GpsExpected_Tot_Cohort_Eng_Previous_Num { get; set; } = string.Empty;
    public string GpsExpected_Tot_Cohort_Eng_Previous2_Num { get; set; } = string.Empty;
    public string GpsExpected_Boy_Cohort_Eng_Current_Num { get; set; } = string.Empty;
    public string GpsExpected_Boy_Cohort_Eng_Previous_Num { get; set; } = string.Empty;
    public string GpsExpected_Boy_Cohort_Eng_Previous2_Num { get; set; } = string.Empty;
    public string GpsExpected_Grl_Cohort_Eng_Current_Num { get; set; } = string.Empty;
    public string GpsExpected_Grl_Cohort_Eng_Previous_Num { get; set; } = string.Empty;
    public string GpsExpected_Grl_Cohort_Eng_Previous2_Num { get; set; } = string.Empty;
    public string GpsExpected_Dis_Cohort_Eng_Current_Num { get; set; } = string.Empty;
    public string GpsExpected_Dis_Cohort_Eng_Previous_Num { get; set; } = string.Empty;
    public string GpsExpected_Dis_Cohort_Eng_Previous2_Num { get; set; } = string.Empty;
    public string GpsExpected_NDi_Cohort_Eng_Current_Num { get; set; } = string.Empty;
    public string GpsExpected_NDi_Cohort_Eng_Previous_Num { get; set; } = string.Empty;
    public string GpsExpected_NDi_Cohort_Eng_Previous2_Num { get; set; } = string.Empty;
    public string GpsExpected_SENEHC_Cohort_Eng_Current_Num { get; set; } = string.Empty;
    public string GpsExpected_SENEHC_Cohort_Eng_Previous_Num { get; set; } = string.Empty;
    public string GpsExpected_SENEHC_Cohort_Eng_Previous2_Num { get; set; } = string.Empty;
    public string GpsExpected_SENSup_Cohort_Eng_Current_Num { get; set; } = string.Empty;
    public string GpsExpected_SENSup_Cohort_Eng_Previous_Num { get; set; } = string.Empty;
    public string GpsExpected_SENSup_Cohort_Eng_Previous2_Num { get; set; } = string.Empty;
    public string GpsExpected_NoSEN_Cohort_Eng_Current_Num { get; set; } = string.Empty;
    public string GpsExpected_NoSEN_Cohort_Eng_Previous_Num { get; set; } = string.Empty;
    public string GpsExpected_NoSEN_Cohort_Eng_Previous2_Num { get; set; } = string.Empty;
    public string GpsExpected_EFL_Cohort_Eng_Current_Num { get; set; } = string.Empty;
    public string GpsExpected_EFL_Cohort_Eng_Previous_Num { get; set; } = string.Empty;
    public string GpsExpected_EFL_Cohort_Eng_Previous2_Num { get; set; } = string.Empty;
    public string GpsExpected_EAL_Cohort_Eng_Current_Num { get; set; } = string.Empty;
    public string GpsExpected_EAL_Cohort_Eng_Previous_Num { get; set; } = string.Empty;
    public string GpsExpected_EAL_Cohort_Eng_Previous2_Num { get; set; } = string.Empty;
    public string GpsExpected_NMo_Cohort_Eng_Current_Num { get; set; } = string.Empty;
    public string GpsExpected_NMo_Cohort_Eng_Previous_Num { get; set; } = string.Empty;
    public string GpsExpected_NMo_Cohort_Eng_Previous2_Num { get; set; } = string.Empty;
    public string GpsExpected_Mob_Cohort_Eng_Current_Num { get; set; } = string.Empty;
    public string GpsExpected_Mob_Cohort_Eng_Previous_Num { get; set; } = string.Empty;
    public string GpsExpected_Mob_Cohort_Eng_Previous2_Num { get; set; } = string.Empty;
}
