// This file is automatically generated by SAPSec.ModelGenerator.
// Please do not manually edit this file or your changes will be lost when the file is regenerated.

using System.Diagnostics.CodeAnalysis;

namespace SAPSec.Data.Dto.KS2.Performance;

[ExcludeFromCodeCoverage]
public class EstablishmentPerformance
{
    public string Id { get; set; } = string.Empty;
    public string RwmExpected_Tot_Cohort_Est_Current_Num { get; set; } = string.Empty;
    public string RwmExpected_Tot_Cohort_Est_Previous_Num { get; set; } = string.Empty;
    public string RwmExpected_Tot_Cohort_Est_Previous2_Num { get; set; } = string.Empty;
    public string RwmExpected_Boy_Cohort_Est_Current_Num { get; set; } = string.Empty;
    public string RwmExpected_Boy_Cohort_Est_Previous_Num { get; set; } = string.Empty;
    public string RwmExpected_Boy_Cohort_Est_Previous2_Num { get; set; } = string.Empty;
    public string RwmExpected_Grl_Cohort_Est_Current_Num { get; set; } = string.Empty;
    public string RwmExpected_Grl_Cohort_Est_Previous_Num { get; set; } = string.Empty;
    public string RwmExpected_Grl_Cohort_Est_Previous2_Num { get; set; } = string.Empty;
    public string RwmExpected_Dis_Cohort_Est_Current_Num { get; set; } = string.Empty;
    public string RwmExpected_Dis_Cohort_Est_Previous_Num { get; set; } = string.Empty;
    public string RwmExpected_Dis_Cohort_Est_Previous2_Num { get; set; } = string.Empty;
    public string RwmExpected_NDi_Cohort_Est_Current_Num { get; set; } = string.Empty;
    public string RwmExpected_NDi_Cohort_Est_Previous_Num { get; set; } = string.Empty;
    public string RwmExpected_NDi_Cohort_Est_Previous2_Num { get; set; } = string.Empty;
    public string RwmExpected_SENEHC_Cohort_Est_Current_Num { get; set; } = string.Empty;
    public string RwmExpected_SENEHC_Cohort_Est_Previous_Num { get; set; } = string.Empty;
    public string RwmExpected_SENEHC_Cohort_Est_Previous2_Num { get; set; } = string.Empty;
    public string RwmExpected_SENSup_Cohort_Est_Current_Num { get; set; } = string.Empty;
    public string RwmExpected_SENSup_Cohort_Est_Previous_Num { get; set; } = string.Empty;
    public string RwmExpected_SENSup_Cohort_Est_Previous2_Num { get; set; } = string.Empty;
    public string RwmExpected_NoSEN_Cohort_Est_Current_Num { get; set; } = string.Empty;
    public string RwmExpected_NoSEN_Cohort_Est_Previous_Num { get; set; } = string.Empty;
    public string RwmExpected_NoSEN_Cohort_Est_Previous2_Num { get; set; } = string.Empty;
    public string RwmExpected_EFL_Cohort_Est_Current_Num { get; set; } = string.Empty;
    public string RwmExpected_EFL_Cohort_Est_Previous_Num { get; set; } = string.Empty;
    public string RwmExpected_EFL_Cohort_Est_Previous2_Num { get; set; } = string.Empty;
    public string RwmExpected_EAL_Cohort_Est_Current_Num { get; set; } = string.Empty;
    public string RwmExpected_EAL_Cohort_Est_Previous_Num { get; set; } = string.Empty;
    public string RwmExpected_EAL_Cohort_Est_Previous2_Num { get; set; } = string.Empty;
    public string RwmExpected_NMo_Cohort_Est_Current_Num { get; set; } = string.Empty;
    public string RwmExpected_NMo_Cohort_Est_Previous_Num { get; set; } = string.Empty;
    public string RwmExpected_NMo_Cohort_Est_Previous2_Num { get; set; } = string.Empty;
    public string RwmExpected_Mob_Cohort_Est_Current_Num { get; set; } = string.Empty;
    public string RwmExpected_Mob_Cohort_Est_Previous_Num { get; set; } = string.Empty;
    public string RwmExpected_Mob_Cohort_Est_Previous2_Num { get; set; } = string.Empty;
    public string GpsExpected_Tot_Cohort_Est_Current_Num { get; set; } = string.Empty;
    public string GpsExpected_Tot_Cohort_Est_Previous_Num { get; set; } = string.Empty;
    public string GpsExpected_Tot_Cohort_Est_Previous2_Num { get; set; } = string.Empty;
    public string GpsExpected_Boy_Cohort_Est_Current_Num { get; set; } = string.Empty;
    public string GpsExpected_Boy_Cohort_Est_Previous_Num { get; set; } = string.Empty;
    public string GpsExpected_Boy_Cohort_Est_Previous2_Num { get; set; } = string.Empty;
    public string GpsExpected_Grl_Cohort_Est_Current_Num { get; set; } = string.Empty;
    public string GpsExpected_Grl_Cohort_Est_Previous_Num { get; set; } = string.Empty;
    public string GpsExpected_Grl_Cohort_Est_Previous2_Num { get; set; } = string.Empty;
    public string GpsExpected_Dis_Cohort_Est_Current_Num { get; set; } = string.Empty;
    public string GpsExpected_Dis_Cohort_Est_Previous_Num { get; set; } = string.Empty;
    public string GpsExpected_Dis_Cohort_Est_Previous2_Num { get; set; } = string.Empty;
    public string GpsExpected_NDi_Cohort_Est_Current_Num { get; set; } = string.Empty;
    public string GpsExpected_NDi_Cohort_Est_Previous_Num { get; set; } = string.Empty;
    public string GpsExpected_NDi_Cohort_Est_Previous2_Num { get; set; } = string.Empty;
    public string GpsExpected_SENEHC_Cohort_Est_Current_Num { get; set; } = string.Empty;
    public string GpsExpected_SENEHC_Cohort_Est_Previous_Num { get; set; } = string.Empty;
    public string GpsExpected_SENEHC_Cohort_Est_Previous2_Num { get; set; } = string.Empty;
    public string GpsExpected_SENSup_Cohort_Est_Current_Num { get; set; } = string.Empty;
    public string GpsExpected_SENSup_Cohort_Est_Previous_Num { get; set; } = string.Empty;
    public string GpsExpected_SENSup_Cohort_Est_Previous2_Num { get; set; } = string.Empty;
    public string GpsExpected_NoSEN_Cohort_Est_Current_Num { get; set; } = string.Empty;
    public string GpsExpected_NoSEN_Cohort_Est_Previous_Num { get; set; } = string.Empty;
    public string GpsExpected_NoSEN_Cohort_Est_Previous2_Num { get; set; } = string.Empty;
    public string GpsExpected_EFL_Cohort_Est_Current_Num { get; set; } = string.Empty;
    public string GpsExpected_EFL_Cohort_Est_Previous_Num { get; set; } = string.Empty;
    public string GpsExpected_EFL_Cohort_Est_Previous2_Num { get; set; } = string.Empty;
    public string GpsExpected_EAL_Cohort_Est_Current_Num { get; set; } = string.Empty;
    public string GpsExpected_EAL_Cohort_Est_Previous_Num { get; set; } = string.Empty;
    public string GpsExpected_EAL_Cohort_Est_Previous2_Num { get; set; } = string.Empty;
    public string GpsExpected_NMo_Cohort_Est_Current_Num { get; set; } = string.Empty;
    public string GpsExpected_NMo_Cohort_Est_Previous_Num { get; set; } = string.Empty;
    public string GpsExpected_NMo_Cohort_Est_Previous2_Num { get; set; } = string.Empty;
    public string GpsExpected_Mob_Cohort_Est_Current_Num { get; set; } = string.Empty;
    public string GpsExpected_Mob_Cohort_Est_Previous_Num { get; set; } = string.Empty;
    public string GpsExpected_Mob_Cohort_Est_Previous2_Num { get; set; } = string.Empty;
}
