-- AUTO-GENERATED RAW TABLE DEFINITIONS
DROP TABLE IF EXISTS raw_1a_absence_3term_s_d1b51341;
CREATE TABLE raw_1a_absence_3term_s_d1b51341 (
    "time_period" TEXT,
    "time_identifier" TEXT,
    "geographic_level" TEXT,
    "country_code" TEXT,
    "country_name" TEXT,
    "region_code" TEXT,
    "region_name" TEXT,
    "old_la_code" TEXT,
    "new_la_code" TEXT,
    "la_name" TEXT,
    "education_phase" TEXT,
    "school_name" TEXT,
    "trust" TEXT,
    "estab" TEXT,
    "school_laestab" TEXT,
    "school_urn" TEXT,
    "academy_type" TEXT,
    "academy_open_date" TEXT,
    "all_through" TEXT,
    "num_schools" TEXT,
    "enrolments" TEXT,
    "sess_possible" TEXT,
    "sess_overall" TEXT,
    "sess_authorised" TEXT,
    "sess_unauthorised" TEXT,
    "sess_overall_percent" TEXT,
    "sess_authorised_percent" TEXT,
    "sess_unauthorised_percent" TEXT,
    "enrolments_pa_10_exact" TEXT,
    "enrolments_pa_10_exact_percent" TEXT,
    "sess_possible_pa_10_exact" TEXT,
    "sess_overall_pa_10_exact" TEXT,
    "sess_authorised_pa_10_exact" TEXT,
    "sess_unauthorised_pa_10_exact" TEXT,
    "sess_overall_percent_pa_10_exact" TEXT,
    "sess_authorised_percent_pa_10_exact" TEXT,
    "sess_unauthorised_percent_pa_10_exact" TEXT,
    "enrolments_pa_50_exact" TEXT,
    "enrolments_pa_50_exact_percent" TEXT,
    "sess_auth_illness" TEXT,
    "sess_auth_appointments" TEXT,
    "sess_auth_religious" TEXT,
    "sess_auth_study" TEXT,
    "sess_auth_traveller" TEXT,
    "sess_auth_holiday" TEXT,
    "sess_auth_ext_holiday" TEXT,
    "sess_auth_excluded" TEXT,
    "sess_auth_other" TEXT,
    "sess_auth_totalreasons" TEXT,
    "sess_unauth_holiday" TEXT,
    "sess_unauth_late" TEXT,
    "sess_unauth_other" TEXT,
    "sess_unauth_noyet" TEXT,
    "sess_unauth_totalreasons" TEXT,
    "sess_overall_totalreasons" TEXT,
    "sess_x_covid" TEXT,
    "sess_y_exceptional" TEXT,
    "sess_auth_illness_rate" TEXT,
    "sess_auth_appointments_rate" TEXT,
    "sess_auth_religious_rate" TEXT,
    "sess_auth_study_rate" TEXT,
    "sess_auth_traveller_rate" TEXT,
    "sess_auth_holiday_rate" TEXT,
    "sess_auth_ext_holiday_rate" TEXT,
    "sess_auth_excluded_rate" TEXT,
    "sess_auth_other_rate" TEXT,
    "sess_auth_totalreasons_rate" TEXT,
    "sess_unauth_holiday_rate" TEXT,
    "sess_unauth_late_rate" TEXT,
    "sess_unauth_other_rate" TEXT,
    "sess_unauth_noyet_rate" TEXT,
    "sess_unauth_totalreasons_rate" TEXT,
    "sess_overall_totalreasons_rate" TEXT,
    "sess_x_covid_rate" TEXT
);

DROP TABLE IF EXISTS raw_1_absence_3term_na_2642eb99;
CREATE TABLE raw_1_absence_3term_na_2642eb99 (
    "time_period" TEXT,
    "time_identifier" TEXT,
    "geographic_level" TEXT,
    "country_code" TEXT,
    "country_name" TEXT,
    "region_code" TEXT,
    "region_name" TEXT,
    "old_la_code" TEXT,
    "new_la_code" TEXT,
    "la_name" TEXT,
    "education_phase" TEXT,
    "num_schools" TEXT,
    "enrolments" TEXT,
    "sess_possible" TEXT,
    "sess_overall" TEXT,
    "sess_authorised" TEXT,
    "sess_unauthorised" TEXT,
    "sess_overall_percent" TEXT,
    "sess_authorised_percent" TEXT,
    "sess_unauthorised_percent" TEXT,
    "enrolments_pa_10_exact" TEXT,
    "enrolments_pa_10_exact_percent" TEXT,
    "sess_possible_pa_10_exact" TEXT,
    "sess_overall_pa_10_exact" TEXT,
    "sess_authorised_pa_10_exact" TEXT,
    "sess_unauthorised_pa_10_exact" TEXT,
    "sess_overall_percent_pa_10_exact" TEXT,
    "sess_authorised_percent_pa_10_exact" TEXT,
    "sess_unauthorised_percent_pa_10_exact" TEXT,
    "enrolments_pa_50_exact" TEXT,
    "enrolments_pa_50_exact_percent" TEXT,
    "sess_auth_illness" TEXT,
    "sess_auth_appointments" TEXT,
    "sess_auth_religious" TEXT,
    "sess_auth_study" TEXT,
    "sess_auth_traveller" TEXT,
    "sess_auth_holiday" TEXT,
    "sess_auth_ext_holiday" TEXT,
    "sess_auth_excluded" TEXT,
    "sess_auth_other" TEXT,
    "sess_auth_totalreasons" TEXT,
    "sess_unauth_holiday" TEXT,
    "sess_unauth_late" TEXT,
    "sess_unauth_other" TEXT,
    "sess_unauth_noyet" TEXT,
    "sess_unauth_totalreasons" TEXT,
    "sess_overall_totalreasons" TEXT,
    "sess_x_covid" TEXT,
    "sess_y_exceptional" TEXT,
    "sess_auth_illness_rate" TEXT,
    "sess_auth_appointments_rate" TEXT,
    "sess_auth_religious_rate" TEXT,
    "sess_auth_study_rate" TEXT,
    "sess_auth_traveller_rate" TEXT,
    "sess_auth_holiday_rate" TEXT,
    "sess_auth_ext_holiday_rate" TEXT,
    "sess_auth_excluded_rate" TEXT,
    "sess_auth_other_rate" TEXT,
    "sess_auth_totalreasons_rate" TEXT,
    "sess_unauth_holiday_rate" TEXT,
    "sess_unauth_late_rate" TEXT,
    "sess_unauth_other_rate" TEXT,
    "sess_unauth_noyet_rate" TEXT,
    "sess_unauth_totalreasons_rate" TEXT,
    "sess_overall_totalreasons_rate" TEXT,
    "sess_x_covid_rate" TEXT
);

DROP TABLE IF EXISTS raw_2022_2023_england__28199246;
CREATE TABLE raw_2022_2023_england__28199246 (
    "RECTYPE" TEXT,
    "LEA" TEXT,
    "ESTAB" TEXT,
    "URN" TEXT,
    "SCHNAME" TEXT,
    "SCHNAME_AC" TEXT,
    "ADDRESS1" TEXT,
    "ADDRESS2" TEXT,
    "ADDRESS3" TEXT,
    "TOWN" TEXT,
    "PCODE" TEXT,
    "TELNUM" TEXT,
    "PCON_CODE" TEXT,
    "PCON_NAME" TEXT,
    "CONTFLAG" TEXT,
    "ICLOSE" TEXT,
    "NFTYPE" TEXT,
    "RELDENOM" TEXT,
    "ADMPOL" TEXT,
    "ADMPOL_PT" TEXT,
    "EGENDER" TEXT,
    "FEEDER" TEXT,
    "TABKS2" TEXT,
    "TAB1618" TEXT,
    "AGERANGE" TEXT,
    "TOTPUPS" TEXT,
    "NUMBOYS" TEXT,
    "NUMGIRLS" TEXT,
    "TPUP" TEXT,
    "BPUP" TEXT,
    "PBPUP" TEXT,
    "GPUP" TEXT,
    "PGPUP" TEXT,
    "KS2ASS" TEXT,
    "TPRIORLO" TEXT,
    "PTPRIORLO" TEXT,
    "TPRIORAV" TEXT,
    "PTPRIORAV" TEXT,
    "TPRIORHI" TEXT,
    "PTPRIORHI" TEXT,
    "TFSM6CLA1A" TEXT,
    "PTFSM6CLA1A" TEXT,
    "TNOTFSM6CLA1A" TEXT,
    "PTNOTFSM6CLA1A" TEXT,
    "TEALGRP2" TEXT,
    "PTEALGRP2" TEXT,
    "TEALGRP1" TEXT,
    "PTEALGRP1" TEXT,
    "TEALGRP3" TEXT,
    "PTEALGRP3" TEXT,
    "TNMOB" TEXT,
    "PTNMOB" TEXT,
    "SENE4" TEXT,
    "PSENE4" TEXT,
    "SEN_ALL4" TEXT,
    "PSEN_ALL4" TEXT,
    "SENK4" TEXT,
    "PSENK4" TEXT,
    "TOTATT8" TEXT,
    "ATT8SCR" TEXT,
    "TOTATT8ENG" TEXT,
    "ATT8SCRENG" TEXT,
    "TOTATT8MAT" TEXT,
    "ATT8SCRMAT" TEXT,
    "TOTATT8EBAC" TEXT,
    "ATT8SCREBAC" TEXT,
    "TOTATT8OPEN" TEXT,
    "ATT8SCROPEN" TEXT,
    "TOTATT8OPENG" TEXT,
    "ATT8SCROPENG" TEXT,
    "TOTATT8OPENNG" TEXT,
    "ATT8SCROPENNG" TEXT,
    "AVGEBACFILL" TEXT,
    "AVGOPENFILL" TEXT,
    "P8PUP" TEXT,
    "TP8ADJ" TEXT,
    "P8MEACOV" TEXT,
    "P8MEA" TEXT,
    "P8CILOW" TEXT,
    "P8CIUPP" TEXT,
    "P8MEA_ORIG" TEXT,
    "P8CILOW_ORIG" TEXT,
    "P8CIUPP_ORIG" TEXT,
    "P8MEAENG" TEXT,
    "P8MEAENG_CILOW" TEXT,
    "P8MEAENG_CIUPP" TEXT,
    "P8MEAMAT" TEXT,
    "P8MEAMAT_CILOW" TEXT,
    "P8MEAMAT_CIUPP" TEXT,
    "P8MEAEBAC" TEXT,
    "P8MEAEBAC_CILOW" TEXT,
    "P8MEAEBAC_CIUPP" TEXT,
    "P8MEAOPEN" TEXT,
    "P8MEAOPEN_CILOW" TEXT,
    "P8MEAOPEN_CIUPP" TEXT,
    "PTL2BASICS_94" TEXT,
    "PTL2BASICS_95" TEXT,
    "TOTEBACCAPS" TEXT,
    "EBACCAPS" TEXT,
    "EBACCAPS_FSM6CLA1A" TEXT,
    "EBACCAPS_NFSM6CLA1A" TEXT,
    "EBACCAPS_LO" TEXT,
    "EBACCAPS_MID" TEXT,
    "EBACCAPS_HI" TEXT,
    "EBACCAPS_EAL" TEXT,
    "EBACCAPS_GIRLS" TEXT,
    "EBACCAPS_BOYS" TEXT,
    "EBACCAPS_NMOB" TEXT,
    "EBACCAPS_21" TEXT,
    "EBACCAPS_FSM6CLA1A_21" TEXT,
    "EBACCAPS_NFSM6CLA1A_21" TEXT,
    "EBACCAPS_22" TEXT,
    "EBACCAPS_FSM6CLA1A_22" TEXT,
    "EBACCAPS_NFSM6CLA1A_22" TEXT,
    "TEBACC_E_PTQ_EE" TEXT,
    "PTEBACC_E_PTQ_EE" TEXT,
    "PTEBACC_94" TEXT,
    "PTEBACC_95" TEXT,
    "TEBACENG_E_PTQ_EE" TEXT,
    "PTEBACENG_E_PTQ_EE" TEXT,
    "TEBACMAT_E_PTQ_EE" TEXT,
    "PTEBACMAT_E_PTQ_EE" TEXT,
    "TEBAC2SCI_E_PTQ_EE" TEXT,
    "PTEBAC2SCI_E_PTQ_EE" TEXT,
    "TEBACHUM_E_PTQ_EE" TEXT,
    "PTEBACHUM_E_PTQ_EE" TEXT,
    "TEBACLAN_E_PTQ_EE" TEXT,
    "PTEBACLAN_E_PTQ_EE" TEXT,
    "PTEBACENG_94" TEXT,
    "PTEBACENG_95" TEXT,
    "PTEBACMAT_94" TEXT,
    "PTEBACMAT_95" TEXT,
    "PTEBAC2SCI_94" TEXT,
    "PTEBAC2SCI_95" TEXT,
    "PTEBACHUM_94" TEXT,
    "PTEBACHUM_95" TEXT,
    "PTEBACLAN_94" TEXT,
    "PTEBACLAN_95" TEXT,
    "SCIVAPUP_PTQ_EE" TEXT,
    "SCIVACOV_PTQ_EE" TEXT,
    "HUMVAPUP_PTQ_EE" TEXT,
    "HUMVACOV_PTQ_EE" TEXT,
    "LANVAPUP_PTQ_EE" TEXT,
    "LANVACOV_PTQ_EE" TEXT,
    "SCIVAMEA_PTQ_EE" TEXT,
    "SCIVALOW_PTQ_EE" TEXT,
    "SCIVAUPP_PTQ_EE" TEXT,
    "HUMVAMEA_PTQ_EE" TEXT,
    "HUMVALOW_PTQ_EE" TEXT,
    "HUMVAUPP_PTQ_EE" TEXT,
    "LANVAMEA_PTQ_EE" TEXT,
    "LANVALOW_PTQ_EE" TEXT,
    "LANVAUPP_PTQ_EE" TEXT,
    "TEBACENG_94" TEXT,
    "TEBACENG_95" TEXT,
    "TEBACMAT_94" TEXT,
    "TEBACMAT_95" TEXT,
    "TEBAC2SCI_94" TEXT,
    "TEBAC2SCI_95" TEXT,
    "TEBACHUM_94" TEXT,
    "TEBACHUM_95" TEXT,
    "TEBACLAN_94" TEXT,
    "TEBACLAN_95" TEXT,
    "TEBACC91" TEXT,
    "PTEBACC91" TEXT,
    "TEBACENG91" TEXT,
    "PTEBACENG91" TEXT,
    "TEBACMAT91" TEXT,
    "PTEBACMAT91" TEXT,
    "TEBAC2SCI91" TEXT,
    "PTEBAC2SCI91" TEXT,
    "TEBACHUM91" TEXT,
    "PTEBACHUM91" TEXT,
    "TEBACLAN91" TEXT,
    "PTEBACLAN91" TEXT,
    "ATT8SCR_FSM6CLA1A" TEXT,
    "P8PUP_FSM6CLA1A" TEXT,
    "TP8ADJ_FSM6CLA1A" TEXT,
    "P8MEA_FSM6CLA1A" TEXT,
    "P8CILOW_FSM6CLA1A" TEXT,
    "P8CIUPP_FSM6CLA1A" TEXT,
    "P8MEA_FSM6CLA1A_ORIG" TEXT,
    "P8CILOW_FSM6CLA1A_ORIG" TEXT,
    "P8CIUPP_FSM6CLA1A_ORIG" TEXT,
    "ATT8SCR_NFSM6CLA1A" TEXT,
    "P8PUP_NFSM6CLA1A" TEXT,
    "TP8ADJ_NFSM6CLA1A" TEXT,
    "P8MEA_NFSM6CLA1A" TEXT,
    "P8CILOW_NFSM6CLA1A" TEXT,
    "P8CIUPP_NFSM6CLA1A" TEXT,
    "P8MEA_NFSM6CLA1A_ORIG" TEXT,
    "P8CILOW_NFSM6CLA1A_ORIG" TEXT,
    "P8CIUPP_NFSM6CLA1A_ORIG" TEXT,
    "ATT8SCRENG_FSM6CLA1A" TEXT,
    "P8MEAENG_FSM6CLA1A" TEXT,
    "P8MEAENG_CILOW_FSM6CLA1A" TEXT,
    "P8MEAENG_CIUPP_FSM6CLA1A" TEXT,
    "ATT8SCRMAT_FSM6CLA1A" TEXT,
    "P8MEAMAT_FSM6CLA1A" TEXT,
    "P8MEAMAT_CILOW_FSM6CLA1A" TEXT,
    "P8MEAMAT_CIUPP_FSM6CLA1A" TEXT,
    "ATT8SCREBAC_FSM6CLA1A" TEXT,
    "P8MEAEBAC_FSM6CLA1A" TEXT,
    "P8MEAEBAC_CILOW_FSM6CLA1A" TEXT,
    "P8MEAEBAC_CIUPP_FSM6CLA1A" TEXT,
    "ATT8SCROPEN_FSM6CLA1A" TEXT,
    "P8MEAOPEN_FSM6CLA1A" TEXT,
    "P8MEAOPEN_CILOW_FSM6CLA1A" TEXT,
    "P8MEAOPEN_CIUPP_FSM6CLA1A" TEXT,
    "ATT8SCRENG_NFSM6CLA1A" TEXT,
    "P8MEAENG_NFSM6CLA1A" TEXT,
    "P8MEAENG_CILOW_NFSM6CLA1A" TEXT,
    "P8MEAENG_CIUPP_NFSM6CLA1A" TEXT,
    "ATT8SCRMAT_NFSM6CLA1A" TEXT,
    "P8MEAMAT_NFSM6CLA1A" TEXT,
    "P8MEAMAT_CILOW_NFSM6CLA1A" TEXT,
    "P8MEAMAT_CIUPP_NFSM6CLA1A" TEXT,
    "ATT8SCREBAC_NFSM6CLA1A" TEXT,
    "P8MEAEBAC_NFSM6CLA1A" TEXT,
    "P8MEAEBAC_CILOW_NFSM6CLA1A" TEXT,
    "P8MEAEBAC_CIUPP_NFSM6CLA1A" TEXT,
    "ATT8SCROPEN_NFSM6CLA1A" TEXT,
    "P8MEAOPEN_NFSM6CLA1A" TEXT,
    "P8MEAOPEN_CILOW_NFSM6CLA1A" TEXT,
    "P8MEAOPEN_CIUPP_NFSM6CLA1A" TEXT,
    "ATT8SCROPENG_FSM6CLA1A" TEXT,
    "ATT8SCROPENNG_FSM6CLA1A" TEXT,
    "ATT8SCROPENG_NFSM6CLA1A" TEXT,
    "ATT8SCROPENNG_NFSM6CLA1A" TEXT,
    "DIFFN_ATT8" TEXT,
    "DIFFN_P8MEA" TEXT,
    "ATT8SCR_LO" TEXT,
    "P8PUP_LO" TEXT,
    "TP8ADJ_LO" TEXT,
    "P8MEA_LO" TEXT,
    "P8CILOW_LO" TEXT,
    "P8CIUPP_LO" TEXT,
    "P8MEA_LO_ORIG" TEXT,
    "P8CILOW_LO_ORIG" TEXT,
    "P8CIUPP_LO_ORIG" TEXT,
    "ATT8SCR_MID" TEXT,
    "P8PUP_MID" TEXT,
    "TP8ADJ_MID" TEXT,
    "P8MEA_MID" TEXT,
    "P8CILOW_MID" TEXT,
    "P8CIUPP_MID" TEXT,
    "P8MEA_MID_ORIG" TEXT,
    "P8CILOW_MID_ORIG" TEXT,
    "P8CIUPP_MID_ORIG" TEXT,
    "ATT8SCR_HI" TEXT,
    "P8PUP_HI" TEXT,
    "TP8ADJ_HI" TEXT,
    "P8MEA_HI" TEXT,
    "P8CILOW_HI" TEXT,
    "P8CIUPP_HI" TEXT,
    "P8MEA_HI_ORIG" TEXT,
    "P8CILOW_HI_ORIG" TEXT,
    "P8CIUPP_HI_ORIG" TEXT,
    "ATT8SCR_EAL" TEXT,
    "ATT8SCRENG_EAL" TEXT,
    "ATT8SCRMAT_EAL" TEXT,
    "ATT8SCREBAC_EAL" TEXT,
    "ATT8SCROPEN_EAL" TEXT,
    "ATT8SCROPENG_EAL" TEXT,
    "ATT8SCROPENNG_EAL" TEXT,
    "P8PUP_EAL" TEXT,
    "TP8ADJ_EAL" TEXT,
    "P8MEA_EAL" TEXT,
    "P8CILOW_EAL" TEXT,
    "P8CIUPP_EAL" TEXT,
    "P8MEA_EAL_ORIG" TEXT,
    "P8CILOW_EAL_ORIG" TEXT,
    "P8CIUPP_EAL_ORIG" TEXT,
    "ATT8SCR_GIRLS" TEXT,
    "ATT8SCRENG_GIRLS" TEXT,
    "ATT8SCRMAT_GIRLS" TEXT,
    "ATT8SCREBAC_GIRLS" TEXT,
    "ATT8SCROPEN_GIRLS" TEXT,
    "ATT8SCROPENG_GIRLS" TEXT,
    "ATT8SCROPENNG_GIRLS" TEXT,
    "P8PUP_GIRLS" TEXT,
    "TP8ADJ_GIRLS" TEXT,
    "P8MEA_GIRLS" TEXT,
    "P8CILOW_GIRLS" TEXT,
    "P8CIUPP_GIRLS" TEXT,
    "P8MEA_GIRLS_ORIG" TEXT,
    "P8CILOW_GIRLS_ORIG" TEXT,
    "P8CIUPP_GIRLS_ORIG" TEXT,
    "ATT8SCR_BOYS" TEXT,
    "ATT8SCRENG_BOYS" TEXT,
    "ATT8SCRMAT_BOYS" TEXT,
    "ATT8SCREBAC_BOYS" TEXT,
    "ATT8SCROPEN_BOYS" TEXT,
    "ATT8SCROPENG_BOYS" TEXT,
    "ATT8SCROPENNG_BOYS" TEXT,
    "P8PUP_BOYS" TEXT,
    "TP8ADJ_BOYS" TEXT,
    "P8MEA_BOYS" TEXT,
    "P8CILOW_BOYS" TEXT,
    "P8CIUPP_BOYS" TEXT,
    "P8MEA_BOYS_ORIG" TEXT,
    "P8CILOW_BOYS_ORIG" TEXT,
    "P8CIUPP_BOYS_ORIG" TEXT,
    "ATT8SCR_NMOB" TEXT,
    "ATT8SCRENG_NMOB" TEXT,
    "ATT8SCRMAT_NMOB" TEXT,
    "ATT8SCREBAC_NMOB" TEXT,
    "ATT8SCROPEN_NMOB" TEXT,
    "ATT8SCROPENG_NMOB" TEXT,
    "ATT8SCROPENNG_NMOB" TEXT,
    "P8PUP_NMOB" TEXT,
    "TP8ADJ_NMOB" TEXT,
    "P8MEA_NMOB" TEXT,
    "P8CILOW_NMOB" TEXT,
    "P8CIUPP_NMOB" TEXT,
    "P8MEA_NMOB_ORIG" TEXT,
    "P8CILOW_NMOB_ORIG" TEXT,
    "P8CIUPP_NMOB_ORIG" TEXT,
    "ATT8SCR_21" TEXT,
    "P8PUP_21" TEXT,
    "P8MEA_21" TEXT,
    "P8CILOW_21" TEXT,
    "P8CIUPP_21" TEXT,
    "ATT8SCR_FSM6CLA1A_21" TEXT,
    "P8PUP_FSM6CLA1A_21" TEXT,
    "P8MEA_FSM6CLA1A_21" TEXT,
    "P8CILOW_FSM6CLA1A_21" TEXT,
    "P8CIUPP_FSM6CLA1A_21" TEXT,
    "ATT8SCR_NFSM6CLA1A_21" TEXT,
    "P8PUP_NFSM6CLA1A_21" TEXT,
    "P8MEA_NFSM6CLA1A_21" TEXT,
    "P8CILOW_NFSM6CLA1A_21" TEXT,
    "P8CIUPP_NFSM6CLA1A_21" TEXT,
    "ATT8SCR_22" TEXT,
    "P8PUP_22" TEXT,
    "P8MEA_22" TEXT,
    "P8CILOW_22" TEXT,
    "P8CIUPP_22" TEXT,
    "ATT8SCR_FSM6CLA1A_22" TEXT,
    "P8PUP_FSM6CLA1A_22" TEXT,
    "P8MEA_FSM6CLA1A_22" TEXT,
    "P8CILOW_FSM6CLA1A_22" TEXT,
    "P8CIUPP_FSM6CLA1A_22" TEXT,
    "ATT8SCR_NFSM6CLA1A_22" TEXT,
    "P8PUP_NFSM6CLA1A_22" TEXT,
    "P8MEA_NFSM6CLA1A_22" TEXT,
    "P8CILOW_NFSM6CLA1A_22" TEXT,
    "P8CIUPP_NFSM6CLA1A_22" TEXT,
    "TEBACC_ELO_PTQ_EE" TEXT,
    "PTEBACC_ELO_PTQ_EE" TEXT,
    "PTEBACCLO_94" TEXT,
    "PTEBACCLO_95" TEXT,
    "TEBACC_EAV_PTQ_EE" TEXT,
    "PTEBACC_EAV_PTQ_EE" TEXT,
    "PTEBACCAV_94" TEXT,
    "PTEBACCAV_95" TEXT,
    "TEBACC_EHI_PTQ_EE" TEXT,
    "PTEBACC_EHI_PTQ_EE" TEXT,
    "PTEBACCHI_94" TEXT,
    "PTEBACCHI_95" TEXT,
    "PTEBACC_EFSM6CLA1A_PTQ_EE" TEXT,
    "PTEBACC_ENFSM6CLA1A_PTQ_EE" TEXT,
    "PTEBACC_94_FSM6CLA1A" TEXT,
    "PTEBACC_95_FSM6CLA1A" TEXT,
    "PTEBACC_94_NFSM6CLA1A" TEXT,
    "PTEBACC_95_NFSM6CLA1A" TEXT,
    "SCIVAMEA_LO_PTQ_EE" TEXT,
    "SCIVAMEA_MID_PTQ_EE" TEXT,
    "SCIVAMEA_HI_PTQ_EE" TEXT,
    "SCIVAMEA_FSM6CLA1A_PTQ_EE" TEXT,
    "SCIVAMEA_NFSM6CLA1A_PTQ_EE" TEXT,
    "HUMVAMEA_LO_PTQ_EE" TEXT,
    "HUMVAMEA_MID_PTQ_EE" TEXT,
    "HUMVAMEA_HI_PTQ_EE" TEXT,
    "HUMVAMEA_FSM6CLA1A_PTQ_EE" TEXT,
    "HUMVAMEA_NFSM6CLA1A_PTQ_EE" TEXT,
    "LANVAMEA_LO_PTQ_EE" TEXT,
    "LANVAMEA_MID_PTQ_EE" TEXT,
    "LANVAMEA_HI_PTQ_EE" TEXT,
    "LANVAMEA_FSM6CLA1A_PTQ_EE" TEXT,
    "LANVAMEA_NFSM6CLA1A_PTQ_EE" TEXT,
    "SCIVAUPP_FSM6CLA1A_PTQ_EE" TEXT,
    "SCIVALOW_FSM6CLA1A_PTQ_EE" TEXT,
    "SCIVAUPP_NFSM6CLA1A_PTQ_EE" TEXT,
    "SCIVALOW_NFSM6CLA1A_PTQ_EE" TEXT,
    "SCIVAUPP_LO_PTQ_EE" TEXT,
    "SCIVALOW_LO_PTQ_EE" TEXT,
    "SCIVAUPP_MID_PTQ_EE" TEXT,
    "SCIVALOW_MID_PTQ_EE" TEXT,
    "SCIVAUPP_HI_PTQ_EE" TEXT,
    "SCIVALOW_HI_PTQ_EE" TEXT,
    "HUMVAUPP_FSM6CLA1A_PTQ_EE" TEXT,
    "HUMVALOW_FSM6CLA1A_PTQ_EE" TEXT,
    "HUMVAUPP_NFSM6CLA1A_PTQ_EE" TEXT,
    "HUMVALOW_NFSM6CLA1A_PTQ_EE" TEXT,
    "HUMVAUPP_LO_PTQ_EE" TEXT,
    "HUMVALOW_LO_PTQ_EE" TEXT,
    "HUMVAUPP_MID_PTQ_EE" TEXT,
    "HUMVALOW_MID_PTQ_EE" TEXT,
    "HUMVAUPP_HI_PTQ_EE" TEXT,
    "HUMVALOW_HI_PTQ_EE" TEXT,
    "LANVAUPP_FSM6CLA1A_PTQ_EE" TEXT,
    "LANVALOW_FSM6CLA1A_PTQ_EE" TEXT,
    "LANVAUPP_NFSM6CLA1A_PTQ_EE" TEXT,
    "LANVALOW_NFSM6CLA1A_PTQ_EE" TEXT,
    "LANVAUPP_LO_PTQ_EE" TEXT,
    "LANVALOW_LO_PTQ_EE" TEXT,
    "LANVAUPP_MID_PTQ_EE" TEXT,
    "LANVALOW_MID_PTQ_EE" TEXT,
    "LANVAUPP_HI_PTQ_EE" TEXT,
    "LANVALOW_HI_PTQ_EE" TEXT,
    "PTEBACC_E_21_PTQ_EE" TEXT,
    "PTEBACC_94_21" TEXT,
    "PTEBACC_95_21" TEXT,
    "PTEBACC_E_22_PTQ_EE" TEXT,
    "PTEBACC_94_22" TEXT,
    "PTEBACC_95_22" TEXT,
    "PBEBACC_E_PTQ_EE" TEXT,
    "PBEBACC_94" TEXT,
    "PBEBACC_95" TEXT,
    "PGEBACC_E_PTQ_EE" TEXT,
    "PGEBACC_94" TEXT,
    "PGEBACC_95" TEXT,
    "PTEBACC_ENMOB_PTQ_EE" TEXT,
    "PTEBACCNMOB_94" TEXT,
    "PTEBACCNMOB_95" TEXT,
    "PTEBACC_EEAL_PTQ_EE" TEXT,
    "PTEBACCEAL_94" TEXT,
    "PTEBACCEAL_95" TEXT,
    "PTEBACC_EFSM6CLA1A_21" TEXT,
    "PTEBACC_94_FSM6CLA1A_21" TEXT,
    "PTEBACC_95_FSM6CLA1A_21" TEXT,
    "PTEBACC_ENFSM6CLA1A_21" TEXT,
    "PTEBACC_94_NFSM6CLA1A_21" TEXT,
    "PTEBACC_95_NFSM6CLA1A_21" TEXT,
    "PTEBACC_EFSM6CLA1A_22" TEXT,
    "PTEBACC_94_FSM6CLA1A_22" TEXT,
    "PTEBACC_95_FSM6CLA1A_22" TEXT,
    "PTEBACC_ENFSM6CLA1A_22" TEXT,
    "PTEBACC_94_NFSM6CLA1A_22" TEXT,
    "PTEBACC_95_NFSM6CLA1A_22" TEXT,
    "PT5EM_94" TEXT,
    "PT5EM_94_21" TEXT,
    "PT5EM_94_22" TEXT,
    "PTANYQ_PTQ_EE" TEXT,
    "PTL2BASICS_94_21" TEXT,
    "PTL2BASICS_95_21" TEXT,
    "PTL2BASICS_94_22" TEXT,
    "PTL2BASICS_95_22" TEXT,
    "PTFSM6CLA1ABASICS_94" TEXT,
    "PTNOTFSM6CLA1ABASICS_94" TEXT,
    "TBASICSLO_94" TEXT,
    "PTBASICSLO_94" TEXT,
    "TBASICSAV_94" TEXT,
    "PTBASICSAV_94" TEXT,
    "TBASICSHI_94" TEXT,
    "PTBASICSHI_94" TEXT,
    "PBL2BASICS_94" TEXT,
    "PGL2BASICS_94" TEXT,
    "PTL2BASICSEAL_94" TEXT,
    "PTL2BASICSNMOB_94" TEXT,
    "PTFSM6CLA1ABASICS_95" TEXT,
    "PTNOTFSM6CLA1ABASICS_95" TEXT,
    "TBASICSLO_95" TEXT,
    "PTBASICSLO_95" TEXT,
    "TBASICSAV_95" TEXT,
    "PTBASICSAV_95" TEXT,
    "TBASICSHI_95" TEXT,
    "PTBASICSHI_95" TEXT,
    "PBL2BASICS_95" TEXT,
    "PGL2BASICS_95" TEXT,
    "PTL2BASICSEAL_95" TEXT,
    "PTL2BASICSNMOB_95" TEXT,
    "PTFSM6CLA1ABASICS_94_21" TEXT,
    "PTFSM6CLA1ABASICS_95_21" TEXT,
    "PTNOTFSM6CLA1ABASICS_94_21" TEXT,
    "PTNOTFSM6CLA1ABASICS_95_21" TEXT,
    "PTFSM6CLA1ABASICS_94_22" TEXT,
    "PTFSM6CLA1ABASICS_95_22" TEXT,
    "PTNOTFSM6CLA1ABASICS_94_22" TEXT,
    "PTNOTFSM6CLA1ABASICS_95_22" TEXT,
    "PTmultiLan_E" TEXT,
    "PTtripleSci_E" TEXT,
    "TFSM6CLA1A_21" TEXT,
    "PTFSM6CLA1A_21" TEXT,
    "TNOTFSM6CLA1A_21" TEXT,
    "PTNOTFSM6CLA1A_21" TEXT,
    "TFSM6CLA1A_22" TEXT,
    "PTFSM6CLA1A_22" TEXT,
    "TNOTFSM6CLA1A_22" TEXT,
    "PTNOTFSM6CLA1A_22" TEXT,
    "TAVENT_E_3NG_PTQ_EE" TEXT,
    "TAVENT_E_3NG_LO_PTQ_EE" TEXT,
    "TAVENT_E_3NG_MID_PTQ_EE" TEXT,
    "TAVENT_E_3NG_HI_PTQ_EE" TEXT,
    "TAVENT_E_3NG_FSM6CLA1A_PTQ_EE" TEXT,
    "TAVENT_E_3NG_NFSM6CLA1A_PTQ_EE" TEXT,
    "TAVENT_EFSM6CLA1A_21_PTQ_EE" TEXT,
    "TAVENT_ENFSM6CLA1A_21_PTQ_EE" TEXT,
    "TAVENT_EFSM6CLA1A_22_PTQ_EE" TEXT,
    "TAVENT_ENFSM6CLA1A_22_PTQ_EE" TEXT,
    "TAVENT_G_PTQ_EE" TEXT,
    "TAVENT_GLO_PTQ_EE" TEXT,
    "TAVENT_GAV_PTQ_EE" TEXT,
    "TAVENT_GHI_PTQ_EE" TEXT,
    "TAVENT_GFSM6CLA1A_PTQ_EE" TEXT,
    "TAVENT_GNFSM6CLA1A_PTQ_EE" TEXT,
    "TAVENT_GFSM6CLA1A_21_PTQ_EE" TEXT,
    "TAVENT_GNFSM6CLA1A_21_PTQ_EE" TEXT,
    "TAVENT_GFSM6CLA1A_22_PTQ_EE" TEXT,
    "TAVENT_GNFSM6CLA1A_22_PTQ_EE" TEXT,
    "TTOTENT_E_TOTAL_PTQ_EE" TEXT,
    "TTOTENT_E_COVID_IMPACTED_PTQ_EE" TEXT,
    "PTOTENT_E_COVID_IMPACTED_PTQ_EE" TEXT,
    "P8_BANDING" TEXT
);

DROP TABLE IF EXISTS raw_202324_la_char_dat_34c2fcb1;
CREATE TABLE raw_202324_la_char_dat_34c2fcb1 (
    "time_period" TEXT,
    "time_identifier" TEXT,
    "geographic_level" TEXT,
    "country_code" TEXT,
    "country_name" TEXT,
    "region_code" TEXT,
    "region_name" TEXT,
    "old_la_code" TEXT,
    "new_la_code" TEXT,
    "la_name" TEXT,
    "version" TEXT,
    "education_investment_area_flag" TEXT,
    "priority_area_flag" TEXT,
    "establishment_type_group" TEXT,
    "breakdown" TEXT,
    "sex" TEXT,
    "ethnicity_major" TEXT,
    "ethnicity_minor" TEXT,
    "free_school_meals" TEXT,
    "sen_provision" TEXT,
    "sen_status" TEXT,
    "disadvantage" TEXT,
    "first_language" TEXT,
    "t_schools" TEXT,
    "t_pupils" TEXT,
    "t_att8" TEXT,
    "avg_att8" TEXT,
    "t_entbasics" TEXT,
    "pt_entbasics" TEXT,
    "t_l2basics_95" TEXT,
    "pt_l2basics_95" TEXT,
    "t_l2basics_94" TEXT,
    "pt_l2basics_94" TEXT,
    "t_ebacc_e_ptq_ee" TEXT,
    "pt_ebacc_e_ptq_ee" TEXT,
    "t_ebacc_95" TEXT,
    "pt_ebacc_95" TEXT,
    "t_ebacc_94" TEXT,
    "pt_ebacc_94" TEXT,
    "t_ebaccaps" TEXT,
    "avg_ebaccaps" TEXT,
    "t_inp8calc" TEXT,
    "t_p8score" TEXT,
    "avg_p8score" TEXT,
    "p8score_ci_low" TEXT,
    "p8score_ci_upp" TEXT
);

DROP TABLE IF EXISTS raw_202324_performance_371eb4e5;
CREATE TABLE raw_202324_performance_371eb4e5 (
    "time_period" TEXT,
    "time_identifier" TEXT,
    "geographic_level" TEXT,
    "country_code" TEXT,
    "country_name" TEXT,
    "school_laestab" TEXT,
    "school_urn" TEXT,
    "school_name" TEXT,
    "old_la_code" TEXT,
    "new_la_code" TEXT,
    "la_name" TEXT,
    "version" TEXT,
    "establishment_type_group" TEXT,
    "breakdown_topic" TEXT,
    "breakdown" TEXT,
    "sex" TEXT,
    "disadvantage" TEXT,
    "first_language" TEXT,
    "prior_attainment" TEXT,
    "mobility" TEXT,
    "t_pupils" TEXT,
    "t_att8" TEXT,
    "avg_att8" TEXT,
    "t_entbasics" TEXT,
    "pt_entbasics" TEXT,
    "t_l2basics_95" TEXT,
    "pt_l2basics_95" TEXT,
    "t_l2basics_94" TEXT,
    "pt_l2basics_94" TEXT,
    "t_ebacc_e_ptq_ee" TEXT,
    "pt_ebacc_e_ptq_ee" TEXT,
    "t_ebacc_95" TEXT,
    "pt_ebacc_95" TEXT,
    "t_ebacc_94" TEXT,
    "pt_ebacc_94" TEXT,
    "t_ebaccaps" TEXT,
    "avg_ebaccaps" TEXT,
    "t_inp8calc" TEXT,
    "t_p8score" TEXT,
    "avg_p8score" TEXT,
    "p8score_ci_low" TEXT,
    "p8score_ci_upp" TEXT,
    "t_p8eng" TEXT,
    "avg_p8eng" TEXT,
    "p8eng_ci_low" TEXT,
    "p8eng_ci_upp" TEXT,
    "t_p8mat" TEXT,
    "avg_p8mat" TEXT,
    "p8mat_ci_low" TEXT,
    "p8mat_ci_upp" TEXT,
    "t_p8ebac" TEXT,
    "avg_p8ebac" TEXT,
    "p8ebac_ci_low" TEXT,
    "p8ebac_ci_upp" TEXT,
    "t_p8open" TEXT,
    "avg_p8open" TEXT,
    "p8open_ci_low" TEXT,
    "p8open_ci_upp" TEXT,
    "t_anypass" TEXT,
    "pt_anypass" TEXT,
    "t_ebaceng_e" TEXT,
    "pt_ebaceng_e" TEXT,
    "t_ebacmat_e" TEXT,
    "pt_ebacmat_e" TEXT,
    "t_ebac2sci_e" TEXT,
    "pt_ebac2sci_e" TEXT,
    "t_ebachum_e" TEXT,
    "pt_ebachum_e" TEXT,
    "t_ebaclan_e" TEXT,
    "pt_ebaclan_e" TEXT,
    "t_ebaceng_95" TEXT,
    "pt_ebaceng_95" TEXT,
    "t_ebacmat_95" TEXT,
    "pt_ebacmat_95" TEXT,
    "t_ebac2sci_95" TEXT,
    "pt_ebac2sci_95" TEXT,
    "t_ebachum_95" TEXT,
    "pt_ebachum_95" TEXT,
    "t_ebaclan_95" TEXT,
    "pt_ebaclan_95" TEXT,
    "t_ebaceng_94" TEXT,
    "pt_ebaceng_94" TEXT,
    "t_ebacmat_94" TEXT,
    "pt_ebacmat_94" TEXT,
    "t_ebac2sci_94" TEXT,
    "pt_ebac2sci_94" TEXT,
    "t_ebachum_94" TEXT,
    "pt_ebachum_94" TEXT,
    "t_ebaclan_94" TEXT,
    "pt_ebaclan_94" TEXT,
    "t_att8_eng" TEXT,
    "avg_att8_eng" TEXT,
    "t_att8_mat" TEXT,
    "avg_att8_mat" TEXT,
    "t_att8_ebac" TEXT,
    "avg_att8_ebac" TEXT,
    "t_att8_open" TEXT,
    "avg_att8_open" TEXT,
    "t_att8_open_g" TEXT,
    "avg_att8_open_g" TEXT,
    "t_att8_open_ng" TEXT,
    "avg_att8_open_ng" TEXT,
    "t_ebac_fill" TEXT,
    "avg_ebac_fill" TEXT,
    "t_open_fill" TEXT,
    "avg_open_fill" TEXT,
    "t_triplesci_e" TEXT,
    "pt_triplesci_e" TEXT,
    "t_multilan_e" TEXT,
    "pt_multilan_e" TEXT,
    "t_ebaceng_91" TEXT,
    "pt_ebaceng_91" TEXT,
    "t_ebacmat_91" TEXT,
    "pt_ebacmat_91" TEXT,
    "t_ebac2sci_91" TEXT,
    "pt_ebac2sci_91" TEXT,
    "t_ebachum_91" TEXT,
    "pt_ebachum_91" TEXT,
    "t_ebaclan_91" TEXT,
    "pt_ebaclan_91" TEXT,
    "t_ebacc_91" TEXT,
    "pt_ebacc_91" TEXT,
    "t_5em_94" TEXT,
    "pt_5em_94" TEXT,
    "pt_inp8calc" TEXT,
    "t_adjp8" TEXT,
    "pt_adjp8" TEXT,
    "t_p8orig" TEXT,
    "avg_p8orig" TEXT,
    "p8orig_ci_low" TEXT,
    "p8orig_ci_upp" TEXT,
    "t_inscivacalc" TEXT,
    "pt_inscivacalc" TEXT,
    "t_vasci" TEXT,
    "avg_vasci" TEXT,
    "vasci_ci_low" TEXT,
    "vasci_ci_upp" TEXT,
    "t_inhumvacalc" TEXT,
    "pt_inhumvacalc" TEXT,
    "t_vahum" TEXT,
    "avg_vahum" TEXT,
    "vahum_ci_low" TEXT,
    "vahum_ci_upp" TEXT,
    "t_inlanvacalc" TEXT,
    "pt_inlanvacalc" TEXT,
    "t_valan" TEXT,
    "avg_valan" TEXT,
    "valan_ci_low" TEXT,
    "valan_ci_upp" TEXT,
    "t_ks4_e" TEXT,
    "avg_ks4_e" TEXT,
    "t_gcse_e" TEXT,
    "avg_gcse_e" TEXT,
    "t_volume_e" TEXT,
    "avg_volume_e" TEXT,
    "t_volume_covidimpacted_e" TEXT,
    "pt_volume_covidimpacted_e" TEXT
);

DROP TABLE IF EXISTS raw_202324_subject_pup_2ab324f6;
CREATE TABLE raw_202324_subject_pup_2ab324f6 (
    "time_period" TEXT,
    "time_identifier" TEXT,
    "geographic_level" TEXT,
    "country_code" TEXT,
    "country_name" TEXT,
    "region_code" TEXT,
    "region_name" TEXT,
    "old_la_code" TEXT,
    "new_la_code" TEXT,
    "la_name" TEXT,
    "version" TEXT,
    "establishment_type_group" TEXT,
    "qualification_type" TEXT,
    "subject" TEXT,
    "sex" TEXT,
    "grade" TEXT,
    "number_achieving" TEXT,
    "percentage_achieving" TEXT
);

DROP TABLE IF EXISTS raw_202324_subject_sch_84751f47;
CREATE TABLE raw_202324_subject_sch_84751f47 (
    "time_period" TEXT,
    "time_identifier" TEXT,
    "geographic_level" TEXT,
    "country_code" TEXT,
    "country_name" TEXT,
    "school_laestab" TEXT,
    "school_urn" TEXT,
    "school_name" TEXT,
    "old_la_code" TEXT,
    "new_la_code" TEXT,
    "la_name" TEXT,
    "version" TEXT,
    "establishment_type_group" TEXT,
    "t_pupils" TEXT,
    "qualification_type" TEXT,
    "qualification_detailed" TEXT,
    "grade_structure" TEXT,
    "discount_code" TEXT,
    "subject_discount_group" TEXT,
    "subject_detailed" TEXT,
    "subject" TEXT,
    "grade" TEXT,
    "number_achieving" TEXT
);

DROP TABLE IF EXISTS raw_202425_all_state_f_2d605f2b;
CREATE TABLE raw_202425_all_state_f_2d605f2b (
    "time_period" TEXT,
    "time_identifier" TEXT,
    "geographic_level" TEXT,
    "country_code" TEXT,
    "country_name" TEXT,
    "region_code" TEXT,
    "region_name" TEXT,
    "old_la_code" TEXT,
    "new_la_code" TEXT,
    "la_name" TEXT,
    "version" TEXT,
    "education_investment_area_flag" TEXT,
    "priority_area_flag" TEXT,
    "establishment_type_group" TEXT,
    "breakdown_topic" TEXT,
    "sex" TEXT,
    "ethnicity_major" TEXT,
    "ethnicity_minor" TEXT,
    "fsm_status" TEXT,
    "sen_provision" TEXT,
    "sen_status" TEXT,
    "sen_primary_need" TEXT,
    "disadvantage_status" TEXT,
    "first_language" TEXT,
    "prior_attainment" TEXT,
    "ks2_scaled_score_group" TEXT,
    "mobility" TEXT,
    "young_carer" TEXT,
    "school_admission_type" TEXT,
    "school_religious_character" TEXT,
    "school_count" TEXT,
    "pupil_count" TEXT,
    "attainment8_sum" TEXT,
    "attainment8_average" TEXT,
    "engmath_entering_total" TEXT,
    "engmath_entering_percent" TEXT,
    "engmath_95_total" TEXT,
    "engmath_95_percent" TEXT,
    "engmath_94_total" TEXT,
    "engmath_94_percent" TEXT,
    "ebacc_entering_total" TEXT,
    "ebacc_entering_percent" TEXT,
    "ebacc_95_total" TEXT,
    "ebacc_95_percent" TEXT,
    "ebacc_94_total" TEXT,
    "ebacc_94_percent" TEXT,
    "ebacc_aps_sum" TEXT,
    "ebacc_aps_average" TEXT,
    "progress8_pupil_count" TEXT,
    "progress8_sum" TEXT,
    "progress8_average" TEXT,
    "progress8_lower_95_ci" TEXT,
    "progress8_upper_95_ci" TEXT,
    "progress8eng_sum" TEXT,
    "progress8eng_average" TEXT,
    "progress8eng_lower_95_ci" TEXT,
    "progress8eng_upper_95_ci" TEXT,
    "progress8mat_sum" TEXT,
    "progress8mat_average" TEXT,
    "progress8mat_lower_95_ci" TEXT,
    "progress8mat_upper_95_ci" TEXT,
    "progress8ebacc_sum" TEXT,
    "progress8ebacc_average" TEXT,
    "progress8ebacc_lower_95_ci" TEXT,
    "progress8ebacc_upper_95_ci" TEXT,
    "progress8open_sum" TEXT,
    "progress8open_average" TEXT,
    "progress8open_lower_95_ci" TEXT,
    "progress8open_upper_95_ci" TEXT,
    "gcse_entering_total" TEXT,
    "gcse_entering_percent" TEXT,
    "gcse_91_total" TEXT,
    "gcse_91_percent" TEXT,
    "ebacceng_entering_total" TEXT,
    "ebacceng_entering_percent" TEXT,
    "ebaccmat_entering_total" TEXT,
    "ebaccmat_entering_percent" TEXT,
    "ebaccsci_entering_total" TEXT,
    "ebaccsci_entering_percent" TEXT,
    "ebacchum_entering_total" TEXT,
    "ebacchum_entering_percent" TEXT,
    "ebacclan_entering_total" TEXT,
    "ebacclan_entering_percent" TEXT,
    "ebacceng_95_total" TEXT,
    "ebacceng_95_percent" TEXT,
    "ebaccmat_95_total" TEXT,
    "ebaccmat_95_percent" TEXT,
    "ebaccsci_95_total" TEXT,
    "ebaccsci_95_percent" TEXT,
    "ebacchum_95_total" TEXT,
    "ebacchum_95_percent" TEXT,
    "ebacclan_95_total" TEXT,
    "ebacclan_95_percent" TEXT,
    "ebacceng_94_total" TEXT,
    "ebacceng_94_percent" TEXT,
    "ebaccmat_94_total" TEXT,
    "ebaccmat_94_percent" TEXT,
    "ebaccsci_94_total" TEXT,
    "ebaccsci_94_percent" TEXT,
    "ebacchum_94_total" TEXT,
    "ebacchum_94_percent" TEXT,
    "ebacclan_94_total" TEXT,
    "ebacclan_94_percent" TEXT,
    "ebacceng_aps_sum" TEXT,
    "ebacceng_aps_average" TEXT,
    "ebaccmat_aps_sum" TEXT,
    "ebaccmat_aps_average" TEXT,
    "ebaccsci_aps_sum" TEXT,
    "ebaccsci_aps_average" TEXT,
    "ebacchum_aps_sum" TEXT,
    "ebacchum_aps_average" TEXT,
    "ebacclan_aps_sum" TEXT,
    "ebacclan_aps_average" TEXT,
    "attainment8eng_sum" TEXT,
    "attainment8eng_average" TEXT,
    "attainment8mat_sum" TEXT,
    "attainment8mat_average" TEXT,
    "attainment8ebacc_sum" TEXT,
    "attainment8ebacc_average" TEXT,
    "attainment8open_sum" TEXT,
    "attainment8open_average" TEXT,
    "attainment8open_gcse_sum" TEXT,
    "attainment8open_gcse_average" TEXT,
    "attainment8open_nongcse_sum" TEXT,
    "attainment8open_nongcse_average" TEXT,
    "attainment8ebacc_slotfill_total" TEXT,
    "attainment8ebacc_slotfill_average" TEXT,
    "attainment8open_slotfill_total" TEXT,
    "attainment8open_slotfill_average" TEXT,
    "ebacc_entering_0pillar_total" TEXT,
    "ebacc_entering_0pillar_percent" TEXT,
    "ebacc_entering_1pillar_total" TEXT,
    "ebacc_entering_1pillar_percent" TEXT,
    "ebacc_entering_2pillar_total" TEXT,
    "ebacc_entering_2pillar_percent" TEXT,
    "ebacc_entering_3pillar_total" TEXT,
    "ebacc_entering_3pillar_percent" TEXT,
    "ebacc_entering_4pillar_total" TEXT,
    "ebacc_entering_4pillar_percent" TEXT,
    "ebaccsci_combpath_entering_total" TEXT,
    "ebaccsci_combpath_entering_percent" TEXT,
    "ebaccsci_indpath_entering_total" TEXT,
    "ebaccsci_indpath_entering_percent" TEXT,
    "sci_triple_entering_total" TEXT,
    "sci_triple_entering_percent" TEXT,
    "geoghist_entering_total" TEXT,
    "geoghist_entering_percent" TEXT,
    "lan_multiple_entering_total" TEXT,
    "lan_multiple_entering_percent" TEXT,
    "art_subject_entering_total" TEXT,
    "art_subject_entering_percent" TEXT,
    "music_qual_entering_total" TEXT,
    "music_qual_entering_percent" TEXT,
    "art_qual_entering_total" TEXT,
    "art_qual_entering_percent" TEXT,
    "ebacceng_91_total" TEXT,
    "ebacceng_91_percent" TEXT,
    "ebaccmat_91_total" TEXT,
    "ebaccmat_91_percent" TEXT,
    "ebaccsci_91_total" TEXT,
    "ebaccsci_91_percent" TEXT,
    "ebacchum_91_total" TEXT,
    "ebacchum_91_percent" TEXT,
    "ebacclan_91_total" TEXT,
    "ebacclan_91_percent" TEXT,
    "ebacc_91_total" TEXT,
    "ebacc_91_percent" TEXT,
    "gcse_five_engmath_total" TEXT,
    "gcse_five_engmath_percent" TEXT,
    "progress8_pupil_percent" TEXT,
    "progress8_adjusted_total" TEXT,
    "progress8_adjusted_percent" TEXT,
    "progress8original_sum" TEXT,
    "progress8original_average" TEXT,
    "progress8original_lower_95_ci" TEXT,
    "progress8original_upper_95_ci" TEXT,
    "valueaddedsci_pupil_count" TEXT,
    "valueaddedsci_pupil_percent" TEXT,
    "valueaddedsci_sum" TEXT,
    "valueaddedsci_average" TEXT,
    "valueaddedsci_lower_95_ci" TEXT,
    "valueaddedsci_upper_95_ci" TEXT,
    "valueaddedhum_pupil_count" TEXT,
    "valueaddedhum_pupil_percent" TEXT,
    "valueaddedhum_sum" TEXT,
    "valueaddedhum_average" TEXT,
    "valueaddedhum_lower_95_ci" TEXT,
    "valueaddedhum_upper_95_ci" TEXT,
    "valueaddedlan_pupil_count" TEXT,
    "valueaddedlan_pupil_percent" TEXT,
    "valueaddedlan_sum" TEXT,
    "valueaddedlan_average" TEXT,
    "valueaddedlan_lower_95_ci" TEXT,
    "valueaddedlan_upper_95_ci" TEXT,
    "qual_entries_sum" TEXT,
    "qual_entries_average" TEXT,
    "gcse_entries_sum" TEXT,
    "gcse_entries_average" TEXT,
    "qual_entries_without_discounting_sum" TEXT,
    "qual_entries_without_discounting_average" TEXT
);

DROP TABLE IF EXISTS raw_202425_performance_3979aec1;
CREATE TABLE raw_202425_performance_3979aec1 (
    "time_period" TEXT,
    "time_identifier" TEXT,
    "geographic_level" TEXT,
    "country_code" TEXT,
    "country_name" TEXT,
    "school_laestab" TEXT,
    "school_urn" TEXT,
    "school_name" TEXT,
    "old_la_code" TEXT,
    "new_la_code" TEXT,
    "la_name" TEXT,
    "version" TEXT,
    "establishment_type_group" TEXT,
    "breakdown_topic" TEXT,
    "breakdown" TEXT,
    "sex" TEXT,
    "disadvantage_status" TEXT,
    "first_language" TEXT,
    "prior_attainment" TEXT,
    "mobility" TEXT,
    "pupil_count" TEXT,
    "pupil_percent" TEXT,
    "attainment8_sum" TEXT,
    "attainment8_average" TEXT,
    "engmath_entering_total" TEXT,
    "engmath_entering_percent" TEXT,
    "engmath_95_total" TEXT,
    "engmath_95_percent" TEXT,
    "engmath_94_total" TEXT,
    "engmath_94_percent" TEXT,
    "ebacc_entering_total" TEXT,
    "ebacc_entering_percent" TEXT,
    "ebacc_95_total" TEXT,
    "ebacc_95_percent" TEXT,
    "ebacc_94_total" TEXT,
    "ebacc_94_percent" TEXT,
    "ebacc_aps_sum" TEXT,
    "ebacc_aps_average" TEXT,
    "progress8_pupil_count" TEXT,
    "progress8_sum" TEXT,
    "progress8_average" TEXT,
    "progress8_lower_95_ci" TEXT,
    "progress8_upper_95_ci" TEXT,
    "progress8eng_sum" TEXT,
    "progress8eng_average" TEXT,
    "progress8eng_lower_95_ci" TEXT,
    "progress8eng_upper_95_ci" TEXT,
    "progress8mat_sum" TEXT,
    "progress8mat_average" TEXT,
    "progress8mat_lower_95_ci" TEXT,
    "progress8mat_upper_95_ci" TEXT,
    "progress8ebacc_sum" TEXT,
    "progress8ebacc_average" TEXT,
    "progress8ebacc_lower_95_ci" TEXT,
    "progress8ebacc_upper_95_ci" TEXT,
    "progress8open_sum" TEXT,
    "progress8open_average" TEXT,
    "progress8open_lower_95_ci" TEXT,
    "progress8open_upper_95_ci" TEXT,
    "gcse_91_total" TEXT,
    "gcse_91_percent" TEXT,
    "ebacceng_entering_total" TEXT,
    "ebacceng_entering_percent" TEXT,
    "ebaccmat_entering_total" TEXT,
    "ebaccmat_entering_percent" TEXT,
    "ebaccsci_entering_total" TEXT,
    "ebaccsci_entering_percent" TEXT,
    "ebacchum_entering_total" TEXT,
    "ebacchum_entering_percent" TEXT,
    "ebacclan_entering_total" TEXT,
    "ebacclan_entering_percent" TEXT,
    "ebacceng_95_total" TEXT,
    "ebacceng_95_percent" TEXT,
    "ebaccmat_95_total" TEXT,
    "ebaccmat_95_percent" TEXT,
    "ebaccsci_95_total" TEXT,
    "ebaccsci_95_percent" TEXT,
    "ebacchum_95_total" TEXT,
    "ebacchum_95_percent" TEXT,
    "ebacclan_95_total" TEXT,
    "ebacclan_95_percent" TEXT,
    "ebacceng_94_total" TEXT,
    "ebacceng_94_percent" TEXT,
    "ebaccmat_94_total" TEXT,
    "ebaccmat_94_percent" TEXT,
    "ebaccsci_94_total" TEXT,
    "ebaccsci_94_percent" TEXT,
    "ebacchum_94_total" TEXT,
    "ebacchum_94_percent" TEXT,
    "ebacclan_94_total" TEXT,
    "ebacclan_94_percent" TEXT,
    "attainment8eng_sum" TEXT,
    "attainment8eng_average" TEXT,
    "attainment8mat_sum" TEXT,
    "attainment8mat_average" TEXT,
    "attainment8ebacc_sum" TEXT,
    "attainment8ebacc_average" TEXT,
    "attainment8open_sum" TEXT,
    "attainment8open_average" TEXT,
    "attainment8open_gcse_sum" TEXT,
    "attainment8open_gcse_average" TEXT,
    "attainment8open_nongcse_sum" TEXT,
    "attainment8open_nongcse_average" TEXT,
    "attainment8ebacc_slotfill_total" TEXT,
    "attainment8ebacc_slotfill_average" TEXT,
    "attainment8open_slotfill_total" TEXT,
    "attainment8open_slotfill_average" TEXT,
    "sci_triple_entering_total" TEXT,
    "sci_triple_entering_percent" TEXT,
    "lan_multiple_entering_total" TEXT,
    "lan_multiple_entering_percent" TEXT,
    "ebacceng_91_total" TEXT,
    "ebacceng_91_percent" TEXT,
    "ebaccmat_91_total" TEXT,
    "ebaccmat_91_percent" TEXT,
    "ebaccsci_91_total" TEXT,
    "ebaccsci_91_percent" TEXT,
    "ebacchum_91_total" TEXT,
    "ebacchum_91_percent" TEXT,
    "ebacclan_91_total" TEXT,
    "ebacclan_91_percent" TEXT,
    "ebacc_91_total" TEXT,
    "ebacc_91_percent" TEXT,
    "gcse_five_engmath_total" TEXT,
    "gcse_five_engmath_percent" TEXT,
    "progress8_pupil_percent" TEXT,
    "progress8_adjusted_total" TEXT,
    "progress8_adjusted_percent" TEXT,
    "progress8original_sum" TEXT,
    "progress8original_average" TEXT,
    "progress8original_lower_95_ci" TEXT,
    "progress8original_upper_95_ci" TEXT,
    "valueaddedsci_pupil_count" TEXT,
    "valueaddedsci_pupil_percent" TEXT,
    "valueaddedsci_sum" TEXT,
    "valueaddedsci_average" TEXT,
    "valueaddedsci_lower_95_ci" TEXT,
    "valueaddedsci_upper_95_ci" TEXT,
    "valueaddedhum_pupil_count" TEXT,
    "valueaddedhum_pupil_percent" TEXT,
    "valueaddedhum_sum" TEXT,
    "valueaddedhum_average" TEXT,
    "valueaddedhum_lower_95_ci" TEXT,
    "valueaddedhum_upper_95_ci" TEXT,
    "valueaddedlan_pupil_count" TEXT,
    "valueaddedlan_pupil_percent" TEXT,
    "valueaddedlan_sum" TEXT,
    "valueaddedlan_average" TEXT,
    "valueaddedlan_lower_95_ci" TEXT,
    "valueaddedlan_upper_95_ci" TEXT,
    "qual_entries_sum" TEXT,
    "qual_entries_average" TEXT,
    "gcse_entries_sum" TEXT,
    "gcse_entries_average" TEXT,
    "qual_entries_without_discounting_sum" TEXT,
    "qual_entries_without_discounting_average" TEXT
);

DROP TABLE IF EXISTS raw_202425_subject_loc_9992c36c;
CREATE TABLE raw_202425_subject_loc_9992c36c (
    "time_period" TEXT,
    "time_identifier" TEXT,
    "geographic_level" TEXT,
    "country_code" TEXT,
    "country_name" TEXT,
    "region_code" TEXT,
    "region_name" TEXT,
    "old_la_code" TEXT,
    "new_la_code" TEXT,
    "la_name" TEXT,
    "version" TEXT,
    "education_investment_area_flag" TEXT,
    "priority_area_flag" TEXT,
    "establishment_type_group" TEXT,
    "breakdown_topic" TEXT,
    "sex" TEXT,
    "qualification_type" TEXT,
    "subject" TEXT,
    "grade" TEXT,
    "number_achieving" TEXT,
    "percentage_achieving" TEXT
);

DROP TABLE IF EXISTS raw_202425_subject_sch_a9a9beac;
CREATE TABLE raw_202425_subject_sch_a9a9beac (
    "time_period" TEXT,
    "time_identifier" TEXT,
    "geographic_level" TEXT,
    "country_code" TEXT,
    "country_name" TEXT,
    "school_laestab" TEXT,
    "school_urn" TEXT,
    "school_name" TEXT,
    "old_la_code" TEXT,
    "new_la_code" TEXT,
    "la_name" TEXT,
    "version" TEXT,
    "establishment_type_group" TEXT,
    "pupil_count" TEXT,
    "qualification_type" TEXT,
    "qualification_detailed" TEXT,
    "grade_structure" TEXT,
    "subject" TEXT,
    "discount_code" TEXT,
    "subject_discount_group" TEXT,
    "grade" TEXT,
    "number_achieving" TEXT
);

DROP TABLE IF EXISTS raw_2223_la_char_data__951c641f;
CREATE TABLE raw_2223_la_char_data__951c641f (
    "time_period" TEXT,
    "time_identifier" TEXT,
    "geographic_level" TEXT,
    "country_code" TEXT,
    "country_name" TEXT,
    "region_code" TEXT,
    "region_name" TEXT,
    "old_la_code" TEXT,
    "new_la_code" TEXT,
    "la_name" TEXT,
    "version" TEXT,
    "education_investment_area_flag" TEXT,
    "priority_area_flag" TEXT,
    "establishment_type" TEXT,
    "breakdown" TEXT,
    "gender" TEXT,
    "ethnicity_major" TEXT,
    "ethnicity_minor" TEXT,
    "free_school_meals" TEXT,
    "sen_status" TEXT,
    "sen_description" TEXT,
    "disadvantage" TEXT,
    "first_language" TEXT,
    "t_schools" TEXT,
    "t_pupils" TEXT,
    "t_att8" TEXT,
    "avg_att8" TEXT,
    "t_entbasics" TEXT,
    "pt_entbasics" TEXT,
    "t_l2basics_95" TEXT,
    "pt_l2basics_95" TEXT,
    "t_l2basics_94" TEXT,
    "pt_l2basics_94" TEXT,
    "t_ebacc_e_ptq_ee" TEXT,
    "pt_ebacc_e_ptq_ee" TEXT,
    "t_ebacc_95" TEXT,
    "pt_ebacc_95" TEXT,
    "t_ebacc_94" TEXT,
    "pt_ebacc_94" TEXT,
    "t_ebaccaps" TEXT,
    "avg_ebaccaps" TEXT,
    "t_inp8calc" TEXT,
    "t_p8score" TEXT,
    "avg_p8score" TEXT,
    "p8score_ci_low" TEXT,
    "p8score_ci_upp" TEXT
);

DROP TABLE IF EXISTS raw_2223_subject_pupil_a6edee97;
CREATE TABLE raw_2223_subject_pupil_a6edee97 (
    "time_period" TEXT,
    "time_identifier" TEXT,
    "geographic_level" TEXT,
    "country_code" TEXT,
    "country_name" TEXT,
    "region_code" TEXT,
    "region_name" TEXT,
    "old_la_code" TEXT,
    "new_la_code" TEXT,
    "la_name" TEXT,
    "version" TEXT,
    "establishment_type" TEXT,
    "qualification_type" TEXT,
    "subject" TEXT,
    "gender" TEXT,
    "grade" TEXT,
    "number_achieving" TEXT,
    "percentage_achieving" TEXT
);

DROP TABLE IF EXISTS raw_edubasealldata2025_4db2d83a;
CREATE TABLE raw_edubasealldata2025_4db2d83a (
    "URN" TEXT,
    "LA (code)" TEXT,
    "LA (name)" TEXT,
    "EstablishmentNumber" TEXT,
    "EstablishmentName" TEXT,
    "TypeOfEstablishment (code)" TEXT,
    "TypeOfEstablishment (name)" TEXT,
    "EstablishmentTypeGroup (code)" TEXT,
    "EstablishmentTypeGroup (name)" TEXT,
    "EstablishmentStatus (code)" TEXT,
    "EstablishmentStatus (name)" TEXT,
    "ReasonEstablishmentOpened (code)" TEXT,
    "ReasonEstablishmentOpened (name)" TEXT,
    "OpenDate" TEXT,
    "ReasonEstablishmentClosed (code)" TEXT,
    "ReasonEstablishmentClosed (name)" TEXT,
    "CloseDate" TEXT,
    "PhaseOfEducation (code)" TEXT,
    "PhaseOfEducation (name)" TEXT,
    "StatutoryLowAge" TEXT,
    "StatutoryHighAge" TEXT,
    "Boarders (code)" TEXT,
    "Boarders (name)" TEXT,
    "NurseryProvision (name)" TEXT,
    "OfficialSixthForm (code)" TEXT,
    "OfficialSixthForm (name)" TEXT,
    "Gender (code)" TEXT,
    "Gender (name)" TEXT,
    "ReligiousCharacter (code)" TEXT,
    "ReligiousCharacter (name)" TEXT,
    "ReligiousEthos (name)" TEXT,
    "Diocese (code)" TEXT,
    "Diocese (name)" TEXT,
    "AdmissionsPolicy (code)" TEXT,
    "AdmissionsPolicy (name)" TEXT,
    "SchoolCapacity" TEXT,
    "SpecialClasses (code)" TEXT,
    "SpecialClasses (name)" TEXT,
    "CensusDate" TEXT,
    "NumberOfPupils" TEXT,
    "NumberOfBoys" TEXT,
    "NumberOfGirls" TEXT,
    "PercentageFSM" TEXT,
    "TrustSchoolFlag (code)" TEXT,
    "TrustSchoolFlag (name)" TEXT,
    "Trusts (code)" TEXT,
    "Trusts (name)" TEXT,
    "SchoolSponsorFlag (name)" TEXT,
    "SchoolSponsors (name)" TEXT,
    "FederationFlag (name)" TEXT,
    "Federations (code)" TEXT,
    "Federations (name)" TEXT,
    "UKPRN" TEXT,
    "FEHEIdentifier" TEXT,
    "FurtherEducationType (name)" TEXT,
    "LastChangedDate" TEXT,
    "Street" TEXT,
    "Locality" TEXT,
    "Address3" TEXT,
    "Town" TEXT,
    "County (name)" TEXT,
    "Postcode" TEXT,
    "SchoolWebsite" TEXT,
    "TelephoneNum" TEXT,
    "HeadTitle (name)" TEXT,
    "HeadFirstName" TEXT,
    "HeadLastName" TEXT,
    "HeadPreferredJobTitle" TEXT,
    "BSOInspectorateName (name)" TEXT,
    "InspectorateReport" TEXT,
    "DateOfLastInspectionVisit" TEXT,
    "NextInspectionVisit" TEXT,
    "TeenMoth (name)" TEXT,
    "TeenMothPlaces" TEXT,
    "CCF (name)" TEXT,
    "SENPRU (name)" TEXT,
    "EBD (name)" TEXT,
    "PlacesPRU" TEXT,
    "FTProv (name)" TEXT,
    "EdByOther (name)" TEXT,
    "Section41Approved (name)" TEXT,
    "SEN1 (name)" TEXT,
    "SEN2 (name)" TEXT,
    "SEN3 (name)" TEXT,
    "SEN4 (name)" TEXT,
    "SEN5 (name)" TEXT,
    "SEN6 (name)" TEXT,
    "SEN7 (name)" TEXT,
    "SEN8 (name)" TEXT,
    "SEN9 (name)" TEXT,
    "SEN10 (name)" TEXT,
    "SEN11 (name)" TEXT,
    "SEN12 (name)" TEXT,
    "SEN13 (name)" TEXT,
    "TypeOfResourcedProvision (name)" TEXT,
    "ResourcedProvisionOnRoll" TEXT,
    "ResourcedProvisionCapacity" TEXT,
    "SenUnitOnRoll" TEXT,
    "SenUnitCapacity" TEXT,
    "GOR (code)" TEXT,
    "GOR (name)" TEXT,
    "DistrictAdministrative (code)" TEXT,
    "DistrictAdministrative (name)" TEXT,
    "AdministrativeWard (code)" TEXT,
    "AdministrativeWard (name)" TEXT,
    "ParliamentaryConstituency (code)" TEXT,
    "ParliamentaryConstituency (name)" TEXT,
    "UrbanRural (code)" TEXT,
    "UrbanRural (name)" TEXT,
    "GSSLACode (name)" TEXT,
    "Easting" TEXT,
    "Northing" TEXT,
    "MSOA (name)" TEXT,
    "LSOA (name)" TEXT,
    "InspectorateName (name)" TEXT,
    "SENStat" TEXT,
    "SENNoStat" TEXT,
    "BoardingEstablishment (name)" TEXT,
    "PropsName" TEXT,
    "PreviousLA (code)" TEXT,
    "PreviousLA (name)" TEXT,
    "PreviousEstablishmentNumber" TEXT,
    "Country (name)" TEXT,
    "UPRN" TEXT,
    "SiteName" TEXT,
    "QABName (code)" TEXT,
    "QABName (name)" TEXT,
    "EstablishmentAccredited (code)" TEXT,
    "EstablishmentAccredited (name)" TEXT,
    "QABReport" TEXT,
    "CHNumber" TEXT,
    "MSOA (code)" TEXT,
    "LSOA (code)" TEXT,
    "FSM" TEXT,
    "AccreditationExpiryDate" TEXT
);

DROP TABLE IF EXISTS raw_ees_ks4_inst_20222_cbe11c27;
CREATE TABLE raw_ees_ks4_inst_20222_cbe11c27 (
    "time_period" TEXT,
    "time_identifier" TEXT,
    "geographic_level" TEXT,
    "country_code" TEXT,
    "country_name" TEXT,
    "region_code" TEXT,
    "region_name" TEXT,
    "old_la_code" TEXT,
    "new_la_code" TEXT,
    "la_name" TEXT,
    "local_authority_selection_status" TEXT,
    "school_laestab" TEXT,
    "school_urn" TEXT,
    "school_name" TEXT,
    "admission_policy" TEXT,
    "entry_gender" TEXT,
    "institution_group" TEXT,
    "institution_type" TEXT,
    "breakdown_topic" TEXT,
    "breakdown" TEXT,
    "data_type" TEXT,
    "version" TEXT,
    "cohort" TEXT,
    "overall" TEXT,
    "education" TEXT,
    "fe" TEXT,
    "ssf" TEXT,
    "sfc" TEXT,
    "other_edu" TEXT,
    "appren" TEXT,
    "all_work" TEXT,
    "all_notsust" TEXT,
    "all_unknown" TEXT
);

DROP TABLE IF EXISTS raw_ees_ks4_la_202223_77d7d168;
CREATE TABLE raw_ees_ks4_la_202223_77d7d168 (
    "time_period" TEXT,
    "time_identifier" TEXT,
    "geographic_level" TEXT,
    "country_code" TEXT,
    "country_name" TEXT,
    "region_code" TEXT,
    "region_name" TEXT,
    "old_la_code" TEXT,
    "new_la_code" TEXT,
    "la_name" TEXT,
    "pcon_code" TEXT,
    "pcon_name" TEXT,
    "lad_code" TEXT,
    "lad_name" TEXT,
    "institution_group" TEXT,
    "institution_type" TEXT,
    "breakdown_topic" TEXT,
    "breakdown" TEXT,
    "data_type" TEXT,
    "version" TEXT,
    "cohort" TEXT,
    "overall" TEXT,
    "education" TEXT,
    "fe" TEXT,
    "ssf" TEXT,
    "sfc" TEXT,
    "other_edu" TEXT,
    "appren" TEXT,
    "appl3" TEXT,
    "appl2" TEXT,
    "all_work" TEXT,
    "all_notsust" TEXT,
    "all_unknown" TEXT
);

DROP TABLE IF EXISTS raw_ees_ks4_nat_202223_6f188ec9;
CREATE TABLE raw_ees_ks4_nat_202223_6f188ec9 (
    "time_period" TEXT,
    "time_identifier" TEXT,
    "geographic_level" TEXT,
    "country_code" TEXT,
    "country_name" TEXT,
    "institution_group" TEXT,
    "institution_type" TEXT,
    "breakdown_topic" TEXT,
    "breakdown" TEXT,
    "data_type" TEXT,
    "version" TEXT,
    "inst_count" TEXT,
    "cohort" TEXT,
    "overall" TEXT,
    "education" TEXT,
    "fe" TEXT,
    "ssf" TEXT,
    "sfc" TEXT,
    "other_edu" TEXT,
    "ind" TEXT,
    "appru" TEXT,
    "special" TEXT,
    "spi" TEXT,
    "edu_combo" TEXT,
    "he" TEXT,
    "appren" TEXT,
    "appl3" TEXT,
    "appl2" TEXT,
    "all_work" TEXT,
    "all_notsust" TEXT,
    "notsust" TEXT,
    "notsust_ben" TEXT,
    "only_ben" TEXT,
    "all_unknown" TEXT,
    "unknown_id" TEXT,
    "unknown" TEXT
);

DROP TABLE IF EXISTS raw_england_ks4underly_effb560d;
CREATE TABLE raw_england_ks4underly_effb560d (
    "Unique Reference Number (URN)" TEXT,
    "School or college name" TEXT,
    "Institution type" TEXT,
    "Pupils at end_KS4" TEXT,
    "Qualification" TEXT,
    "Qualification description" TEXT,
    "Grade structure of qualification" TEXT,
    "Discount Code" TEXT,
    "Subject discount group" TEXT,
    "Subject description" TEXT,
    "GRADE" TEXT,
    "GRADE DESCRIPTION" TEXT,
    "Number of entries at grade" TEXT
);

DROP TABLE IF EXISTS raw_exc_nat_region_la_02f87f3c;
CREATE TABLE raw_exc_nat_region_la_02f87f3c (
    "time_identifier" TEXT,
    "time_period" TEXT,
    "geographic_level" TEXT,
    "country_code" TEXT,
    "country_name" TEXT,
    "region_code" TEXT,
    "region_name" TEXT,
    "old_la_code" TEXT,
    "new_la_code" TEXT,
    "la_name" TEXT,
    "education_phase" TEXT,
    "num_schools" TEXT,
    "headcount" TEXT,
    "perm_excl" TEXT,
    "perm_excl_rate" TEXT,
    "suspension" TEXT,
    "susp_rate" TEXT,
    "one_plus_susp" TEXT,
    "one_plus_susp_rate" TEXT
);

DROP TABLE IF EXISTS raw_exc_school_a1c7f527;
CREATE TABLE raw_exc_school_a1c7f527 (
    "time_identifier" TEXT,
    "time_period" TEXT,
    "geographic_level" TEXT,
    "country_code" TEXT,
    "country_name" TEXT,
    "region_code" TEXT,
    "region_name" TEXT,
    "old_la_code" TEXT,
    "new_la_code" TEXT,
    "la_name" TEXT,
    "estab" TEXT,
    "school_laestab" TEXT,
    "school_urn" TEXT,
    "school_name" TEXT,
    "trust_name" TEXT,
    "academy_type" TEXT,
    "academy_open_date" TEXT,
    "education_phase" TEXT,
    "headcount" TEXT,
    "perm_excl" TEXT,
    "perm_excl_rate" TEXT,
    "suspension" TEXT,
    "susp_rate" TEXT,
    "one_plus_susp" TEXT,
    "one_plus_susp_rate" TEXT
);

DROP TABLE IF EXISTS raw_GIAS_8f9c91c0;
CREATE TABLE raw_GIAS_8f9c91c0 (
    "URN" TEXT,
    "LA (code)" TEXT,
    "LA (name)" TEXT,
    "EstablishmentNumber" TEXT,
    "EstablishmentName" TEXT,
    "TypeOfEstablishment (code)" TEXT,
    "TypeOfEstablishment (name)" TEXT,
    "EstablishmentTypeGroup (code)" TEXT,
    "EstablishmentTypeGroup (name)" TEXT,
    "EstablishmentStatus (code)" TEXT,
    "EstablishmentStatus (name)" TEXT,
    "ReasonEstablishmentOpened (code)" TEXT,
    "ReasonEstablishmentOpened (name)" TEXT,
    "OpenDate" TEXT,
    "ReasonEstablishmentClosed (code)" TEXT,
    "ReasonEstablishmentClosed (name)" TEXT,
    "CloseDate" TEXT,
    "PhaseOfEducation (code)" TEXT,
    "PhaseOfEducation (name)" TEXT,
    "StatutoryLowAge" TEXT,
    "StatutoryHighAge" TEXT,
    "Boarders (code)" TEXT,
    "Boarders (name)" TEXT,
    "NurseryProvision (name)" TEXT,
    "OfficialSixthForm (code)" TEXT,
    "OfficialSixthForm (name)" TEXT,
    "Gender (code)" TEXT,
    "Gender (name)" TEXT,
    "ReligiousCharacter (code)" TEXT,
    "ReligiousCharacter (name)" TEXT,
    "ReligiousEthos (name)" TEXT,
    "Diocese (code)" TEXT,
    "Diocese (name)" TEXT,
    "AdmissionsPolicy (code)" TEXT,
    "AdmissionsPolicy (name)" TEXT,
    "SchoolCapacity" TEXT,
    "SpecialClasses (code)" TEXT,
    "SpecialClasses (name)" TEXT,
    "CensusDate" TEXT,
    "NumberOfPupils" TEXT,
    "NumberOfBoys" TEXT,
    "NumberOfGirls" TEXT,
    "PercentageFSM" TEXT,
    "TrustSchoolFlag (code)" TEXT,
    "TrustSchoolFlag (name)" TEXT,
    "Trusts (code)" TEXT,
    "Trusts (name)" TEXT,
    "SchoolSponsorFlag (name)" TEXT,
    "SchoolSponsors (name)" TEXT,
    "FederationFlag (name)" TEXT,
    "Federations (code)" TEXT,
    "Federations (name)" TEXT,
    "UKPRN" TEXT,
    "FEHEIdentifier" TEXT,
    "FurtherEducationType (name)" TEXT,
    "LastChangedDate" TEXT,
    "Street" TEXT,
    "Locality" TEXT,
    "Address3" TEXT,
    "Town" TEXT,
    "County (name)" TEXT,
    "Postcode" TEXT,
    "SchoolWebsite" TEXT,
    "TelephoneNum" TEXT,
    "HeadTitle (name)" TEXT,
    "HeadFirstName" TEXT,
    "HeadLastName" TEXT,
    "HeadPreferredJobTitle" TEXT,
    "BSOInspectorateName (name)" TEXT,
    "InspectorateReport" TEXT,
    "DateOfLastInspectionVisit" TEXT,
    "NextInspectionVisit" TEXT,
    "TeenMoth (name)" TEXT,
    "TeenMothPlaces" TEXT,
    "CCF (name)" TEXT,
    "SENPRU (name)" TEXT,
    "EBD (name)" TEXT,
    "PlacesPRU" TEXT,
    "FTProv (name)" TEXT,
    "EdByOther (name)" TEXT,
    "Section41Approved (name)" TEXT,
    "SEN1 (name)" TEXT,
    "SEN2 (name)" TEXT,
    "SEN3 (name)" TEXT,
    "SEN4 (name)" TEXT,
    "SEN5 (name)" TEXT,
    "SEN6 (name)" TEXT,
    "SEN7 (name)" TEXT,
    "SEN8 (name)" TEXT,
    "SEN9 (name)" TEXT,
    "SEN10 (name)" TEXT,
    "SEN11 (name)" TEXT,
    "SEN12 (name)" TEXT,
    "SEN13 (name)" TEXT,
    "TypeOfResourcedProvision (name)" TEXT,
    "ResourcedProvisionOnRoll" TEXT,
    "ResourcedProvisionCapacity" TEXT,
    "SenUnitOnRoll" TEXT,
    "SenUnitCapacity" TEXT,
    "GOR (code)" TEXT,
    "GOR (name)" TEXT,
    "DistrictAdministrative (code)" TEXT,
    "DistrictAdministrative (name)" TEXT,
    "AdministrativeWard (code)" TEXT,
    "AdministrativeWard (name)" TEXT,
    "ParliamentaryConstituency (code)" TEXT,
    "ParliamentaryConstituency (name)" TEXT,
    "UrbanRural (code)" TEXT,
    "UrbanRural (name)" TEXT,
    "GSSLACode (name)" TEXT,
    "Easting" TEXT,
    "Northing" TEXT,
    "MSOA (name)" TEXT,
    "LSOA (name)" TEXT,
    "InspectorateName (name)" TEXT,
    "SENStat" TEXT,
    "SENNoStat" TEXT,
    "BoardingEstablishment (name)" TEXT,
    "PropsName" TEXT,
    "PreviousLA (code)" TEXT,
    "PreviousLA (name)" TEXT,
    "PreviousEstablishmentNumber" TEXT,
    "Country (name)" TEXT,
    "UPRN" TEXT,
    "SiteName" TEXT,
    "QABName (code)" TEXT,
    "QABName (name)" TEXT,
    "EstablishmentAccredited (code)" TEXT,
    "EstablishmentAccredited (name)" TEXT,
    "QABReport" TEXT,
    "CHNumber" TEXT,
    "MSOA (code)" TEXT,
    "LSOA (code)" TEXT,
    "FSM" TEXT,
    "AccreditationExpiryDate" TEXT
);

DROP TABLE IF EXISTS raw_ks4_dm_ud_202122_i_d3152640;
CREATE TABLE raw_ks4_dm_ud_202122_i_d3152640 (
    "time_period" TEXT,
    "time_identifier" TEXT,
    "geographic_level" TEXT,
    "country_code" TEXT,
    "country_name" TEXT,
    "region_code" TEXT,
    "region_name" TEXT,
    "old_la_code" TEXT,
    "new_la_code" TEXT,
    "la_name" TEXT,
    "local_authority_selection_status" TEXT,
    "school_laestab" TEXT,
    "school_name" TEXT,
    "admission_policy" TEXT,
    "entry_gender" TEXT,
    "institution_group" TEXT,
    "institution_type" TEXT,
    "breakdown_topic" TEXT,
    "breakdown" TEXT,
    "data_type" TEXT,
    "version" TEXT,
    "cohort" TEXT,
    "overall" TEXT,
    "education" TEXT,
    "fe" TEXT,
    "ssf" TEXT,
    "sfc" TEXT,
    "other_edu" TEXT,
    "appren" TEXT,
    "all_work" TEXT,
    "all_notsust" TEXT,
    "all_unknown" TEXT
);

DROP TABLE IF EXISTS raw_ks4_dm_ud_202122_l_f2233097;
CREATE TABLE raw_ks4_dm_ud_202122_l_f2233097 (
    "time_period" TEXT,
    "time_identifier" TEXT,
    "geographic_level" TEXT,
    "country_code" TEXT,
    "country_name" TEXT,
    "region_code" TEXT,
    "region_name" TEXT,
    "old_la_code" TEXT,
    "new_la_code" TEXT,
    "la_name" TEXT,
    "pcon_code" TEXT,
    "pcon_name" TEXT,
    "lad_code" TEXT,
    "lad_name" TEXT,
    "level_methodology" TEXT,
    "institution_group" TEXT,
    "institution_type" TEXT,
    "breakdown_topic" TEXT,
    "breakdown" TEXT,
    "version" TEXT,
    "data_type" TEXT,
    "cohort" TEXT,
    "overall" TEXT,
    "education" TEXT,
    "fe" TEXT,
    "ssf" TEXT,
    "sfc" TEXT,
    "other_edu" TEXT,
    "appren" TEXT,
    "appl3" TEXT,
    "appl2" TEXT,
    "all_work" TEXT,
    "all_notsust" TEXT,
    "all_unknown" TEXT
);

DROP TABLE IF EXISTS raw_ks4_dm_ud_202122_n_e9fce4c6;
CREATE TABLE raw_ks4_dm_ud_202122_n_e9fce4c6 (
    "time_period" TEXT,
    "time_identifier" TEXT,
    "geographic_level" TEXT,
    "country_code" TEXT,
    "country_name" TEXT,
    "institution_group" TEXT,
    "institution_type" TEXT,
    "breakdown_topic" TEXT,
    "breakdown" TEXT,
    "data_type" TEXT,
    "version" TEXT,
    "inst_count" TEXT,
    "cohort" TEXT,
    "overall" TEXT,
    "education" TEXT,
    "fe" TEXT,
    "ssf" TEXT,
    "sfc" TEXT,
    "other_edu" TEXT,
    "ind" TEXT,
    "appru" TEXT,
    "special" TEXT,
    "spi" TEXT,
    "edu_combo" TEXT,
    "he" TEXT,
    "appren" TEXT,
    "appl3" TEXT,
    "appl2" TEXT,
    "all_work" TEXT,
    "all_notsust" TEXT,
    "notsust" TEXT,
    "notsust_beneet" TEXT,
    "only_beneet" TEXT,
    "all_unknown" TEXT,
    "unknown_id" TEXT,
    "unknown" TEXT
);

DROP TABLE IF EXISTS raw_ks4_dm_ud_202223_i_49ea482a;
CREATE TABLE raw_ks4_dm_ud_202223_i_49ea482a (
    "time_period" TEXT,
    "time_identifier" TEXT,
    "geographic_level" TEXT,
    "country_code" TEXT,
    "country_name" TEXT,
    "region_code" TEXT,
    "region_name" TEXT,
    "old_la_code" TEXT,
    "new_la_code" TEXT,
    "la_name" TEXT,
    "local_authority_selection_status" TEXT,
    "school_urn" TEXT,
    "school_laestab" TEXT,
    "school_name" TEXT,
    "admission_policy" TEXT,
    "entry_gender" TEXT,
    "institution_group" TEXT,
    "institution_type" TEXT,
    "breakdown_topic" TEXT,
    "breakdown" TEXT,
    "data_type" TEXT,
    "version" TEXT,
    "cohort" TEXT,
    "overall" TEXT,
    "education" TEXT,
    "fe" TEXT,
    "ssf" TEXT,
    "sfc" TEXT,
    "other_edu" TEXT,
    "appren" TEXT,
    "all_work" TEXT,
    "all_notsust" TEXT,
    "all_unknown" TEXT
);

DROP TABLE IF EXISTS raw_ks4_dm_ud_202223_l_c3b076dc;
CREATE TABLE raw_ks4_dm_ud_202223_l_c3b076dc (
    "time_period" TEXT,
    "time_identifier" TEXT,
    "geographic_level" TEXT,
    "country_code" TEXT,
    "country_name" TEXT,
    "region_code" TEXT,
    "region_name" TEXT,
    "old_la_code" TEXT,
    "new_la_code" TEXT,
    "la_name" TEXT,
    "pcon_code" TEXT,
    "pcon_name" TEXT,
    "lad_code" TEXT,
    "lad_name" TEXT,
    "level_methodology" TEXT,
    "institution_group" TEXT,
    "institution_type" TEXT,
    "breakdown_topic" TEXT,
    "breakdown" TEXT,
    "version" TEXT,
    "data_type" TEXT,
    "cohort" TEXT,
    "overall" TEXT,
    "education" TEXT,
    "fe" TEXT,
    "ssf" TEXT,
    "sfc" TEXT,
    "other_edu" TEXT,
    "appren" TEXT,
    "appl3" TEXT,
    "appl2" TEXT,
    "all_work" TEXT,
    "all_notsust" TEXT,
    "all_unknown" TEXT
);

DROP TABLE IF EXISTS raw_ks4_dm_ud_202223_n_8dfd44c9;
CREATE TABLE raw_ks4_dm_ud_202223_n_8dfd44c9 (
    "time_period" TEXT,
    "time_identifier" TEXT,
    "geographic_level" TEXT,
    "country_code" TEXT,
    "country_name" TEXT,
    "institution_group" TEXT,
    "institution_type" TEXT,
    "breakdown_topic" TEXT,
    "breakdown" TEXT,
    "data_type" TEXT,
    "version" TEXT,
    "inst_count" TEXT,
    "cohort" TEXT,
    "overall" TEXT,
    "education" TEXT,
    "fe" TEXT,
    "ssf" TEXT,
    "sfc" TEXT,
    "other_edu" TEXT,
    "ind" TEXT,
    "appru" TEXT,
    "special" TEXT,
    "spi" TEXT,
    "edu_combo" TEXT,
    "he" TEXT,
    "appren" TEXT,
    "appl3" TEXT,
    "appl2" TEXT,
    "all_work" TEXT,
    "all_notsust" TEXT,
    "notsust" TEXT,
    "notsust_beneet" TEXT,
    "only_beneet" TEXT,
    "all_unknown" TEXT,
    "unknown_id" TEXT,
    "unknown" TEXT
);

DROP TABLE IF EXISTS raw_workforce_ptrs_201_8b26fc7d;
CREATE TABLE raw_workforce_ptrs_201_8b26fc7d (
    "time_period" TEXT,
    "time_identifier" TEXT,
    "geographic_level" TEXT,
    "country_code" TEXT,
    "country_name" TEXT,
    "region_code" TEXT,
    "region_name" TEXT,
    "old_la_code" TEXT,
    "new_la_code" TEXT,
    "la_name" TEXT,
    "school_laestab" TEXT,
    "school_urn" TEXT,
    "school_name" TEXT,
    "school_type" TEXT,
    "number_schools" TEXT,
    "pupils_fte" TEXT,
    "qualified_teachers_fte" TEXT,
    "teachers_fte" TEXT,
    "adults_fte" TEXT,
    "pupil_to_qual_teacher_ratio" TEXT,
    "pupil_to_qual_unqual_teacher_ratio" TEXT,
    "pupil_to_adult_ratio" TEXT
);

