-- AUTO-GENERATED MATERIALIZED VIEW: v_establishment_performance

DROP MATERIALIZED VIEW IF EXISTS v_establishment_performance;

CREATE MATERIALIZED VIEW v_establishment_performance AS
WITH
src_1 AS (
    SELECT
        t."URN" AS "Id",
        MAX(CASE WHEN TRUE THEN t."ATT8SCR_BOYS" END) AS "Attainment8_Boy_Est_Previous2_Num",
        MAX(CASE WHEN TRUE THEN t."ATT8SCR_FSM6CLA1A" END) AS "Attainment8_Dis_Est_Previous2_Num",
        MAX(CASE WHEN TRUE THEN t."ATT8SCR_EAL" END) AS "Attainment8_EAL_Est_Previous2_Num",
        MAX(CASE WHEN TRUE THEN t."ATT8SCR_GIRLS" END) AS "Attainment8_Grl_Est_Previous2_Num",
        MAX(CASE WHEN TRUE THEN t."ATT8SCR_NFSM6CLA1A" END) AS "Attainment8_NDi_Est_Previous2_Num",
        MAX(CASE WHEN TRUE THEN t."ATT8SCR_NMOB" END) AS "Attainment8_NMo_Est_Previous2_Num",
        MAX(CASE WHEN TRUE THEN t."ATT8SCR" END) AS "Attainment8_Tot_Est_Previous2_Num",
        MAX(CASE WHEN TRUE THEN clean_numeric(t."PBL2BASICS_94") END) AS "EngMaths49_Boy_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN clean_numeric(t."PBL2BASICS_95") END) AS "EngMaths59_Boy_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN clean_numeric(t."PTFSM6CLA1ABASICS_94") END) AS "EngMaths49_Dis_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN clean_numeric(t."PTFSM6CLA1ABASICS_95") END) AS "EngMaths59_Dis_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN clean_numeric(t."PTL2BASICSEAL_94") END) AS "EngMaths49_EAL_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN clean_numeric(t."PTL2BASICSEAL_95") END) AS "EngMaths59_EAL_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN clean_numeric(t."PGL2BASICS_94") END) AS "EngMaths49_Grl_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN clean_numeric(t."PGL2BASICS_95") END) AS "EngMaths59_Grl_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN clean_numeric(t."PTL2BASICSNMOB_94") END) AS "EngMaths49_Mob_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN clean_numeric(t."PTL2BASICSNMOB_95") END) AS "EngMaths59_Mob_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN clean_numeric(t."PTL2BASICS_94") END) AS "EngMaths49_Tot_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN clean_numeric(t."PTL2BASICS_95") END) AS "EngMaths59_Tot_Est_Previous2_Pct",
        MAX(CASE WHEN TRUE THEN t."P8MEA" END) AS "Prog8_Tot_Est_Previous2_Num"
    FROM raw_2022_2023_england__28199246 t
    GROUP BY t."URN"
),
src_2 AS (
    SELECT
        t."school_urn" AS "Id",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN t."avg_att8" END) AS "Attainment8_Boy_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN t."avg_att8" END) AS "Attainment8_Dis_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN t."avg_att8" END) AS "Attainment8_EAL_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN t."avg_att8" END) AS "Attainment8_Grl_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN t."avg_att8" END) AS "Attainment8_NMo_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN t."avg_att8" END) AS "Attainment8_Tot_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN clean_int(t."t_l2basics_94") END) AS "EngMaths49_Boy_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN clean_numeric(t."pt_l2basics_94") END) AS "EngMaths49_Boy_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN clean_int(t."t_l2basics_95") END) AS "EngMaths59_Boy_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN clean_numeric(t."pt_l2basics_95") END) AS "EngMaths59_Boy_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN clean_int(t."t_l2basics_94") END) AS "EngMaths49_Dis_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN clean_numeric(t."pt_l2basics_94") END) AS "EngMaths49_Dis_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN clean_int(t."t_l2basics_95") END) AS "EngMaths59_Dis_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN clean_numeric(t."pt_l2basics_95") END) AS "EngMaths59_Dis_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN clean_int(t."t_l2basics_94") END) AS "EngMaths49_EAL_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN clean_numeric(t."pt_l2basics_94") END) AS "EngMaths49_EAL_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN clean_int(t."t_l2basics_95") END) AS "EngMaths59_EAL_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN clean_numeric(t."pt_l2basics_95") END) AS "EngMaths59_EAL_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN clean_int(t."t_l2basics_94") END) AS "EngMaths49_Grl_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN clean_numeric(t."pt_l2basics_94") END) AS "EngMaths49_Grl_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN clean_int(t."t_l2basics_95") END) AS "EngMaths59_Grl_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN clean_numeric(t."pt_l2basics_95") END) AS "EngMaths59_Grl_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN clean_int(t."t_l2basics_94") END) AS "EngMaths49_NMo_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN clean_numeric(t."pt_l2basics_94") END) AS "EngMaths49_NMo_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN clean_int(t."t_l2basics_95") END) AS "EngMaths59_NMo_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN clean_numeric(t."pt_l2basics_95") END) AS "EngMaths59_NMo_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN clean_int(t."t_l2basics_94") END) AS "EngMaths49_Tot_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN clean_numeric(t."pt_l2basics_94") END) AS "EngMaths49_Tot_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN clean_int(t."t_l2basics_95") END) AS "EngMaths59_Tot_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN clean_numeric(t."pt_l2basics_95") END) AS "EngMaths59_Tot_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN t."t_p8score" END) AS "Prog8_Tot_Est_Previous_Num"
    FROM raw_202324_performance_371eb4e5 t
    GROUP BY t."school_urn"
),
src_3 AS (
    SELECT
        t."Unique Reference Number (URN)" AS "Id",
        MAX(CASE WHEN t."Discount Code" = 'RH3' AND t."GRADE" = '4+5+6+7+8+9' THEN t."Number of entries at grade" END) AS "Bio49__Est_Previous2_Num",
        MAX(CASE WHEN t."Discount Code" = 'RD1' AND t."GRADE" = '4+5+6+7+8+9' THEN t."Number of entries at grade" END) AS "Chem49__Est_Previous2_Num",
        MAX(CASE WHEN t."Discount Code" = 'RD1' AND t."GRADE" = '5+6+7+8+9' THEN t."Number of entries at grade" END) AS "Chem59__Est_Previous2_Num",
        MAX(CASE WHEN t."Discount Code" = 'RA1E' AND t."GRADE" = '4+5+6+7+8+9' THEN t."Number of entries at grade" END) AS "CombSci49__Est_Previous2_Num",
        MAX(CASE WHEN t."Discount Code" = 'RA1E' AND t."GRADE" = '5+6+7+8+9' THEN t."Number of entries at grade" END) AS "CombSci59__Est_Previous2_Num",
        MAX(CASE WHEN t."Discount Code" = 'RA1E' AND t."GRADE" = '7+8+9' THEN t."Number of entries at grade" END) AS "CombSci79__Est_Previous2_Num",
        MAX(CASE WHEN t."Discount Code" = 'FK2B' AND t."GRADE" = '4+5+6+7+8+9' THEN t."Number of entries at grade" END) AS "EngLang49__Est_Previous2_Num",
        MAX(CASE WHEN t."Discount Code" = 'FK2B' AND t."GRADE" = '5+6+7+8+9' THEN t."Number of entries at grade" END) AS "EngLang59__Est_Previous2_Num",
        MAX(CASE WHEN t."Discount Code" = 'FK2B' AND t."GRADE" = '7+8+9' THEN t."Number of entries at grade" END) AS "EngLang79__Est_Previous2_Num",
        MAX(CASE WHEN t."Discount Code" = 'FC4' AND t."GRADE" = '4+5+6+7+8+9' THEN t."Number of entries at grade" END) AS "EngLit49__Est_Previous2_Num",
        MAX(CASE WHEN t."Discount Code" = 'FC4' AND t."GRADE" = '5+6+7+8+9' THEN t."Number of entries at grade" END) AS "EngLit59__Est_Previous2_Num",
        MAX(CASE WHEN t."Discount Code" = 'FC4' AND t."GRADE" = '7+8+9' THEN t."Number of entries at grade" END) AS "EngLit79__Est_Previous2_Num",
        MAX(CASE WHEN t."Discount Code" = 'RB1' AND t."GRADE" = '4+5+6+7+8+9' THEN t."Number of entries at grade" END) AS "Maths49__Est_Previous2_Num",
        MAX(CASE WHEN t."Discount Code" = 'RB1' AND t."GRADE" = '5+6+7+8+9' THEN t."Number of entries at grade" END) AS "Maths59__Est_Previous2_Num",
        MAX(CASE WHEN t."Discount Code" = 'RB1' AND t."GRADE" = '7+8+9' THEN t."Number of entries at grade" END) AS "Maths79__Est_Previous2_Num",
        MAX(CASE WHEN t."Discount Code" = 'RC1' AND t."GRADE" = '4+5+6+7+8+9' THEN t."Number of entries at grade" END) AS "Physics49__Est_Previous2_Num",
        MAX(CASE WHEN t."Discount Code" = 'RC1' AND t."GRADE" = '5+6+7+8+9' THEN t."Number of entries at grade" END) AS "Physics59__Est_Previous2_Num",
        MAX(CASE WHEN t."Discount Code" = 'RC1' AND t."GRADE" = '7+8+9' THEN t."Number of entries at grade" END) AS "Physics79__Est_Previous2_Num"
    FROM raw_england_ks4underly_effb560d t
    GROUP BY t."Unique Reference Number (URN)"
),
src_4 AS (
    SELECT
        t."school_urn" AS "Id",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving" END) AS "Bio49__Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving" END) AS "Chem49__Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving" END) AS "Chem59__Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RAE1' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving" END) AS "CombSci49__Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RAE1' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving" END) AS "CombSci59__Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RAE1' AND t."grade" = '7+8+9' THEN t."number_achieving" END) AS "CombSci79__Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving" END) AS "EngLang49__Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving" END) AS "EngLang59__Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '7+8+9' THEN t."number_achieving" END) AS "EngLang79__Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving" END) AS "EngLit49__Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving" END) AS "EngLit59__Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '7+8+9' THEN t."number_achieving" END) AS "EngLit79__Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving" END) AS "Maths49__Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving" END) AS "Maths59__Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '7+8+9' THEN t."number_achieving" END) AS "Maths79__Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving" END) AS "Physics49__Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving" END) AS "Physics59__Est_Previous_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '7+8+9' THEN t."number_achieving" END) AS "Physics79__Est_Previous_Num"
    FROM raw_202324_subject_sch_84751f47 t
    GROUP BY t."school_urn"
),
src_5 AS (
    SELECT
        t."school_urn" AS "Id",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN clean_int(t."attainment8_average") END) AS "Attainment8_Boy_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN clean_numeric(t."engmath_94_total") END) AS "EngMaths49_Boy_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN clean_numeric(t."engmath_94_percent") END) AS "EngMaths49_Boy_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN clean_int(t."engmath_95_total") END) AS "EngMaths59_Boy_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Boys' THEN clean_numeric(t."engmath_95_percent") END) AS "EngMaths59_Boy_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN clean_numeric(t."engmath_94_total") END) AS "EngMaths49_Dis_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN clean_int(t."engmath_95_total") END) AS "EngMaths59_Dis_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN clean_numeric(t."engmath_95_percent") END) AS "EngMaths59_Dis_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN clean_numeric(t."engmath_94_total") END) AS "EngMaths49_EAL_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN clean_int(t."engmath_95_total") END) AS "EngMaths59_EAL_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN clean_numeric(t."engmath_95_percent") END) AS "EngMaths59_EAL_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' THEN clean_int(t."attainment8_average") END) AS "Attainment8_Dis_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN clean_numeric(t."engmath_94_total") END) AS "EngMaths49_Grl_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN clean_int(t."engmath_95_total") END) AS "EngMaths59_Grl_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN clean_numeric(t."engmath_95_percent") END) AS "EngMaths59_Grl_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Not known to be disadvantaged' THEN clean_int(t."engmath_94_total") END) AS "EngMaths49_NDi_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Not known to be disadvantaged' THEN clean_numeric(t."engmath_94_percent") END) AS "EngMaths49_NDi_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Not known to be disadvantaged' THEN clean_numeric(t."engmath_95_total") END) AS "EngMaths59_NDi_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN clean_numeric(t."engmath_94_total") END) AS "EngMaths49_NMo_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN clean_int(t."engmath_95_total") END) AS "EngMaths59_NMo_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN clean_numeric(t."engmath_95_percent") END) AS "EngMaths59_NMo_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Other than English' THEN clean_int(t."attainment8_average") END) AS "Attainment8_EAL_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN clean_int(t."engmath_94_total") END) AS "EngMaths49_Tot_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN clean_numeric(t."engmath_94_percent") END) AS "EngMaths49_Tot_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN clean_int(t."engmath_95_total") END) AS "EngMaths59_Tot_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN clean_numeric(t."engmath_95_percent") END) AS "EngMaths59_Tot_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Girls' THEN clean_int(t."attainment8_average") END) AS "Attainment8_Grl_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Not known to be disadvantaged' THEN clean_int(t."attainment8_average") END) AS "Attainment8_NDi_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Non mobile' THEN clean_int(t."attainment8_average") END) AS "Attainment8_NMo_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' THEN clean_int(t."attainment8_average") END) AS "Attainment8_Tot_Est_Current_Num"
    FROM raw_202425_performance_3979aec1 t
    GROUP BY t."school_urn"
),
src_6 AS (
    SELECT
        t."school_urn" AS "Id",
        MAX(CASE WHEN t."discount_code" = 'RH3' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving" END) AS "Bio49__Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving" END) AS "Chem49__Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RD1' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving" END) AS "Chem59__Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'CK1' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving" END) AS "CombSci49__Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'CK1' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving" END) AS "CombSci59__Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'CK1' AND t."grade" = '7+8+9' THEN t."number_achieving" END) AS "CombSci79__Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving" END) AS "EngLang49__Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving" END) AS "EngLang59__Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'FK2B' AND t."grade" = '7+8+9' THEN t."number_achieving" END) AS "EngLang79__Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving" END) AS "EngLit49__Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving" END) AS "EngLit59__Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'FC4' AND t."grade" = '7+8+9' THEN t."number_achieving" END) AS "EngLit79__Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving" END) AS "Maths49__Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving" END) AS "Maths59__Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RB1' AND t."grade" = '7+8+9' THEN t."number_achieving" END) AS "Maths79__Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '4+5+6+7+8+9' THEN t."number_achieving" END) AS "Physics49__Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '5+6+7+8+9' THEN t."number_achieving" END) AS "Physics59__Est_Current_Num",
        MAX(CASE WHEN t."discount_code" = 'RC1' AND t."grade" = '7+8+9' THEN t."number_achieving" END) AS "Physics79__Est_Current_Num"
    FROM raw_202425_subject_sch_a9a9beac t
    GROUP BY t."school_urn"
)

SELECT
    COALESCE(src_1."Id", src_2."Id", src_3."Id", src_4."Id", src_5."Id", src_6."Id") AS "Id",
    src_5."Attainment8_Boy_Est_Current_Num" AS "Attainment8_Boy_Est_Current_Num",
    src_2."Attainment8_Boy_Est_Previous_Num" AS "Attainment8_Boy_Est_Previous_Num",
    src_1."Attainment8_Boy_Est_Previous2_Num" AS "Attainment8_Boy_Est_Previous2_Num",
    src_5."Attainment8_Dis_Est_Current_Num" AS "Attainment8_Dis_Est_Current_Num",
    src_2."Attainment8_Dis_Est_Previous_Num" AS "Attainment8_Dis_Est_Previous_Num",
    src_1."Attainment8_Dis_Est_Previous2_Num" AS "Attainment8_Dis_Est_Previous2_Num",
    src_5."Attainment8_EAL_Est_Current_Num" AS "Attainment8_EAL_Est_Current_Num",
    src_2."Attainment8_EAL_Est_Previous_Num" AS "Attainment8_EAL_Est_Previous_Num",
    src_1."Attainment8_EAL_Est_Previous2_Num" AS "Attainment8_EAL_Est_Previous2_Num",
    src_5."Attainment8_Grl_Est_Current_Num" AS "Attainment8_Grl_Est_Current_Num",
    src_2."Attainment8_Grl_Est_Previous_Num" AS "Attainment8_Grl_Est_Previous_Num",
    src_1."Attainment8_Grl_Est_Previous2_Num" AS "Attainment8_Grl_Est_Previous2_Num",
    src_5."Attainment8_NDi_Est_Current_Num" AS "Attainment8_NDi_Est_Current_Num",
    src_1."Attainment8_NDi_Est_Previous2_Num" AS "Attainment8_NDi_Est_Previous2_Num",
    src_5."Attainment8_NMo_Est_Current_Num" AS "Attainment8_NMo_Est_Current_Num",
    src_2."Attainment8_NMo_Est_Previous_Num" AS "Attainment8_NMo_Est_Previous_Num",
    src_1."Attainment8_NMo_Est_Previous2_Num" AS "Attainment8_NMo_Est_Previous2_Num",
    src_5."Attainment8_Tot_Est_Current_Num" AS "Attainment8_Tot_Est_Current_Num",
    src_2."Attainment8_Tot_Est_Previous_Num" AS "Attainment8_Tot_Est_Previous_Num",
    src_1."Attainment8_Tot_Est_Previous2_Num" AS "Attainment8_Tot_Est_Previous2_Num",
    src_6."Bio49__Est_Current_Num" AS "Bio49__Est_Current_Num",
    src_4."Bio49__Est_Previous_Num" AS "Bio49__Est_Previous_Num",
    src_3."Bio49__Est_Previous2_Num" AS "Bio49__Est_Previous2_Num",
    src_6."Chem49__Est_Current_Num" AS "Chem49__Est_Current_Num",
    src_4."Chem49__Est_Previous_Num" AS "Chem49__Est_Previous_Num",
    src_3."Chem49__Est_Previous2_Num" AS "Chem49__Est_Previous2_Num",
    src_6."Chem59__Est_Current_Num" AS "Chem59__Est_Current_Num",
    src_4."Chem59__Est_Previous_Num" AS "Chem59__Est_Previous_Num",
    src_3."Chem59__Est_Previous2_Num" AS "Chem59__Est_Previous2_Num",
    src_6."CombSci49__Est_Current_Num" AS "CombSci49__Est_Current_Num",
    src_4."CombSci49__Est_Previous_Num" AS "CombSci49__Est_Previous_Num",
    src_3."CombSci49__Est_Previous2_Num" AS "CombSci49__Est_Previous2_Num",
    src_6."CombSci59__Est_Current_Num" AS "CombSci59__Est_Current_Num",
    src_4."CombSci59__Est_Previous_Num" AS "CombSci59__Est_Previous_Num",
    src_3."CombSci59__Est_Previous2_Num" AS "CombSci59__Est_Previous2_Num",
    src_6."CombSci79__Est_Current_Num" AS "CombSci79__Est_Current_Num",
    src_4."CombSci79__Est_Previous_Num" AS "CombSci79__Est_Previous_Num",
    src_3."CombSci79__Est_Previous2_Num" AS "CombSci79__Est_Previous2_Num",
    src_6."EngLang49__Est_Current_Num" AS "EngLang49__Est_Current_Num",
    src_4."EngLang49__Est_Previous_Num" AS "EngLang49__Est_Previous_Num",
    src_3."EngLang49__Est_Previous2_Num" AS "EngLang49__Est_Previous2_Num",
    src_6."EngLang59__Est_Current_Num" AS "EngLang59__Est_Current_Num",
    src_4."EngLang59__Est_Previous_Num" AS "EngLang59__Est_Previous_Num",
    src_3."EngLang59__Est_Previous2_Num" AS "EngLang59__Est_Previous2_Num",
    src_6."EngLang79__Est_Current_Num" AS "EngLang79__Est_Current_Num",
    src_4."EngLang79__Est_Previous_Num" AS "EngLang79__Est_Previous_Num",
    src_3."EngLang79__Est_Previous2_Num" AS "EngLang79__Est_Previous2_Num",
    src_6."EngLit49__Est_Current_Num" AS "EngLit49__Est_Current_Num",
    src_4."EngLit49__Est_Previous_Num" AS "EngLit49__Est_Previous_Num",
    src_3."EngLit49__Est_Previous2_Num" AS "EngLit49__Est_Previous2_Num",
    src_6."EngLit59__Est_Current_Num" AS "EngLit59__Est_Current_Num",
    src_4."EngLit59__Est_Previous_Num" AS "EngLit59__Est_Previous_Num",
    src_3."EngLit59__Est_Previous2_Num" AS "EngLit59__Est_Previous2_Num",
    src_6."EngLit79__Est_Current_Num" AS "EngLit79__Est_Current_Num",
    src_4."EngLit79__Est_Previous_Num" AS "EngLit79__Est_Previous_Num",
    src_3."EngLit79__Est_Previous2_Num" AS "EngLit79__Est_Previous2_Num",
    src_5."EngMaths49_Boy_Est_Current_Num" AS "EngMaths49_Boy_Est_Current_Num",
    src_5."EngMaths49_Boy_Est_Current_Pct" AS "EngMaths49_Boy_Est_Current_Pct",
    src_2."EngMaths49_Boy_Est_Previous_Num" AS "EngMaths49_Boy_Est_Previous_Num",
    src_2."EngMaths49_Boy_Est_Previous_Pct" AS "EngMaths49_Boy_Est_Previous_Pct",
    src_1."EngMaths49_Boy_Est_Previous2_Pct" AS "EngMaths49_Boy_Est_Previous2_Pct",
    src_5."EngMaths49_Dis_Est_Current_Pct" AS "EngMaths49_Dis_Est_Current_Pct",
    src_2."EngMaths49_Dis_Est_Previous_Num" AS "EngMaths49_Dis_Est_Previous_Num",
    src_2."EngMaths49_Dis_Est_Previous_Pct" AS "EngMaths49_Dis_Est_Previous_Pct",
    src_1."EngMaths49_Dis_Est_Previous2_Pct" AS "EngMaths49_Dis_Est_Previous2_Pct",
    src_5."EngMaths49_EAL_Est_Current_Pct" AS "EngMaths49_EAL_Est_Current_Pct",
    src_2."EngMaths49_EAL_Est_Previous_Num" AS "EngMaths49_EAL_Est_Previous_Num",
    src_2."EngMaths49_EAL_Est_Previous_Pct" AS "EngMaths49_EAL_Est_Previous_Pct",
    src_1."EngMaths49_EAL_Est_Previous2_Pct" AS "EngMaths49_EAL_Est_Previous2_Pct",
    src_5."EngMaths49_Grl_Est_Current_Pct" AS "EngMaths49_Grl_Est_Current_Pct",
    src_2."EngMaths49_Grl_Est_Previous_Num" AS "EngMaths49_Grl_Est_Previous_Num",
    src_2."EngMaths49_Grl_Est_Previous_Pct" AS "EngMaths49_Grl_Est_Previous_Pct",
    src_1."EngMaths49_Grl_Est_Previous2_Pct" AS "EngMaths49_Grl_Est_Previous2_Pct",
    src_1."EngMaths49_Mob_Est_Previous2_Pct" AS "EngMaths49_Mob_Est_Previous2_Pct",
    src_5."EngMaths49_NDi_Est_Current_Num" AS "EngMaths49_NDi_Est_Current_Num",
    src_5."EngMaths49_NDi_Est_Current_Pct" AS "EngMaths49_NDi_Est_Current_Pct",
    src_5."EngMaths49_NMo_Est_Current_Pct" AS "EngMaths49_NMo_Est_Current_Pct",
    src_2."EngMaths49_NMo_Est_Previous_Num" AS "EngMaths49_NMo_Est_Previous_Num",
    src_2."EngMaths49_NMo_Est_Previous_Pct" AS "EngMaths49_NMo_Est_Previous_Pct",
    src_5."EngMaths49_Tot_Est_Current_Num" AS "EngMaths49_Tot_Est_Current_Num",
    src_5."EngMaths49_Tot_Est_Current_Pct" AS "EngMaths49_Tot_Est_Current_Pct",
    src_2."EngMaths49_Tot_Est_Previous_Num" AS "EngMaths49_Tot_Est_Previous_Num",
    src_2."EngMaths49_Tot_Est_Previous_Pct" AS "EngMaths49_Tot_Est_Previous_Pct",
    src_1."EngMaths49_Tot_Est_Previous2_Pct" AS "EngMaths49_Tot_Est_Previous2_Pct",
    src_5."EngMaths59_Boy_Est_Current_Num" AS "EngMaths59_Boy_Est_Current_Num",
    src_5."EngMaths59_Boy_Est_Current_Pct" AS "EngMaths59_Boy_Est_Current_Pct",
    src_2."EngMaths59_Boy_Est_Previous_Num" AS "EngMaths59_Boy_Est_Previous_Num",
    src_2."EngMaths59_Boy_Est_Previous_Pct" AS "EngMaths59_Boy_Est_Previous_Pct",
    src_1."EngMaths59_Boy_Est_Previous2_Pct" AS "EngMaths59_Boy_Est_Previous2_Pct",
    src_5."EngMaths59_Dis_Est_Current_Num" AS "EngMaths59_Dis_Est_Current_Num",
    src_5."EngMaths59_Dis_Est_Current_Pct" AS "EngMaths59_Dis_Est_Current_Pct",
    src_2."EngMaths59_Dis_Est_Previous_Num" AS "EngMaths59_Dis_Est_Previous_Num",
    src_2."EngMaths59_Dis_Est_Previous_Pct" AS "EngMaths59_Dis_Est_Previous_Pct",
    src_1."EngMaths59_Dis_Est_Previous2_Pct" AS "EngMaths59_Dis_Est_Previous2_Pct",
    src_5."EngMaths59_EAL_Est_Current_Num" AS "EngMaths59_EAL_Est_Current_Num",
    src_5."EngMaths59_EAL_Est_Current_Pct" AS "EngMaths59_EAL_Est_Current_Pct",
    src_2."EngMaths59_EAL_Est_Previous_Num" AS "EngMaths59_EAL_Est_Previous_Num",
    src_2."EngMaths59_EAL_Est_Previous_Pct" AS "EngMaths59_EAL_Est_Previous_Pct",
    src_1."EngMaths59_EAL_Est_Previous2_Pct" AS "EngMaths59_EAL_Est_Previous2_Pct",
    src_5."EngMaths59_Grl_Est_Current_Num" AS "EngMaths59_Grl_Est_Current_Num",
    src_5."EngMaths59_Grl_Est_Current_Pct" AS "EngMaths59_Grl_Est_Current_Pct",
    src_2."EngMaths59_Grl_Est_Previous_Num" AS "EngMaths59_Grl_Est_Previous_Num",
    src_2."EngMaths59_Grl_Est_Previous_Pct" AS "EngMaths59_Grl_Est_Previous_Pct",
    src_1."EngMaths59_Grl_Est_Previous2_Pct" AS "EngMaths59_Grl_Est_Previous2_Pct",
    src_1."EngMaths59_Mob_Est_Previous2_Pct" AS "EngMaths59_Mob_Est_Previous2_Pct",
    src_5."EngMaths59_NDi_Est_Current_Pct" AS "EngMaths59_NDi_Est_Current_Pct",
    src_5."EngMaths59_NMo_Est_Current_Num" AS "EngMaths59_NMo_Est_Current_Num",
    src_5."EngMaths59_NMo_Est_Current_Pct" AS "EngMaths59_NMo_Est_Current_Pct",
    src_2."EngMaths59_NMo_Est_Previous_Num" AS "EngMaths59_NMo_Est_Previous_Num",
    src_2."EngMaths59_NMo_Est_Previous_Pct" AS "EngMaths59_NMo_Est_Previous_Pct",
    src_5."EngMaths59_Tot_Est_Current_Num" AS "EngMaths59_Tot_Est_Current_Num",
    src_5."EngMaths59_Tot_Est_Current_Pct" AS "EngMaths59_Tot_Est_Current_Pct",
    src_2."EngMaths59_Tot_Est_Previous_Num" AS "EngMaths59_Tot_Est_Previous_Num",
    src_2."EngMaths59_Tot_Est_Previous_Pct" AS "EngMaths59_Tot_Est_Previous_Pct",
    src_1."EngMaths59_Tot_Est_Previous2_Pct" AS "EngMaths59_Tot_Est_Previous2_Pct",
    src_6."Maths49__Est_Current_Num" AS "Maths49__Est_Current_Num",
    src_4."Maths49__Est_Previous_Num" AS "Maths49__Est_Previous_Num",
    src_3."Maths49__Est_Previous2_Num" AS "Maths49__Est_Previous2_Num",
    src_6."Maths59__Est_Current_Num" AS "Maths59__Est_Current_Num",
    src_4."Maths59__Est_Previous_Num" AS "Maths59__Est_Previous_Num",
    src_3."Maths59__Est_Previous2_Num" AS "Maths59__Est_Previous2_Num",
    src_6."Maths79__Est_Current_Num" AS "Maths79__Est_Current_Num",
    src_4."Maths79__Est_Previous_Num" AS "Maths79__Est_Previous_Num",
    src_3."Maths79__Est_Previous2_Num" AS "Maths79__Est_Previous2_Num",
    src_6."Physics49__Est_Current_Num" AS "Physics49__Est_Current_Num",
    src_4."Physics49__Est_Previous_Num" AS "Physics49__Est_Previous_Num",
    src_3."Physics49__Est_Previous2_Num" AS "Physics49__Est_Previous2_Num",
    src_6."Physics59__Est_Current_Num" AS "Physics59__Est_Current_Num",
    src_4."Physics59__Est_Previous_Num" AS "Physics59__Est_Previous_Num",
    src_3."Physics59__Est_Previous2_Num" AS "Physics59__Est_Previous2_Num",
    src_6."Physics79__Est_Current_Num" AS "Physics79__Est_Current_Num",
    src_4."Physics79__Est_Previous_Num" AS "Physics79__Est_Previous_Num",
    src_3."Physics79__Est_Previous2_Num" AS "Physics79__Est_Previous2_Num",
    src_2."Prog8_Tot_Est_Previous_Num" AS "Prog8_Tot_Est_Previous_Num",
    src_1."Prog8_Tot_Est_Previous2_Num" AS "Prog8_Tot_Est_Previous2_Num"
FROM src_1
LEFT JOIN src_2 ON src_2."Id" = src_1."Id"
LEFT JOIN src_3 ON src_3."Id" = src_1."Id"
LEFT JOIN src_4 ON src_4."Id" = src_1."Id"
LEFT JOIN src_5 ON src_5."Id" = src_1."Id"
LEFT JOIN src_6 ON src_6."Id" = src_1."Id"
;
