-- AUTO-GENERATED MATERIALIZED VIEW: v_establishment_destinations

DROP MATERIALIZED VIEW IF EXISTS v_establishment_destinations;

CREATE MATERIALIZED VIEW v_establishment_destinations AS
WITH
src_1 AS (
    SELECT
        t."school_laestab" AS "Id",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of pupils' THEN clean_int(t."overall") END) AS "AllDest_Boy_Est_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' THEN clean_numeric(t."overall") END) AS "AllDest_Boy_Est_Previous2_Pct",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of pupils' THEN clean_int(t."appren") END) AS "Apprentice_Boy_Est_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' THEN clean_numeric(t."appren") END) AS "Apprentice_Boy_Est_Previous2_Pct",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of pupils' THEN clean_int(t."all_work") END) AS "Employment_Boy_Est_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' THEN clean_numeric(t."all_work") END) AS "Employment_Boy_Est_Previous2_Pct",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of pupils' THEN clean_int(t."education") END) AS "Education_Boy_Est_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' THEN clean_numeric(t."education") END) AS "Education_Boy_Est_Previous2_Pct",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of pupils' THEN clean_int(t."overall") END) AS "AllDest_Dis_Est_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' THEN clean_numeric(t."overall") END) AS "AllDest_Dis_Est_Previous2_Pct",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of pupils' THEN clean_int(t."education") END) AS "Education_Dis_Est_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' THEN clean_numeric(t."education") END) AS "Education_Dis_Est_Previous2_Pct",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of pupils' THEN clean_int(t."all_work") END) AS "Employment_Dis_Est_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' THEN clean_numeric(t."all_work") END) AS "Employment_Dis_Est_Previous2_Pct",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of pupils' THEN clean_int(t."overall") END) AS "AllDest_Grl_Est_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' THEN clean_numeric(t."overall") END) AS "AllDest_Grl_Est_Previous2_Pct",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of pupils' THEN clean_int(t."education") END) AS "Education_Grl_Est_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' THEN clean_numeric(t."education") END) AS "Education_Grl_Est_Previous2_Pct",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of pupils' THEN clean_int(t."all_work") END) AS "Employment_Grl_Est_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' THEN clean_numeric(t."all_work") END) AS "Employment_Grl_Est_Previous2_Pct",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of pupils' THEN clean_int(t."overall") END) AS "AllDest_NDi_Est_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' THEN clean_numeric(t."overall") END) AS "AllDest_NDi_Est_Previous2_Pct",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of pupils' THEN clean_int(t."education") END) AS "Education_NDi_Est_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' THEN clean_numeric(t."education") END) AS "Education_NDi_Est_Previous2_Pct",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of pupils' THEN clean_int(t."all_work") END) AS "Employment_NDi_Est_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' THEN clean_numeric(t."all_work") END) AS "Employment_NDi_Est_Previous2_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of pupils' THEN clean_int(t."overall") END) AS "AllDest_Tot_Est_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' THEN clean_numeric(t."overall") END) AS "AllDest_Tot_Est_Previous2_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of pupils' THEN clean_int(t."education") END) AS "Education_Tot_Est_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' THEN clean_numeric(t."education") END) AS "Education_Tot_Est_Previous2_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of pupils' THEN clean_int(t."all_work") END) AS "Employment_Tot_Est_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' THEN clean_numeric(t."all_work") END) AS "Employment_Tot_Est_Previous2_Pct",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of pupils' THEN clean_int(t."appren") END) AS "Apprentice_Dis_Est_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' THEN clean_numeric(t."appren") END) AS "Apprentice_Dis_Est_Previous2_Pct",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of pupils' THEN clean_int(t."appren") END) AS "Apprentice_Grl_Est_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' THEN clean_numeric(t."appren") END) AS "Apprentice_Grl_Est_Previous2_Pct",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of pupils' THEN clean_int(t."appren") END) AS "Apprentice_NDi_Est_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' THEN clean_numeric(t."appren") END) AS "Apprentice_NDi_Est_Previous2_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of pupils' THEN clean_int(t."appren") END) AS "Apprentice_Tot_Est_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' THEN clean_numeric(t."appren") END) AS "Apprentice_Tot_Est_Previous2_Pct"
    FROM raw_ks4_dm_ud_202122_i_d3152640 t
    GROUP BY t."school_laestab"
),
src_2 AS (
    SELECT
        t."school_urn" AS "Id",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of pupils' THEN clean_int(t."overall") END) AS "AllDest_Boy_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' THEN clean_numeric(t."overall") END) AS "AllDest_Boy_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of pupils' THEN clean_int(t."appren") END) AS "Apprentice_Boy_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' THEN clean_numeric(t."appren") END) AS "Apprentice_Boy_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of pupils' THEN clean_int(t."all_work") END) AS "Employment_Boy_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' THEN clean_numeric(t."all_work") END) AS "Employment_Boy_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of pupils' THEN clean_int(t."education") END) AS "Education_Boy_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' THEN clean_numeric(t."education") END) AS "Education_Boy_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of pupils' THEN clean_int(t."overall") END) AS "AllDest_Dis_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' THEN clean_numeric(t."overall") END) AS "AllDest_Dis_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of pupils' THEN clean_int(t."education") END) AS "Education_Dis_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' THEN clean_numeric(t."education") END) AS "Education_Dis_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of pupils' THEN clean_int(t."all_work") END) AS "Employment_Dis_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' THEN clean_numeric(t."all_work") END) AS "Employment_Dis_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of pupils' THEN clean_int(t."overall") END) AS "AllDest_Grl_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' THEN clean_numeric(t."overall") END) AS "AllDest_Grl_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of pupils' THEN clean_int(t."education") END) AS "Education_Grl_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' THEN clean_numeric(t."education") END) AS "Education_Grl_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of pupils' THEN clean_int(t."all_work") END) AS "Employment_Grl_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' THEN clean_numeric(t."all_work") END) AS "Employment_Grl_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of pupils' THEN clean_int(t."overall") END) AS "AllDest_NDi_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' THEN clean_numeric(t."overall") END) AS "AllDest_NDi_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of pupils' THEN clean_int(t."education") END) AS "Education_NDi_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' THEN clean_numeric(t."education") END) AS "Education_NDi_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of pupils' THEN clean_int(t."all_work") END) AS "Employment_NDi_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' THEN clean_numeric(t."all_work") END) AS "Employment_NDi_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of pupils' THEN clean_int(t."overall") END) AS "AllDest_Tot_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' THEN clean_numeric(t."overall") END) AS "AllDest_Tot_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of pupils' THEN clean_int(t."education") END) AS "Education_Tot_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' THEN clean_numeric(t."education") END) AS "Education_Tot_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of pupils' THEN clean_int(t."all_work") END) AS "Employment_Tot_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' THEN clean_numeric(t."all_work") END) AS "Employment_Tot_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of pupils' THEN clean_int(t."appren") END) AS "Apprentice_Dis_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' THEN clean_numeric(t."appren") END) AS "Apprentice_Dis_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of pupils' THEN clean_int(t."appren") END) AS "Apprentice_Grl_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' THEN clean_numeric(t."appren") END) AS "Apprentice_Grl_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of pupils' THEN clean_int(t."appren") END) AS "Apprentice_NDi_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' THEN clean_numeric(t."appren") END) AS "Apprentice_NDi_Est_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of pupils' THEN clean_int(t."appren") END) AS "Apprentice_Tot_Est_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' THEN clean_numeric(t."appren") END) AS "Apprentice_Tot_Est_Previous_Pct"
    FROM raw_ks4_dm_ud_202223_i_49ea482a t
    GROUP BY t."school_urn"
),
src_3 AS (
    SELECT
        t."school_urn" AS "Id",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of Students' THEN clean_int(t."overall") END) AS "AllDest_Boy_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' THEN clean_numeric(t."overall") END) AS "AllDest_Boy_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of Students' THEN clean_int(t."appren") END) AS "Apprentice_Boy_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' THEN clean_numeric(t."appren") END) AS "Apprentice_Boy_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of Students' THEN clean_int(t."all_work") END) AS "Employment_Boy_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' THEN clean_numeric(t."all_work") END) AS "Employment_Boy_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Number of Students' THEN clean_int(t."education") END) AS "Education_Boy_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Male' AND t."data_type" = 'Percentage' THEN clean_numeric(t."education") END) AS "Education_Boy_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of Students' THEN clean_int(t."overall") END) AS "AllDest_Dis_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' THEN clean_numeric(t."overall") END) AS "AllDest_Dis_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of Students' THEN clean_int(t."education") END) AS "Education_Dis_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' THEN clean_numeric(t."education") END) AS "Education_Dis_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of Students' THEN clean_int(t."all_work") END) AS "Employment_Dis_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' THEN clean_numeric(t."all_work") END) AS "Employment_Dis_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of Students' THEN clean_int(t."overall") END) AS "AllDest_Grl_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' THEN clean_numeric(t."overall") END) AS "AllDest_Grl_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of Students' THEN clean_int(t."education") END) AS "Education_Grl_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' THEN clean_numeric(t."education") END) AS "Education_Grl_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of Students' THEN clean_int(t."all_work") END) AS "Employment_Grl_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' THEN clean_numeric(t."all_work") END) AS "Employment_Grl_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of Students' THEN clean_int(t."overall") END) AS "AllDest_NDi_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' THEN clean_numeric(t."overall") END) AS "AllDest_NDi_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of Students' THEN clean_int(t."education") END) AS "Education_NDi_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' THEN clean_numeric(t."education") END) AS "Education_NDi_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of Students' THEN clean_int(t."all_work") END) AS "Employment_NDi_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' THEN clean_numeric(t."all_work") END) AS "Employment_NDi_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of Students' THEN clean_int(t."overall") END) AS "AllDest_Tot_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' THEN clean_numeric(t."overall") END) AS "AllDest_Tot_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of Students' THEN clean_int(t."education") END) AS "Education_Tot_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' THEN clean_numeric(t."education") END) AS "Education_Tot_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of Students' THEN clean_int(t."all_work") END) AS "Employment_Tot_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' THEN clean_numeric(t."all_work") END) AS "Employment_Tot_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Number of Students' THEN clean_int(t."appren") END) AS "Apprentice_Dis_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantaged' AND t."data_type" = 'Percentage' THEN clean_numeric(t."appren") END) AS "Apprentice_Dis_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Number of Students' THEN clean_int(t."appren") END) AS "Apprentice_Grl_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Female' AND t."data_type" = 'Percentage' THEN clean_numeric(t."appren") END) AS "Apprentice_Grl_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Number of Students' THEN clean_int(t."appren") END) AS "Apprentice_NDi_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Not disadvantaged' AND t."data_type" = 'Percentage' THEN clean_numeric(t."appren") END) AS "Apprentice_NDi_Est_Current_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Number of Students' THEN clean_int(t."appren") END) AS "Apprentice_Tot_Est_Current_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."data_type" = 'Percentage' THEN clean_numeric(t."appren") END) AS "Apprentice_Tot_Est_Current_Pct"
    FROM raw_ees_ks4_inst_20222_cbe11c27 t
    GROUP BY t."school_urn"
)

SELECT
    COALESCE(src_1."Id", src_2."Id", src_3."Id") AS "Id",
    src_3."AllDest_Boy_Est_Current_Num" AS "AllDest_Boy_Est_Current_Num",
    src_3."AllDest_Boy_Est_Current_Pct" AS "AllDest_Boy_Est_Current_Pct",
    src_2."AllDest_Boy_Est_Previous_Num" AS "AllDest_Boy_Est_Previous_Num",
    src_2."AllDest_Boy_Est_Previous_Pct" AS "AllDest_Boy_Est_Previous_Pct",
    src_1."AllDest_Boy_Est_Previous2_Num" AS "AllDest_Boy_Est_Previous2_Num",
    src_1."AllDest_Boy_Est_Previous2_Pct" AS "AllDest_Boy_Est_Previous2_Pct",
    src_3."AllDest_Dis_Est_Current_Num" AS "AllDest_Dis_Est_Current_Num",
    src_3."AllDest_Dis_Est_Current_Pct" AS "AllDest_Dis_Est_Current_Pct",
    src_2."AllDest_Dis_Est_Previous_Num" AS "AllDest_Dis_Est_Previous_Num",
    src_2."AllDest_Dis_Est_Previous_Pct" AS "AllDest_Dis_Est_Previous_Pct",
    src_1."AllDest_Dis_Est_Previous2_Num" AS "AllDest_Dis_Est_Previous2_Num",
    src_1."AllDest_Dis_Est_Previous2_Pct" AS "AllDest_Dis_Est_Previous2_Pct",
    src_3."AllDest_Grl_Est_Current_Num" AS "AllDest_Grl_Est_Current_Num",
    src_3."AllDest_Grl_Est_Current_Pct" AS "AllDest_Grl_Est_Current_Pct",
    src_2."AllDest_Grl_Est_Previous_Num" AS "AllDest_Grl_Est_Previous_Num",
    src_2."AllDest_Grl_Est_Previous_Pct" AS "AllDest_Grl_Est_Previous_Pct",
    src_1."AllDest_Grl_Est_Previous2_Num" AS "AllDest_Grl_Est_Previous2_Num",
    src_1."AllDest_Grl_Est_Previous2_Pct" AS "AllDest_Grl_Est_Previous2_Pct",
    src_3."AllDest_NDi_Est_Current_Num" AS "AllDest_NDi_Est_Current_Num",
    src_3."AllDest_NDi_Est_Current_Pct" AS "AllDest_NDi_Est_Current_Pct",
    src_2."AllDest_NDi_Est_Previous_Num" AS "AllDest_NDi_Est_Previous_Num",
    src_2."AllDest_NDi_Est_Previous_Pct" AS "AllDest_NDi_Est_Previous_Pct",
    src_1."AllDest_NDi_Est_Previous2_Num" AS "AllDest_NDi_Est_Previous2_Num",
    src_1."AllDest_NDi_Est_Previous2_Pct" AS "AllDest_NDi_Est_Previous2_Pct",
    src_3."AllDest_Tot_Est_Current_Num" AS "AllDest_Tot_Est_Current_Num",
    src_3."AllDest_Tot_Est_Current_Pct" AS "AllDest_Tot_Est_Current_Pct",
    src_2."AllDest_Tot_Est_Previous_Num" AS "AllDest_Tot_Est_Previous_Num",
    src_2."AllDest_Tot_Est_Previous_Pct" AS "AllDest_Tot_Est_Previous_Pct",
    src_1."AllDest_Tot_Est_Previous2_Num" AS "AllDest_Tot_Est_Previous2_Num",
    src_1."AllDest_Tot_Est_Previous2_Pct" AS "AllDest_Tot_Est_Previous2_Pct",
    src_3."Apprentice_Boy_Est_Current_Num" AS "Apprentice_Boy_Est_Current_Num",
    src_3."Apprentice_Boy_Est_Current_Pct" AS "Apprentice_Boy_Est_Current_Pct",
    src_2."Apprentice_Boy_Est_Previous_Num" AS "Apprentice_Boy_Est_Previous_Num",
    src_2."Apprentice_Boy_Est_Previous_Pct" AS "Apprentice_Boy_Est_Previous_Pct",
    src_1."Apprentice_Boy_Est_Previous2_Num" AS "Apprentice_Boy_Est_Previous2_Num",
    src_1."Apprentice_Boy_Est_Previous2_Pct" AS "Apprentice_Boy_Est_Previous2_Pct",
    src_3."Apprentice_Dis_Est_Current_Num" AS "Apprentice_Dis_Est_Current_Num",
    src_3."Apprentice_Dis_Est_Current_Pct" AS "Apprentice_Dis_Est_Current_Pct",
    src_2."Apprentice_Dis_Est_Previous_Num" AS "Apprentice_Dis_Est_Previous_Num",
    src_2."Apprentice_Dis_Est_Previous_Pct" AS "Apprentice_Dis_Est_Previous_Pct",
    src_1."Apprentice_Dis_Est_Previous2_Num" AS "Apprentice_Dis_Est_Previous2_Num",
    src_1."Apprentice_Dis_Est_Previous2_Pct" AS "Apprentice_Dis_Est_Previous2_Pct",
    src_3."Apprentice_Grl_Est_Current_Num" AS "Apprentice_Grl_Est_Current_Num",
    src_3."Apprentice_Grl_Est_Current_Pct" AS "Apprentice_Grl_Est_Current_Pct",
    src_2."Apprentice_Grl_Est_Previous_Num" AS "Apprentice_Grl_Est_Previous_Num",
    src_2."Apprentice_Grl_Est_Previous_Pct" AS "Apprentice_Grl_Est_Previous_Pct",
    src_1."Apprentice_Grl_Est_Previous2_Num" AS "Apprentice_Grl_Est_Previous2_Num",
    src_1."Apprentice_Grl_Est_Previous2_Pct" AS "Apprentice_Grl_Est_Previous2_Pct",
    src_3."Apprentice_NDi_Est_Current_Num" AS "Apprentice_NDi_Est_Current_Num",
    src_3."Apprentice_NDi_Est_Current_Pct" AS "Apprentice_NDi_Est_Current_Pct",
    src_2."Apprentice_NDi_Est_Previous_Num" AS "Apprentice_NDi_Est_Previous_Num",
    src_2."Apprentice_NDi_Est_Previous_Pct" AS "Apprentice_NDi_Est_Previous_Pct",
    src_1."Apprentice_NDi_Est_Previous2_Num" AS "Apprentice_NDi_Est_Previous2_Num",
    src_1."Apprentice_NDi_Est_Previous2_Pct" AS "Apprentice_NDi_Est_Previous2_Pct",
    src_3."Apprentice_Tot_Est_Current_Num" AS "Apprentice_Tot_Est_Current_Num",
    src_3."Apprentice_Tot_Est_Current_Pct" AS "Apprentice_Tot_Est_Current_Pct",
    src_2."Apprentice_Tot_Est_Previous_Num" AS "Apprentice_Tot_Est_Previous_Num",
    src_2."Apprentice_Tot_Est_Previous_Pct" AS "Apprentice_Tot_Est_Previous_Pct",
    src_1."Apprentice_Tot_Est_Previous2_Num" AS "Apprentice_Tot_Est_Previous2_Num",
    src_1."Apprentice_Tot_Est_Previous2_Pct" AS "Apprentice_Tot_Est_Previous2_Pct",
    src_3."Education_Boy_Est_Current_Num" AS "Education_Boy_Est_Current_Num",
    src_3."Education_Boy_Est_Current_Pct" AS "Education_Boy_Est_Current_Pct",
    src_2."Education_Boy_Est_Previous_Num" AS "Education_Boy_Est_Previous_Num",
    src_2."Education_Boy_Est_Previous_Pct" AS "Education_Boy_Est_Previous_Pct",
    src_1."Education_Boy_Est_Previous2_Num" AS "Education_Boy_Est_Previous2_Num",
    src_1."Education_Boy_Est_Previous2_Pct" AS "Education_Boy_Est_Previous2_Pct",
    src_3."Education_Dis_Est_Current_Num" AS "Education_Dis_Est_Current_Num",
    src_3."Education_Dis_Est_Current_Pct" AS "Education_Dis_Est_Current_Pct",
    src_2."Education_Dis_Est_Previous_Num" AS "Education_Dis_Est_Previous_Num",
    src_2."Education_Dis_Est_Previous_Pct" AS "Education_Dis_Est_Previous_Pct",
    src_1."Education_Dis_Est_Previous2_Num" AS "Education_Dis_Est_Previous2_Num",
    src_1."Education_Dis_Est_Previous2_Pct" AS "Education_Dis_Est_Previous2_Pct",
    src_3."Education_Grl_Est_Current_Num" AS "Education_Grl_Est_Current_Num",
    src_3."Education_Grl_Est_Current_Pct" AS "Education_Grl_Est_Current_Pct",
    src_2."Education_Grl_Est_Previous_Num" AS "Education_Grl_Est_Previous_Num",
    src_2."Education_Grl_Est_Previous_Pct" AS "Education_Grl_Est_Previous_Pct",
    src_1."Education_Grl_Est_Previous2_Num" AS "Education_Grl_Est_Previous2_Num",
    src_1."Education_Grl_Est_Previous2_Pct" AS "Education_Grl_Est_Previous2_Pct",
    src_3."Education_NDi_Est_Current_Num" AS "Education_NDi_Est_Current_Num",
    src_3."Education_NDi_Est_Current_Pct" AS "Education_NDi_Est_Current_Pct",
    src_2."Education_NDi_Est_Previous_Num" AS "Education_NDi_Est_Previous_Num",
    src_2."Education_NDi_Est_Previous_Pct" AS "Education_NDi_Est_Previous_Pct",
    src_1."Education_NDi_Est_Previous2_Num" AS "Education_NDi_Est_Previous2_Num",
    src_1."Education_NDi_Est_Previous2_Pct" AS "Education_NDi_Est_Previous2_Pct",
    src_3."Education_Tot_Est_Current_Num" AS "Education_Tot_Est_Current_Num",
    src_3."Education_Tot_Est_Current_Pct" AS "Education_Tot_Est_Current_Pct",
    src_2."Education_Tot_Est_Previous_Num" AS "Education_Tot_Est_Previous_Num",
    src_2."Education_Tot_Est_Previous_Pct" AS "Education_Tot_Est_Previous_Pct",
    src_1."Education_Tot_Est_Previous2_Num" AS "Education_Tot_Est_Previous2_Num",
    src_1."Education_Tot_Est_Previous2_Pct" AS "Education_Tot_Est_Previous2_Pct",
    src_3."Employment_Boy_Est_Current_Num" AS "Employment_Boy_Est_Current_Num",
    src_3."Employment_Boy_Est_Current_Pct" AS "Employment_Boy_Est_Current_Pct",
    src_2."Employment_Boy_Est_Previous_Num" AS "Employment_Boy_Est_Previous_Num",
    src_2."Employment_Boy_Est_Previous_Pct" AS "Employment_Boy_Est_Previous_Pct",
    src_1."Employment_Boy_Est_Previous2_Num" AS "Employment_Boy_Est_Previous2_Num",
    src_1."Employment_Boy_Est_Previous2_Pct" AS "Employment_Boy_Est_Previous2_Pct",
    src_3."Employment_Dis_Est_Current_Num" AS "Employment_Dis_Est_Current_Num",
    src_3."Employment_Dis_Est_Current_Pct" AS "Employment_Dis_Est_Current_Pct",
    src_2."Employment_Dis_Est_Previous_Num" AS "Employment_Dis_Est_Previous_Num",
    src_2."Employment_Dis_Est_Previous_Pct" AS "Employment_Dis_Est_Previous_Pct",
    src_1."Employment_Dis_Est_Previous2_Num" AS "Employment_Dis_Est_Previous2_Num",
    src_1."Employment_Dis_Est_Previous2_Pct" AS "Employment_Dis_Est_Previous2_Pct",
    src_3."Employment_Grl_Est_Current_Num" AS "Employment_Grl_Est_Current_Num",
    src_3."Employment_Grl_Est_Current_Pct" AS "Employment_Grl_Est_Current_Pct",
    src_2."Employment_Grl_Est_Previous_Num" AS "Employment_Grl_Est_Previous_Num",
    src_2."Employment_Grl_Est_Previous_Pct" AS "Employment_Grl_Est_Previous_Pct",
    src_1."Employment_Grl_Est_Previous2_Num" AS "Employment_Grl_Est_Previous2_Num",
    src_1."Employment_Grl_Est_Previous2_Pct" AS "Employment_Grl_Est_Previous2_Pct",
    src_3."Employment_NDi_Est_Current_Num" AS "Employment_NDi_Est_Current_Num",
    src_3."Employment_NDi_Est_Current_Pct" AS "Employment_NDi_Est_Current_Pct",
    src_2."Employment_NDi_Est_Previous_Num" AS "Employment_NDi_Est_Previous_Num",
    src_2."Employment_NDi_Est_Previous_Pct" AS "Employment_NDi_Est_Previous_Pct",
    src_1."Employment_NDi_Est_Previous2_Num" AS "Employment_NDi_Est_Previous2_Num",
    src_1."Employment_NDi_Est_Previous2_Pct" AS "Employment_NDi_Est_Previous2_Pct",
    src_3."Employment_Tot_Est_Current_Num" AS "Employment_Tot_Est_Current_Num",
    src_3."Employment_Tot_Est_Current_Pct" AS "Employment_Tot_Est_Current_Pct",
    src_2."Employment_Tot_Est_Previous_Num" AS "Employment_Tot_Est_Previous_Num",
    src_2."Employment_Tot_Est_Previous_Pct" AS "Employment_Tot_Est_Previous_Pct",
    src_1."Employment_Tot_Est_Previous2_Num" AS "Employment_Tot_Est_Previous2_Num",
    src_1."Employment_Tot_Est_Previous2_Pct" AS "Employment_Tot_Est_Previous2_Pct"
FROM src_1
LEFT JOIN src_2 ON src_2."Id" = src_1."Id"
LEFT JOIN src_3 ON src_3."Id" = src_1."Id"
;
