-- AUTO-GENERATED MATERIALIZED VIEW: v_la_performance

DROP MATERIALIZED VIEW IF EXISTS v_la_performance;

CREATE MATERIALIZED VIEW v_la_performance AS
WITH
src_1 AS (
    SELECT
        t."old_la_code" AS "Id",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."gender" = 'Boys' THEN clean_int(t."t_l2basics_94") END) AS "EngMaths49_Boy_LA_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."gender" = 'Boys' THEN clean_numeric(t."pt_l2basics_94") END) AS "EngMaths49_Boy_LA_Previous2_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."gender" = 'Boys' THEN clean_int(t."t_l2basics_95") END) AS "EngMaths59_Boy_LA_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."gender" = 'Boys' THEN clean_numeric(t."pt_l2basics_95") END) AS "EngMaths59_Boy_LA_Previous2_Pct",
        MAX(CASE WHEN t."breakdown" = 'Disadvantage' AND t."disadvantage" = 'Disadvantaged' AND t."gender" = 'Total' THEN clean_int(t."t_l2basics_94") END) AS "EngMaths49_Dis_LA_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantage' AND t."disadvantage" = 'Disadvantaged' AND t."gender" = 'Total' THEN clean_numeric(t."pt_l2basics_94") END) AS "EngMaths49_Dis_LA_Previous2_Pct",
        MAX(CASE WHEN t."breakdown" = 'Disadvantage' AND t."disadvantage" = 'Disadvantaged' AND t."gender" = 'Total' THEN clean_int(t."t_l2basics_95") END) AS "EngMaths59_Dis_LA_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantage' AND t."disadvantage" = 'Disadvantaged' AND t."gender" = 'Total' THEN clean_numeric(t."pt_l2basics_95") END) AS "EngMaths59_Dis_LA_Previous2_Pct",
        MAX(CASE WHEN t."breakdown" = 'First language' AND t."first_language" = 'Other than English' AND t."gender" = 'Total' THEN clean_int(t."t_l2basics_94") END) AS "EngMaths49_EAL_LA_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'First language' AND t."first_language" = 'Other than English' AND t."gender" = 'Total' THEN clean_numeric(t."pt_l2basics_94") END) AS "EngMaths49_EAL_LA_Previous2_Pct",
        MAX(CASE WHEN t."breakdown" = 'First language' AND t."first_language" = 'Other than English' AND t."gender" = 'Total' THEN clean_int(t."t_l2basics_95") END) AS "EngMaths59_EAL_LA_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'First language' AND t."first_language" = 'Other than English' AND t."gender" = 'Total' THEN clean_numeric(t."pt_l2basics_95") END) AS "EngMaths59_EAL_LA_Previous2_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."gender" = 'Girls' THEN clean_int(t."t_l2basics_94") END) AS "EngMaths49_Grl_LA_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."gender" = 'Girls' THEN clean_numeric(t."pt_l2basics_94") END) AS "EngMaths49_Grl_LA_Previous2_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."gender" = 'Girls' THEN clean_int(t."t_l2basics_95") END) AS "EngMaths59_Grl_LA_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."gender" = 'Girls' THEN clean_numeric(t."pt_l2basics_95") END) AS "EngMaths59_Grl_LA_Previous2_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."gender" = 'Total' THEN clean_int(t."t_l2basics_94") END) AS "EngMaths49_Tot_LA_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."gender" = 'Total' THEN clean_numeric(t."pt_l2basics_94") END) AS "EngMaths49_Tot_LA_Previous2_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."gender" = 'Total' THEN clean_int(t."t_l2basics_95") END) AS "EngMaths59_Tot_LA_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."gender" = 'Total' THEN clean_numeric(t."pt_l2basics_95") END) AS "EngMaths59_Tot_LA_Previous2_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."gender" = 'Boys' THEN t."t_att8" END) AS "Attainment8_Boy_LA_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantage' AND t."gender" = 'Total' AND t."disadvantage" = 'Disadvantaged' THEN t."t_att8" END) AS "Attainment8_Dis_LA_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'First language' AND t."gender" = 'Total' AND t."first_language" = 'Other than English' THEN t."t_att8" END) AS "Attainment8_EAL_LA_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."gender" = 'Girls' THEN t."t_att8" END) AS "Attainment8_Grl_LA_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."gender" = 'Total' THEN t."t_att8" END) AS "Attainment8_Tot_LA_Previous2_Num"
    FROM raw_2223_la_char_data__951c641f t
    GROUP BY t."old_la_code"
),
src_2 AS (
    SELECT
        t."old_la_code" AS "Id",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."sex" = 'Total' THEN t."t_att8" END) AS "Prog8_Avg_LA_Previous2_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."sex" = 'Boys' THEN t."t_att8" END) AS "Attainment8_Boy_LA_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantage' AND t."sex" = 'Total' AND t."disadvantage" = 'Disadvantaged' THEN t."t_att8" END) AS "Attainment8_Dis_LA_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'First language' AND t."sex" = 'Total' AND t."first_language" = 'Other than English' THEN t."t_att8" END) AS "Attainment8_EAL_LA_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."sex" = 'Boys' THEN clean_int(t."t_l2basics_94") END) AS "EngMaths49_Boy_LA_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."sex" = 'Boys' THEN clean_numeric(t."pt_l2basics_94") END) AS "EngMaths49_Boy_LA_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."sex" = 'Boys' THEN clean_int(t."t_l2basics_95") END) AS "EngMaths59_Boy_LA_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."sex" = 'Boys' THEN clean_numeric(t."pt_l2basics_95") END) AS "EngMaths59_Boy_LA_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Disadvantage' AND t."disadvantage" = 'Disadvantaged' AND t."sex" = 'Total' THEN clean_int(t."t_l2basics_94") END) AS "EngMaths49_Dis_LA_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantage' AND t."disadvantage" = 'Disadvantaged' AND t."sex" = 'Total' THEN clean_numeric(t."pt_l2basics_94") END) AS "EngMaths49_Dis_LA_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Disadvantage' AND t."disadvantage" = 'Disadvantaged' AND t."sex" = 'Total' THEN clean_int(t."t_l2basics_95") END) AS "EngMaths59_Dis_LA_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Disadvantage' AND t."disadvantage" = 'Disadvantaged' AND t."sex" = 'Total' THEN clean_numeric(t."pt_l2basics_95") END) AS "EngMaths59_Dis_LA_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."sex" = 'Girls' THEN t."t_att8" END) AS "Attainment8_Grl_LA_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'First language' AND t."first_language" = 'Other than English' AND t."sex" = 'Total' THEN clean_int(t."t_l2basics_94") END) AS "EngMaths49_EAL_LA_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'First language' AND t."first_language" = 'Other than English' AND t."sex" = 'Total' THEN clean_numeric(t."pt_l2basics_94") END) AS "EngMaths49_EAL_LA_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'First language' AND t."first_language" = 'Other than English' AND t."sex" = 'Total' THEN clean_int(t."t_l2basics_95") END) AS "EngMaths59_EAL_LA_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'First language' AND t."first_language" = 'Other than English' AND t."sex" = 'Total' THEN clean_numeric(t."pt_l2basics_95") END) AS "EngMaths59_EAL_LA_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."sex" = 'Girls' THEN clean_int(t."t_l2basics_94") END) AS "EngMaths49_Grl_LA_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."sex" = 'Girls' THEN clean_numeric(t."pt_l2basics_94") END) AS "EngMaths49_Grl_LA_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."sex" = 'Girls' THEN clean_int(t."t_l2basics_95") END) AS "EngMaths59_Grl_LA_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."sex" = 'Girls' THEN clean_numeric(t."pt_l2basics_95") END) AS "EngMaths59_Grl_LA_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."sex" = 'Total' THEN t."t_att8" END) AS "Attainment8_Tot_LA_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."sex" = 'Total' THEN clean_int(t."t_l2basics_94") END) AS "EngMaths49_Tot_LA_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."sex" = 'Total' THEN clean_numeric(t."pt_l2basics_94") END) AS "EngMaths49_Tot_LA_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."sex" = 'Total' THEN clean_int(t."t_l2basics_95") END) AS "EngMaths59_Tot_LA_Previous_Num",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."sex" = 'Total' THEN clean_numeric(t."pt_l2basics_95") END) AS "EngMaths59_Tot_LA_Previous_Pct",
        MAX(CASE WHEN t."breakdown" = 'Total' AND t."sex" = 'Total' THEN t."avg_p8score" END) AS "Prog8_Avg_LA_Previous_Num"
    FROM raw_202324_la_char_dat_34c2fcb1 t
    GROUP BY t."old_la_code"
),
src_3 AS (
    SELECT
        t."old_la_code" AS "Id",
        MAX(CASE WHEN t."subject" = 'Biology' AND t."grade" = '9 to 4' AND t."sex" = 'Boys' THEN clean_int(t."number_achieving") END) AS "Bio49_Boy_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Chemistry' AND t."grade" = '9 to 4' AND t."sex" = 'Boys' THEN clean_int(t."number_achieving") END) AS "Chem49_Boy_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Chemistry' AND t."grade" = '9 to 5' AND t."sex" = 'Boys' THEN clean_int(t."number_achieving") END) AS "Chem59_Boy_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Combined Science' AND t."grade" = '9 to 4' AND t."sex" = 'Boys' THEN clean_int(t."number_achieving") END) AS "CombSci49_Boy_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Combined Science' AND t."grade" = '9 to 5' AND t."sex" = 'Boys' THEN clean_int(t."number_achieving") END) AS "CombSci59_Boy_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'English Language' AND t."grade" = '9 to 4' AND t."sex" = 'Boys' THEN clean_int(t."number_achieving") END) AS "EngLang49_Boy_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'English Language' AND t."grade" = '9 to 5' AND t."sex" = 'Boys' THEN clean_int(t."number_achieving") END) AS "EngLang59_Boy_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'English Literature' AND t."grade" = '9 to 4' AND t."sex" = 'Boys' THEN clean_int(t."number_achieving") END) AS "EngLit49_Boy_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'English Literature' AND t."grade" = '9 to 5' AND t."sex" = 'Boys' THEN clean_int(t."number_achieving") END) AS "EngLit59_Boy_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Mathematics' AND t."grade" = '9 to 4' AND t."sex" = 'Boys' THEN clean_int(t."number_achieving") END) AS "Maths49_Boy_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Mathematics' AND t."grade" = '9 to 5' AND t."sex" = 'Boys' THEN clean_int(t."number_achieving") END) AS "Maths59_Boy_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Physics' AND t."grade" = '9 to 4' AND t."sex" = 'Boys' THEN clean_int(t."number_achieving") END) AS "Physics49_Boy_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Physics' AND t."grade" = '9 to 5' AND t."sex" = 'Boys' THEN clean_int(t."number_achieving") END) AS "Physics59_Boy_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Biology' AND t."grade" = '9 to 4' AND t."sex" = 'Girls' THEN clean_int(t."number_achieving") END) AS "Bio49_Grl_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Chemistry' AND t."grade" = '9 to 4' AND t."sex" = 'Girls' THEN clean_int(t."number_achieving") END) AS "Chem49_Grl_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Chemistry' AND t."grade" = '9 to 5' AND t."sex" = 'Girls' THEN clean_int(t."number_achieving") END) AS "Chem59_Grl_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Combined Science' AND t."grade" = '9 to 4' AND t."sex" = 'Girls' THEN clean_int(t."number_achieving") END) AS "CombSci49_Grl_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Combined Science' AND t."grade" = '9 to 5' AND t."sex" = 'Girls' THEN clean_int(t."number_achieving") END) AS "CombSci59_Grl_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'English Language' AND t."grade" = '9 to 4' AND t."sex" = 'Girls' THEN clean_int(t."number_achieving") END) AS "EngLang49_Grl_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'English Language' AND t."grade" = '9 to 5' AND t."sex" = 'Girls' THEN clean_int(t."number_achieving") END) AS "EngLang59_Grl_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'English Literature' AND t."grade" = '9 to 4' AND t."sex" = 'Girls' THEN clean_int(t."number_achieving") END) AS "EngLit49_Grl_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'English Literature' AND t."grade" = '9 to 5' AND t."sex" = 'Girls' THEN clean_int(t."number_achieving") END) AS "EngLit59_Grl_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Mathematics' AND t."grade" = '9 to 4' AND t."sex" = 'Girls' THEN clean_int(t."number_achieving") END) AS "Maths49_Grl_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Mathematics' AND t."grade" = '9 to 5' AND t."sex" = 'Girls' THEN clean_int(t."number_achieving") END) AS "Maths59_Grl_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Physics' AND t."grade" = '9 to 4' AND t."sex" = 'Girls' THEN clean_int(t."number_achieving") END) AS "Physics49_Grl_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Physics' AND t."grade" = '9 to 5' AND t."sex" = 'Girls' THEN clean_int(t."number_achieving") END) AS "Physics59_Grl_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Biology' AND t."grade" = '9 to 4' AND t."sex" = 'Total' THEN clean_int(t."number_achieving") END) AS "Bio49_Tot_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Chemistry' AND t."grade" = '9 to 4' AND t."sex" = 'Total' THEN clean_int(t."number_achieving") END) AS "Chem49_Tot_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Chemistry' AND t."grade" = '9 to 5' AND t."sex" = 'Total' THEN clean_int(t."number_achieving") END) AS "Chem59_Tot_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Combined Science' AND t."grade" = '9 to 4' AND t."sex" = 'Total' THEN clean_int(t."number_achieving") END) AS "CombSci49_Tot_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Combined Science' AND t."grade" = '9 to 5' AND t."sex" = 'Total' THEN clean_int(t."number_achieving") END) AS "CombSci59_Tot_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'English Language' AND t."grade" = '9 to 4' AND t."sex" = 'Total' THEN clean_int(t."number_achieving") END) AS "EngLang49_Tot_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'English Language' AND t."grade" = '9 to 5' AND t."sex" = 'Total' THEN clean_int(t."number_achieving") END) AS "EngLang59_Tot_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'English Literature' AND t."grade" = '9 to 4' AND t."sex" = 'Total' THEN clean_int(t."number_achieving") END) AS "EngLit49_Tot_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'English Literature' AND t."grade" = '9 to 5' AND t."sex" = 'Total' THEN clean_int(t."number_achieving") END) AS "EngLit59_Tot_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Mathematics' AND t."grade" = '9 to 4' AND t."sex" = 'Total' THEN clean_int(t."number_achieving") END) AS "Maths49_Tot_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Mathematics' AND t."grade" = '9 to 5' AND t."sex" = 'Total' THEN clean_int(t."number_achieving") END) AS "Maths59_Tot_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Physics' AND t."grade" = '9 to 4' AND t."sex" = 'Total' THEN clean_int(t."number_achieving") END) AS "Physics49_Tot_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Physics' AND t."grade" = '9 to 5' AND t."sex" = 'Total' THEN clean_int(t."number_achieving") END) AS "Physics59_Tot_LA_Previous_Num"
    FROM raw_202324_subject_pup_2ab324f6 t
    GROUP BY t."old_la_code"
),
src_4 AS (
    SELECT
        t."old_la_code" AS "Id",
        MAX(CASE WHEN t."subject" = 'Biology' AND t."grade" = '9 to 4' AND t."gender" = 'Boys' THEN clean_int(t."number_achieving") END) AS "Bio49_Boy_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Chemistry' AND t."grade" = '9 to 4' AND t."gender" = 'Boys' THEN clean_int(t."number_achieving") END) AS "Chem49_Boy_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Chemistry' AND t."grade" = '9 to 5' AND t."gender" = 'Boys' THEN clean_int(t."number_achieving") END) AS "Chem59_Boy_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Combined Science' AND t."grade" = '9 to 4' AND t."gender" = 'Boys' THEN clean_int(t."number_achieving") END) AS "CombSci49_Boy_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Combined Science' AND t."grade" = '9 to 5' AND t."gender" = 'Boys' THEN clean_int(t."number_achieving") END) AS "CombSci59_Boy_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'English Language' AND t."grade" = '9 to 4' AND t."gender" = 'Boys' THEN clean_int(t."number_achieving") END) AS "EngLang49_Boy_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'English Language' AND t."grade" = '9 to 5' AND t."gender" = 'Boys' THEN clean_int(t."number_achieving") END) AS "EngLang59_Boy_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'English Literature' AND t."grade" = '9 to 4' AND t."gender" = 'Boys' THEN clean_int(t."number_achieving") END) AS "EngLit49_Boy_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'English Literature' AND t."grade" = '9 to 5' AND t."gender" = 'Boys' THEN clean_int(t."number_achieving") END) AS "EngLit59_Boy_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Mathematics' AND t."grade" = '9 to 4' AND t."gender" = 'Boys' THEN clean_int(t."number_achieving") END) AS "Maths49_Boy_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Mathematics' AND t."grade" = '9 to 5' AND t."gender" = 'Boys' THEN clean_int(t."number_achieving") END) AS "Maths59_Boy_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Physics' AND t."grade" = '9 to 4' AND t."gender" = 'Boys' THEN clean_int(t."number_achieving") END) AS "Physics49_Boy_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Physics' AND t."grade" = '9 to 5' AND t."gender" = 'Boys' THEN clean_int(t."number_achieving") END) AS "Physics59_Boy_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Biology' AND t."grade" = '9 to 4' AND t."gender" = 'Girls' THEN clean_int(t."number_achieving") END) AS "Bio49_Grl_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Chemistry' AND t."grade" = '9 to 4' AND t."gender" = 'Girls' THEN clean_int(t."number_achieving") END) AS "Chem49_Grl_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Chemistry' AND t."grade" = '9 to 5' AND t."gender" = 'Girls' THEN clean_int(t."number_achieving") END) AS "Chem59_Grl_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Combined Science' AND t."grade" = '9 to 4' AND t."gender" = 'Girls' THEN clean_int(t."number_achieving") END) AS "CombSci49_Grl_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Combined Science' AND t."grade" = '9 to 5' AND t."gender" = 'Girls' THEN clean_int(t."number_achieving") END) AS "CombSci59_Grl_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'English Language' AND t."grade" = '9 to 4' AND t."gender" = 'Girls' THEN clean_int(t."number_achieving") END) AS "EngLang49_Grl_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'English Language' AND t."grade" = '9 to 5' AND t."gender" = 'Girls' THEN clean_int(t."number_achieving") END) AS "EngLang59_Grl_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'English Literature' AND t."grade" = '9 to 4' AND t."gender" = 'Girls' THEN clean_int(t."number_achieving") END) AS "EngLit49_Grl_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'English Literature' AND t."grade" = '9 to 5' AND t."gender" = 'Girls' THEN clean_int(t."number_achieving") END) AS "EngLit59_Grl_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Mathematics' AND t."grade" = '9 to 4' AND t."gender" = 'Girls' THEN clean_int(t."number_achieving") END) AS "Maths49_Grl_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Mathematics' AND t."grade" = '9 to 5' AND t."gender" = 'Girls' THEN clean_int(t."number_achieving") END) AS "Maths59_Grl_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Physics' AND t."grade" = '9 to 4' AND t."gender" = 'Girls' THEN clean_int(t."number_achieving") END) AS "Physics49_Grl_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Physics' AND t."grade" = '9 to 5' AND t."gender" = 'Girls' THEN clean_int(t."number_achieving") END) AS "Physics59_Grl_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Biology' AND t."grade" = '9 to 4' AND t."gender" = 'Total' THEN clean_int(t."number_achieving") END) AS "Bio49_Tot_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Chemistry' AND t."grade" = '9 to 4' AND t."gender" = 'Total' THEN clean_int(t."number_achieving") END) AS "Chem49_Tot_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Chemistry' AND t."grade" = '9 to 5' AND t."gender" = 'Total' THEN clean_int(t."number_achieving") END) AS "Chem59_Tot_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Combined Science' AND t."grade" = '9 to 4' AND t."gender" = 'Total' THEN clean_int(t."number_achieving") END) AS "CombSci49_Tot_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Combined Science' AND t."grade" = '9 to 5' AND t."gender" = 'Total' THEN clean_int(t."number_achieving") END) AS "CombSci59_Tot_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'English Language' AND t."grade" = '9 to 4' AND t."gender" = 'Total' THEN clean_int(t."number_achieving") END) AS "EngLang49_Tot_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'English Language' AND t."grade" = '9 to 5' AND t."gender" = 'Total' THEN clean_int(t."number_achieving") END) AS "EngLang59_Tot_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'English Literature' AND t."grade" = '9 to 4' AND t."gender" = 'Total' THEN clean_int(t."number_achieving") END) AS "EngLit49_Tot_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'English Literature' AND t."grade" = '9 to 5' AND t."gender" = 'Total' THEN clean_int(t."number_achieving") END) AS "EngLit59_Tot_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Mathematics' AND t."grade" = '9 to 4' AND t."gender" = 'Total' THEN clean_int(t."number_achieving") END) AS "Maths49_Tot_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Mathematics' AND t."grade" = '9 to 5' AND t."gender" = 'Total' THEN clean_int(t."number_achieving") END) AS "Maths59_Tot_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Physics' AND t."grade" = '9 to 4' AND t."gender" = 'Total' THEN clean_int(t."number_achieving") END) AS "Physics49_Tot_LA_Previous_Num",
        MAX(CASE WHEN t."subject" = 'Physics' AND t."grade" = '9 to 5' AND t."gender" = 'Total' THEN clean_int(t."number_achieving") END) AS "Physics59_Tot_LA_Previous_Num"
    FROM raw_2223_subject_pupil_a6edee97 t
    GROUP BY t."old_la_code"
),
src_5 AS (
    SELECT
        t."old_la_code" AS "Id",
        MAX(CASE WHEN t."breakdown_topic" = 'Sex' AND t."sex" = 'Boys' AND t."time_period" = '202425' THEN clean_int(t."attainment8_average") END) AS "Attainment8_Boy_LA_Current_Num",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."disadvantage_status" = 'Disadvantaged' AND t."time_period" = '202425' THEN clean_int(t."attainment8_average") END) AS "Attainment8_Dis_LA_Current_Num",
        MAX(CASE WHEN t."breakdown_topic" = 'Sex' AND t."sex" = 'Boys' AND t."time_period" = '202425' THEN clean_int(t."engmath_94_total") END) AS "EngMaths49_Boy_LA_Current_Num",
        MAX(CASE WHEN t."breakdown_topic" = 'Sex' AND t."sex" = 'Boys' AND t."time_period" = '202425' THEN clean_numeric(t."engmath_94_percent") END) AS "EngMaths49_Boy_LA_Current_Pct",
        MAX(CASE WHEN t."breakdown_topic" = 'Sex' AND t."sex" = 'Boys' AND t."time_period" = '202425' THEN clean_int(t."engmath_95_total") END) AS "EngMaths59_Boy_LA_Current_Num",
        MAX(CASE WHEN t."breakdown_topic" = 'Sex' AND t."sex" = 'Boys' AND t."time_period" = '202425' THEN clean_numeric(t."engmath_95_percent") END) AS "EngMaths59_Boy_LA_Current_Pct",
        MAX(CASE WHEN t."breakdown_topic" = 'First language' AND t."first_language" = 'Known or believed to be other than English' AND t."time_period" = '202425' THEN clean_int(t."attainment8_average") END) AS "Attainment8_EAL_LA_Current_Num",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."disadvantage_status" = 'Disadvantaged' AND t."time_period" = '202425' THEN clean_int(t."engmath_94_total") END) AS "EngMaths49_Dis_LA_Current_Num",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."disadvantage_status" = 'Disadvantaged' AND t."time_period" = '202425' THEN clean_numeric(t."engmath_94_percent") END) AS "EngMaths49_Dis_LA_Current_Pct",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."disadvantage_status" = 'Disadvantaged' AND t."time_period" = '202425' THEN clean_int(t."engmath_95_total") END) AS "EngMaths59_Dis_LA_Current_Num",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."disadvantage_status" = 'Disadvantaged' AND t."time_period" = '202425' THEN clean_numeric(t."engmath_95_percent") END) AS "EngMaths59_Dis_LA_Current_Pct",
        MAX(CASE WHEN t."breakdown_topic" = 'First language' AND t."first_language" = 'Known or believed to be other than English' AND t."time_period" = '202425' THEN clean_int(t."engmath_94_total") END) AS "EngMaths49_EAL_LA_Current_Num",
        MAX(CASE WHEN t."breakdown_topic" = 'First language' AND t."first_language" = 'Known or believed to be other than English' AND t."time_period" = '202425' THEN clean_numeric(t."engmath_94_percent") END) AS "EngMaths49_EAL_LA_Current_Pct",
        MAX(CASE WHEN t."breakdown_topic" = 'First language' AND t."first_language" = 'Known or believed to be other than English' AND t."time_period" = '202425' THEN clean_int(t."engmath_95_total") END) AS "EngMaths59_EAL_LA_Current_Num",
        MAX(CASE WHEN t."breakdown_topic" = 'First language' AND t."first_language" = 'Known or believed to be other than English' AND t."time_period" = '202425' THEN clean_numeric(t."engmath_95_percent") END) AS "EngMaths59_EAL_LA_Current_Pct",
        MAX(CASE WHEN t."breakdown_topic" = 'Sex' AND t."sex" = 'Girls' AND t."time_period" = '202425' THEN clean_int(t."engmath_94_total") END) AS "EngMaths49_Grl_LA_Current_Num",
        MAX(CASE WHEN t."breakdown_topic" = 'Sex' AND t."sex" = 'Girls' AND t."time_period" = '202425' THEN clean_numeric(t."engmath_94_percent") END) AS "EngMaths49_Grl_LA_Current_Pct",
        MAX(CASE WHEN t."breakdown_topic" = 'Sex' AND t."sex" = 'Girls' AND t."time_period" = '202425' THEN clean_int(t."engmath_95_total") END) AS "EngMaths59_Grl_LA_Current_Num",
        MAX(CASE WHEN t."breakdown_topic" = 'Sex' AND t."sex" = 'Girls' AND t."time_period" = '202425' THEN clean_numeric(t."engmath_95_percent") END) AS "EngMaths59_Grl_LA_Current_Pct",
        MAX(CASE WHEN t."breakdown_topic" = 'Sex' AND t."sex" = 'Girls' AND t."time_period" = '202425' THEN clean_int(t."attainment8_average") END) AS "Attainment8_Grl_LA_Current_Num",
        MAX(CASE WHEN t."breakdown_topic" = 'Mobility' AND t."mobility" = 'Non mobile' AND t."time_period" = '202425' THEN clean_int(t."engmath_94_total") END) AS "EngMaths49_Mob_LA_Current_Num",
        MAX(CASE WHEN t."breakdown_topic" = 'Mobility' AND t."mobility" = 'Non mobile' AND t."time_period" = '202425' THEN clean_numeric(t."engmath_94_percent") END) AS "EngMaths49_Mob_LA_Current_Pct",
        MAX(CASE WHEN t."breakdown_topic" = 'Mobility' AND t."mobility" = 'Non mobile' AND t."time_period" = '202425' THEN clean_int(t."engmath_95_total") END) AS "EngMaths59_Mob_LA_Current_Num",
        MAX(CASE WHEN t."breakdown_topic" = 'Mobility' AND t."mobility" = 'Non mobile' AND t."time_period" = '202425' THEN clean_numeric(t."engmath_95_percent") END) AS "EngMaths59_Mob_LA_Current_Pct",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."disadvantage_status" = 'Not known to be disadvantaged' AND t."time_period" = '202425' THEN clean_int(t."engmath_94_total") END) AS "EngMaths49_NDi_LA_Current_Num",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."disadvantage_status" = 'Not known to be disadvantaged' AND t."time_period" = '202425' THEN clean_numeric(t."engmath_94_percent") END) AS "EngMaths49_NDi_LA_Current_Pct",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."disadvantage_status" = 'Not known to be disadvantaged' AND t."time_period" = '202425' THEN clean_int(t."engmath_95_total") END) AS "EngMaths59_NDi_LA_Current_Num",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."disadvantage_status" = 'Not known to be disadvantaged' AND t."time_period" = '202425' THEN clean_numeric(t."engmath_95_percent") END) AS "EngMaths59_NDi_LA_Current_Pct",
        MAX(CASE WHEN t."breakdown_topic" = 'Mobility' AND t."mobility" = 'Non mobile' AND t."time_period" = '202425' THEN clean_int(t."attainment8_average") END) AS "Attainment8_Mob_LA_Current_Num",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202425' THEN clean_int(t."engmath_94_total") END) AS "EngMaths49_Tot_LA_Current_Num",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202425' THEN clean_numeric(t."engmath_94_percent") END) AS "EngMaths49_Tot_LA_Current_Pct",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202425' THEN clean_int(t."engmath_95_total") END) AS "EngMaths59_Tot_LA_Current_Num",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202425' THEN clean_numeric(t."engmath_95_percent") END) AS "EngMaths59_Tot_LA_Current_Pct",
        MAX(CASE WHEN t."breakdown_topic" = 'Disadvantage status' AND t."disadvantage_status" = 'Not known to be disadvantaged' AND t."time_period" = '202425' THEN clean_int(t."attainment8_average") END) AS "Attainment8_NDi_LA_Current_Num",
        MAX(CASE WHEN t."breakdown_topic" = 'Total' AND t."time_period" = '202425' THEN clean_int(t."attainment8_average") END) AS "Attainment8_Tot_LA_Current_Num"
    FROM raw_202425_all_state_f_2d605f2b t
    GROUP BY t."old_la_code"
),
src_6 AS (
    SELECT
        t."old_la_code" AS "Id",
        MAX(CASE WHEN t."subject" = 'Biology' AND t."grade" = '9 to 4' AND t."sex" = 'Boys' THEN clean_int(t."number_achieving") END) AS "Bio49_Boy_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'Chemistry' AND t."grade" = '9 to 4' AND t."sex" = 'Boys' THEN clean_int(t."number_achieving") END) AS "Chem49_Boy_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'Chemistry' AND t."grade" = '9 to 5' AND t."sex" = 'Boys' THEN clean_int(t."number_achieving") END) AS "Chem59_Boy_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'Combined Science' AND t."grade" = '9 to 4' AND t."sex" = 'Boys' THEN clean_int(t."number_achieving") END) AS "CombSci49_Boy_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'Combined Science' AND t."grade" = '9 to 5' AND t."sex" = 'Boys' THEN clean_int(t."number_achieving") END) AS "CombSci59_Boy_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'English Language' AND t."grade" = '9 to 4' AND t."sex" = 'Boys' THEN clean_int(t."number_achieving") END) AS "EngLang49_Boy_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'English Language' AND t."grade" = '9 to 5' AND t."sex" = 'Boys' THEN clean_int(t."number_achieving") END) AS "EngLang59_Boy_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'English Literature' AND t."grade" = '9 to 4' AND t."sex" = 'Boys' THEN clean_int(t."number_achieving") END) AS "EngLit49_Boy_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'English Literature' AND t."grade" = '9 to 5' AND t."sex" = 'Boys' THEN clean_int(t."number_achieving") END) AS "EngLit59_Boy_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'Mathematics' AND t."grade" = '9 to 4' AND t."sex" = 'Boys' THEN clean_int(t."number_achieving") END) AS "Maths49_Boy_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'Mathematics' AND t."grade" = '9 to 5' AND t."sex" = 'Boys' THEN clean_int(t."number_achieving") END) AS "Maths59_Boy_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'Physics' AND t."grade" = '9 to 4' AND t."sex" = 'Boys' THEN clean_int(t."number_achieving") END) AS "Physics49_Boy_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'Physics' AND t."grade" = '9 to 5' AND t."sex" = 'Boys' THEN clean_int(t."number_achieving") END) AS "Physics59_Boy_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'Biology' AND t."grade" = '9 to 4' AND t."sex" = 'Girls' THEN clean_int(t."number_achieving") END) AS "Bio49_Grl_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'Chemistry' AND t."grade" = '9 to 4' AND t."sex" = 'Girls' THEN clean_int(t."number_achieving") END) AS "Chem49_Grl_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'Chemistry' AND t."grade" = '9 to 5' AND t."sex" = 'Girls' THEN clean_int(t."number_achieving") END) AS "Chem59_Grl_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'Combined Science' AND t."grade" = '9 to 4' AND t."sex" = 'Girls' THEN clean_int(t."number_achieving") END) AS "CombSci49_Grl_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'Combined Science' AND t."grade" = '9 to 5' AND t."sex" = 'Girls' THEN clean_int(t."number_achieving") END) AS "CombSci59_Grl_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'English Language' AND t."grade" = '9 to 4' AND t."sex" = 'Girls' THEN clean_int(t."number_achieving") END) AS "EngLang49_Grl_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'English Language' AND t."grade" = '9 to 5' AND t."sex" = 'Girls' THEN clean_int(t."number_achieving") END) AS "EngLang59_Grl_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'English Literature' AND t."grade" = '9 to 4' AND t."sex" = 'Girls' THEN clean_int(t."number_achieving") END) AS "EngLit49_Grl_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'English Literature' AND t."grade" = '9 to 5' AND t."sex" = 'Girls' THEN clean_int(t."number_achieving") END) AS "EngLit59_Grl_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'Mathematics' AND t."grade" = '9 to 4' AND t."sex" = 'Girls' THEN clean_int(t."number_achieving") END) AS "Maths49_Grl_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'Mathematics' AND t."grade" = '9 to 5' AND t."sex" = 'Girls' THEN clean_int(t."number_achieving") END) AS "Maths59_Grl_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'Physics' AND t."grade" = '9 to 4' AND t."sex" = 'Girls' THEN clean_int(t."number_achieving") END) AS "Physics49_Grl_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'Physics' AND t."grade" = '9 to 5' AND t."sex" = 'Girls' THEN clean_int(t."number_achieving") END) AS "Physics59_Grl_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'Biology' AND t."grade" = '9 to 4' AND t."sex" = 'Total' THEN clean_int(t."number_achieving") END) AS "Bio49_Tot_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'Chemistry' AND t."grade" = '9 to 4' AND t."sex" = 'Total' THEN clean_int(t."number_achieving") END) AS "Chem49_Tot_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'Chemistry' AND t."grade" = '9 to 5' AND t."sex" = 'Total' THEN clean_int(t."number_achieving") END) AS "Chem59_Tot_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'Combined Science' AND t."grade" = '9 to 4' AND t."sex" = 'Total' THEN clean_int(t."number_achieving") END) AS "CombSci49_Tot_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'Combined Science' AND t."grade" = '9 to 5' AND t."sex" = 'Total' THEN clean_int(t."number_achieving") END) AS "CombSci59_Tot_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'English Language' AND t."grade" = '9 to 4' AND t."sex" = 'Total' THEN clean_int(t."number_achieving") END) AS "EngLang49_Tot_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'English Language' AND t."grade" = '9 to 5' AND t."sex" = 'Total' THEN clean_int(t."number_achieving") END) AS "EngLang59_Tot_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'English Literature' AND t."grade" = '9 to 4' AND t."sex" = 'Total' THEN clean_int(t."number_achieving") END) AS "EngLit49_Tot_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'English Literature' AND t."grade" = '9 to 5' AND t."sex" = 'Total' THEN clean_int(t."number_achieving") END) AS "EngLit59_Tot_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'Mathematics' AND t."grade" = '9 to 4' AND t."sex" = 'Total' THEN clean_int(t."number_achieving") END) AS "Maths49_Tot_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'Mathematics' AND t."grade" = '9 to 5' AND t."sex" = 'Total' THEN clean_int(t."number_achieving") END) AS "Maths59_Tot_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'Physics' AND t."grade" = '9 to 4' AND t."sex" = 'Total' THEN clean_int(t."number_achieving") END) AS "Physics49_Tot_LA_Current_Num",
        MAX(CASE WHEN t."subject" = 'Physics' AND t."grade" = '9 to 5' AND t."sex" = 'Total' THEN clean_int(t."number_achieving") END) AS "Physics59_Tot_LA_Current_Num"
    FROM raw_202425_subject_loc_9992c36c t
    GROUP BY t."old_la_code"
)

SELECT
    COALESCE(src_1."Id", src_2."Id", src_3."Id", src_4."Id", src_5."Id", src_6."Id") AS "Id",
    src_5."Attainment8_Boy_LA_Current_Num" AS "Attainment8_Boy_LA_Current_Num",
    src_2."Attainment8_Boy_LA_Previous_Num" AS "Attainment8_Boy_LA_Previous_Num",
    src_1."Attainment8_Boy_LA_Previous2_Num" AS "Attainment8_Boy_LA_Previous2_Num",
    src_5."Attainment8_Dis_LA_Current_Num" AS "Attainment8_Dis_LA_Current_Num",
    src_2."Attainment8_Dis_LA_Previous_Num" AS "Attainment8_Dis_LA_Previous_Num",
    src_1."Attainment8_Dis_LA_Previous2_Num" AS "Attainment8_Dis_LA_Previous2_Num",
    src_5."Attainment8_EAL_LA_Current_Num" AS "Attainment8_EAL_LA_Current_Num",
    src_2."Attainment8_EAL_LA_Previous_Num" AS "Attainment8_EAL_LA_Previous_Num",
    src_1."Attainment8_EAL_LA_Previous2_Num" AS "Attainment8_EAL_LA_Previous2_Num",
    src_5."Attainment8_Grl_LA_Current_Num" AS "Attainment8_Grl_LA_Current_Num",
    src_2."Attainment8_Grl_LA_Previous_Num" AS "Attainment8_Grl_LA_Previous_Num",
    src_1."Attainment8_Grl_LA_Previous2_Num" AS "Attainment8_Grl_LA_Previous2_Num",
    src_5."Attainment8_Mob_LA_Current_Num" AS "Attainment8_Mob_LA_Current_Num",
    src_5."Attainment8_NDi_LA_Current_Num" AS "Attainment8_NDi_LA_Current_Num",
    src_5."Attainment8_Tot_LA_Current_Num" AS "Attainment8_Tot_LA_Current_Num",
    src_2."Attainment8_Tot_LA_Previous_Num" AS "Attainment8_Tot_LA_Previous_Num",
    src_1."Attainment8_Tot_LA_Previous2_Num" AS "Attainment8_Tot_LA_Previous2_Num",
    src_6."Bio49_Boy_LA_Current_Num" AS "Bio49_Boy_LA_Current_Num",
    COALESCE(src_3."Bio49_Boy_LA_Previous_Num", src_4."Bio49_Boy_LA_Previous_Num") AS "Bio49_Boy_LA_Previous_Num",
    src_6."Bio49_Grl_LA_Current_Num" AS "Bio49_Grl_LA_Current_Num",
    COALESCE(src_3."Bio49_Grl_LA_Previous_Num", src_4."Bio49_Grl_LA_Previous_Num") AS "Bio49_Grl_LA_Previous_Num",
    src_6."Bio49_Tot_LA_Current_Num" AS "Bio49_Tot_LA_Current_Num",
    COALESCE(src_3."Bio49_Tot_LA_Previous_Num", src_4."Bio49_Tot_LA_Previous_Num") AS "Bio49_Tot_LA_Previous_Num",
    src_6."Chem49_Boy_LA_Current_Num" AS "Chem49_Boy_LA_Current_Num",
    COALESCE(src_3."Chem49_Boy_LA_Previous_Num", src_4."Chem49_Boy_LA_Previous_Num") AS "Chem49_Boy_LA_Previous_Num",
    src_6."Chem49_Grl_LA_Current_Num" AS "Chem49_Grl_LA_Current_Num",
    COALESCE(src_3."Chem49_Grl_LA_Previous_Num", src_4."Chem49_Grl_LA_Previous_Num") AS "Chem49_Grl_LA_Previous_Num",
    src_6."Chem49_Tot_LA_Current_Num" AS "Chem49_Tot_LA_Current_Num",
    COALESCE(src_3."Chem49_Tot_LA_Previous_Num", src_4."Chem49_Tot_LA_Previous_Num") AS "Chem49_Tot_LA_Previous_Num",
    src_6."Chem59_Boy_LA_Current_Num" AS "Chem59_Boy_LA_Current_Num",
    COALESCE(src_3."Chem59_Boy_LA_Previous_Num", src_4."Chem59_Boy_LA_Previous_Num") AS "Chem59_Boy_LA_Previous_Num",
    src_6."Chem59_Grl_LA_Current_Num" AS "Chem59_Grl_LA_Current_Num",
    COALESCE(src_3."Chem59_Grl_LA_Previous_Num", src_4."Chem59_Grl_LA_Previous_Num") AS "Chem59_Grl_LA_Previous_Num",
    src_6."Chem59_Tot_LA_Current_Num" AS "Chem59_Tot_LA_Current_Num",
    COALESCE(src_3."Chem59_Tot_LA_Previous_Num", src_4."Chem59_Tot_LA_Previous_Num") AS "Chem59_Tot_LA_Previous_Num",
    src_6."CombSci49_Boy_LA_Current_Num" AS "CombSci49_Boy_LA_Current_Num",
    COALESCE(src_3."CombSci49_Boy_LA_Previous_Num", src_4."CombSci49_Boy_LA_Previous_Num") AS "CombSci49_Boy_LA_Previous_Num",
    src_6."CombSci49_Grl_LA_Current_Num" AS "CombSci49_Grl_LA_Current_Num",
    COALESCE(src_3."CombSci49_Grl_LA_Previous_Num", src_4."CombSci49_Grl_LA_Previous_Num") AS "CombSci49_Grl_LA_Previous_Num",
    src_6."CombSci49_Tot_LA_Current_Num" AS "CombSci49_Tot_LA_Current_Num",
    COALESCE(src_3."CombSci49_Tot_LA_Previous_Num", src_4."CombSci49_Tot_LA_Previous_Num") AS "CombSci49_Tot_LA_Previous_Num",
    src_6."CombSci59_Boy_LA_Current_Num" AS "CombSci59_Boy_LA_Current_Num",
    COALESCE(src_3."CombSci59_Boy_LA_Previous_Num", src_4."CombSci59_Boy_LA_Previous_Num") AS "CombSci59_Boy_LA_Previous_Num",
    src_6."CombSci59_Grl_LA_Current_Num" AS "CombSci59_Grl_LA_Current_Num",
    COALESCE(src_3."CombSci59_Grl_LA_Previous_Num", src_4."CombSci59_Grl_LA_Previous_Num") AS "CombSci59_Grl_LA_Previous_Num",
    src_6."CombSci59_Tot_LA_Current_Num" AS "CombSci59_Tot_LA_Current_Num",
    COALESCE(src_3."CombSci59_Tot_LA_Previous_Num", src_4."CombSci59_Tot_LA_Previous_Num") AS "CombSci59_Tot_LA_Previous_Num",
    src_6."EngLang49_Boy_LA_Current_Num" AS "EngLang49_Boy_LA_Current_Num",
    COALESCE(src_3."EngLang49_Boy_LA_Previous_Num", src_4."EngLang49_Boy_LA_Previous_Num") AS "EngLang49_Boy_LA_Previous_Num",
    src_6."EngLang49_Grl_LA_Current_Num" AS "EngLang49_Grl_LA_Current_Num",
    COALESCE(src_3."EngLang49_Grl_LA_Previous_Num", src_4."EngLang49_Grl_LA_Previous_Num") AS "EngLang49_Grl_LA_Previous_Num",
    src_6."EngLang49_Tot_LA_Current_Num" AS "EngLang49_Tot_LA_Current_Num",
    COALESCE(src_3."EngLang49_Tot_LA_Previous_Num", src_4."EngLang49_Tot_LA_Previous_Num") AS "EngLang49_Tot_LA_Previous_Num",
    src_6."EngLang59_Boy_LA_Current_Num" AS "EngLang59_Boy_LA_Current_Num",
    COALESCE(src_3."EngLang59_Boy_LA_Previous_Num", src_4."EngLang59_Boy_LA_Previous_Num") AS "EngLang59_Boy_LA_Previous_Num",
    src_6."EngLang59_Grl_LA_Current_Num" AS "EngLang59_Grl_LA_Current_Num",
    COALESCE(src_3."EngLang59_Grl_LA_Previous_Num", src_4."EngLang59_Grl_LA_Previous_Num") AS "EngLang59_Grl_LA_Previous_Num",
    src_6."EngLang59_Tot_LA_Current_Num" AS "EngLang59_Tot_LA_Current_Num",
    COALESCE(src_3."EngLang59_Tot_LA_Previous_Num", src_4."EngLang59_Tot_LA_Previous_Num") AS "EngLang59_Tot_LA_Previous_Num",
    src_6."EngLit49_Boy_LA_Current_Num" AS "EngLit49_Boy_LA_Current_Num",
    COALESCE(src_3."EngLit49_Boy_LA_Previous_Num", src_4."EngLit49_Boy_LA_Previous_Num") AS "EngLit49_Boy_LA_Previous_Num",
    src_6."EngLit49_Grl_LA_Current_Num" AS "EngLit49_Grl_LA_Current_Num",
    COALESCE(src_3."EngLit49_Grl_LA_Previous_Num", src_4."EngLit49_Grl_LA_Previous_Num") AS "EngLit49_Grl_LA_Previous_Num",
    src_6."EngLit49_Tot_LA_Current_Num" AS "EngLit49_Tot_LA_Current_Num",
    COALESCE(src_3."EngLit49_Tot_LA_Previous_Num", src_4."EngLit49_Tot_LA_Previous_Num") AS "EngLit49_Tot_LA_Previous_Num",
    src_6."EngLit59_Boy_LA_Current_Num" AS "EngLit59_Boy_LA_Current_Num",
    COALESCE(src_3."EngLit59_Boy_LA_Previous_Num", src_4."EngLit59_Boy_LA_Previous_Num") AS "EngLit59_Boy_LA_Previous_Num",
    src_6."EngLit59_Grl_LA_Current_Num" AS "EngLit59_Grl_LA_Current_Num",
    COALESCE(src_3."EngLit59_Grl_LA_Previous_Num", src_4."EngLit59_Grl_LA_Previous_Num") AS "EngLit59_Grl_LA_Previous_Num",
    src_6."EngLit59_Tot_LA_Current_Num" AS "EngLit59_Tot_LA_Current_Num",
    COALESCE(src_3."EngLit59_Tot_LA_Previous_Num", src_4."EngLit59_Tot_LA_Previous_Num") AS "EngLit59_Tot_LA_Previous_Num",
    src_5."EngMaths49_Boy_LA_Current_Num" AS "EngMaths49_Boy_LA_Current_Num",
    src_5."EngMaths49_Boy_LA_Current_Pct" AS "EngMaths49_Boy_LA_Current_Pct",
    src_2."EngMaths49_Boy_LA_Previous_Num" AS "EngMaths49_Boy_LA_Previous_Num",
    src_2."EngMaths49_Boy_LA_Previous_Pct" AS "EngMaths49_Boy_LA_Previous_Pct",
    src_1."EngMaths49_Boy_LA_Previous2_Num" AS "EngMaths49_Boy_LA_Previous2_Num",
    src_1."EngMaths49_Boy_LA_Previous2_Pct" AS "EngMaths49_Boy_LA_Previous2_Pct",
    src_5."EngMaths49_Dis_LA_Current_Num" AS "EngMaths49_Dis_LA_Current_Num",
    src_5."EngMaths49_Dis_LA_Current_Pct" AS "EngMaths49_Dis_LA_Current_Pct",
    src_2."EngMaths49_Dis_LA_Previous_Num" AS "EngMaths49_Dis_LA_Previous_Num",
    src_2."EngMaths49_Dis_LA_Previous_Pct" AS "EngMaths49_Dis_LA_Previous_Pct",
    src_1."EngMaths49_Dis_LA_Previous2_Num" AS "EngMaths49_Dis_LA_Previous2_Num",
    src_1."EngMaths49_Dis_LA_Previous2_Pct" AS "EngMaths49_Dis_LA_Previous2_Pct",
    src_5."EngMaths49_EAL_LA_Current_Num" AS "EngMaths49_EAL_LA_Current_Num",
    src_5."EngMaths49_EAL_LA_Current_Pct" AS "EngMaths49_EAL_LA_Current_Pct",
    src_2."EngMaths49_EAL_LA_Previous_Num" AS "EngMaths49_EAL_LA_Previous_Num",
    src_2."EngMaths49_EAL_LA_Previous_Pct" AS "EngMaths49_EAL_LA_Previous_Pct",
    src_1."EngMaths49_EAL_LA_Previous2_Num" AS "EngMaths49_EAL_LA_Previous2_Num",
    src_1."EngMaths49_EAL_LA_Previous2_Pct" AS "EngMaths49_EAL_LA_Previous2_Pct",
    src_5."EngMaths49_Grl_LA_Current_Num" AS "EngMaths49_Grl_LA_Current_Num",
    src_5."EngMaths49_Grl_LA_Current_Pct" AS "EngMaths49_Grl_LA_Current_Pct",
    src_2."EngMaths49_Grl_LA_Previous_Num" AS "EngMaths49_Grl_LA_Previous_Num",
    src_2."EngMaths49_Grl_LA_Previous_Pct" AS "EngMaths49_Grl_LA_Previous_Pct",
    src_1."EngMaths49_Grl_LA_Previous2_Num" AS "EngMaths49_Grl_LA_Previous2_Num",
    src_1."EngMaths49_Grl_LA_Previous2_Pct" AS "EngMaths49_Grl_LA_Previous2_Pct",
    src_5."EngMaths49_Mob_LA_Current_Num" AS "EngMaths49_Mob_LA_Current_Num",
    src_5."EngMaths49_Mob_LA_Current_Pct" AS "EngMaths49_Mob_LA_Current_Pct",
    src_5."EngMaths49_NDi_LA_Current_Num" AS "EngMaths49_NDi_LA_Current_Num",
    src_5."EngMaths49_NDi_LA_Current_Pct" AS "EngMaths49_NDi_LA_Current_Pct",
    src_5."EngMaths49_Tot_LA_Current_Num" AS "EngMaths49_Tot_LA_Current_Num",
    src_5."EngMaths49_Tot_LA_Current_Pct" AS "EngMaths49_Tot_LA_Current_Pct",
    src_2."EngMaths49_Tot_LA_Previous_Num" AS "EngMaths49_Tot_LA_Previous_Num",
    src_2."EngMaths49_Tot_LA_Previous_Pct" AS "EngMaths49_Tot_LA_Previous_Pct",
    src_1."EngMaths49_Tot_LA_Previous2_Num" AS "EngMaths49_Tot_LA_Previous2_Num",
    src_1."EngMaths49_Tot_LA_Previous2_Pct" AS "EngMaths49_Tot_LA_Previous2_Pct",
    src_5."EngMaths59_Boy_LA_Current_Num" AS "EngMaths59_Boy_LA_Current_Num",
    src_5."EngMaths59_Boy_LA_Current_Pct" AS "EngMaths59_Boy_LA_Current_Pct",
    src_2."EngMaths59_Boy_LA_Previous_Num" AS "EngMaths59_Boy_LA_Previous_Num",
    src_2."EngMaths59_Boy_LA_Previous_Pct" AS "EngMaths59_Boy_LA_Previous_Pct",
    src_1."EngMaths59_Boy_LA_Previous2_Num" AS "EngMaths59_Boy_LA_Previous2_Num",
    src_1."EngMaths59_Boy_LA_Previous2_Pct" AS "EngMaths59_Boy_LA_Previous2_Pct",
    src_5."EngMaths59_Dis_LA_Current_Num" AS "EngMaths59_Dis_LA_Current_Num",
    src_5."EngMaths59_Dis_LA_Current_Pct" AS "EngMaths59_Dis_LA_Current_Pct",
    src_2."EngMaths59_Dis_LA_Previous_Num" AS "EngMaths59_Dis_LA_Previous_Num",
    src_2."EngMaths59_Dis_LA_Previous_Pct" AS "EngMaths59_Dis_LA_Previous_Pct",
    src_1."EngMaths59_Dis_LA_Previous2_Num" AS "EngMaths59_Dis_LA_Previous2_Num",
    src_1."EngMaths59_Dis_LA_Previous2_Pct" AS "EngMaths59_Dis_LA_Previous2_Pct",
    src_5."EngMaths59_EAL_LA_Current_Num" AS "EngMaths59_EAL_LA_Current_Num",
    src_5."EngMaths59_EAL_LA_Current_Pct" AS "EngMaths59_EAL_LA_Current_Pct",
    src_2."EngMaths59_EAL_LA_Previous_Num" AS "EngMaths59_EAL_LA_Previous_Num",
    src_2."EngMaths59_EAL_LA_Previous_Pct" AS "EngMaths59_EAL_LA_Previous_Pct",
    src_1."EngMaths59_EAL_LA_Previous2_Num" AS "EngMaths59_EAL_LA_Previous2_Num",
    src_1."EngMaths59_EAL_LA_Previous2_Pct" AS "EngMaths59_EAL_LA_Previous2_Pct",
    src_5."EngMaths59_Grl_LA_Current_Num" AS "EngMaths59_Grl_LA_Current_Num",
    src_5."EngMaths59_Grl_LA_Current_Pct" AS "EngMaths59_Grl_LA_Current_Pct",
    src_2."EngMaths59_Grl_LA_Previous_Num" AS "EngMaths59_Grl_LA_Previous_Num",
    src_2."EngMaths59_Grl_LA_Previous_Pct" AS "EngMaths59_Grl_LA_Previous_Pct",
    src_1."EngMaths59_Grl_LA_Previous2_Num" AS "EngMaths59_Grl_LA_Previous2_Num",
    src_1."EngMaths59_Grl_LA_Previous2_Pct" AS "EngMaths59_Grl_LA_Previous2_Pct",
    src_5."EngMaths59_Mob_LA_Current_Num" AS "EngMaths59_Mob_LA_Current_Num",
    src_5."EngMaths59_Mob_LA_Current_Pct" AS "EngMaths59_Mob_LA_Current_Pct",
    src_5."EngMaths59_NDi_LA_Current_Num" AS "EngMaths59_NDi_LA_Current_Num",
    src_5."EngMaths59_NDi_LA_Current_Pct" AS "EngMaths59_NDi_LA_Current_Pct",
    src_5."EngMaths59_Tot_LA_Current_Num" AS "EngMaths59_Tot_LA_Current_Num",
    src_5."EngMaths59_Tot_LA_Current_Pct" AS "EngMaths59_Tot_LA_Current_Pct",
    src_2."EngMaths59_Tot_LA_Previous_Num" AS "EngMaths59_Tot_LA_Previous_Num",
    src_2."EngMaths59_Tot_LA_Previous_Pct" AS "EngMaths59_Tot_LA_Previous_Pct",
    src_1."EngMaths59_Tot_LA_Previous2_Num" AS "EngMaths59_Tot_LA_Previous2_Num",
    src_1."EngMaths59_Tot_LA_Previous2_Pct" AS "EngMaths59_Tot_LA_Previous2_Pct",
    src_6."Maths49_Boy_LA_Current_Num" AS "Maths49_Boy_LA_Current_Num",
    COALESCE(src_3."Maths49_Boy_LA_Previous_Num", src_4."Maths49_Boy_LA_Previous_Num") AS "Maths49_Boy_LA_Previous_Num",
    src_6."Maths49_Grl_LA_Current_Num" AS "Maths49_Grl_LA_Current_Num",
    COALESCE(src_3."Maths49_Grl_LA_Previous_Num", src_4."Maths49_Grl_LA_Previous_Num") AS "Maths49_Grl_LA_Previous_Num",
    src_6."Maths49_Tot_LA_Current_Num" AS "Maths49_Tot_LA_Current_Num",
    COALESCE(src_3."Maths49_Tot_LA_Previous_Num", src_4."Maths49_Tot_LA_Previous_Num") AS "Maths49_Tot_LA_Previous_Num",
    src_6."Maths59_Boy_LA_Current_Num" AS "Maths59_Boy_LA_Current_Num",
    COALESCE(src_3."Maths59_Boy_LA_Previous_Num", src_4."Maths59_Boy_LA_Previous_Num") AS "Maths59_Boy_LA_Previous_Num",
    src_6."Maths59_Grl_LA_Current_Num" AS "Maths59_Grl_LA_Current_Num",
    COALESCE(src_3."Maths59_Grl_LA_Previous_Num", src_4."Maths59_Grl_LA_Previous_Num") AS "Maths59_Grl_LA_Previous_Num",
    src_6."Maths59_Tot_LA_Current_Num" AS "Maths59_Tot_LA_Current_Num",
    COALESCE(src_3."Maths59_Tot_LA_Previous_Num", src_4."Maths59_Tot_LA_Previous_Num") AS "Maths59_Tot_LA_Previous_Num",
    src_6."Physics49_Boy_LA_Current_Num" AS "Physics49_Boy_LA_Current_Num",
    COALESCE(src_3."Physics49_Boy_LA_Previous_Num", src_4."Physics49_Boy_LA_Previous_Num") AS "Physics49_Boy_LA_Previous_Num",
    src_6."Physics49_Grl_LA_Current_Num" AS "Physics49_Grl_LA_Current_Num",
    COALESCE(src_3."Physics49_Grl_LA_Previous_Num", src_4."Physics49_Grl_LA_Previous_Num") AS "Physics49_Grl_LA_Previous_Num",
    src_6."Physics49_Tot_LA_Current_Num" AS "Physics49_Tot_LA_Current_Num",
    COALESCE(src_3."Physics49_Tot_LA_Previous_Num", src_4."Physics49_Tot_LA_Previous_Num") AS "Physics49_Tot_LA_Previous_Num",
    src_6."Physics59_Boy_LA_Current_Num" AS "Physics59_Boy_LA_Current_Num",
    COALESCE(src_3."Physics59_Boy_LA_Previous_Num", src_4."Physics59_Boy_LA_Previous_Num") AS "Physics59_Boy_LA_Previous_Num",
    src_6."Physics59_Grl_LA_Current_Num" AS "Physics59_Grl_LA_Current_Num",
    COALESCE(src_3."Physics59_Grl_LA_Previous_Num", src_4."Physics59_Grl_LA_Previous_Num") AS "Physics59_Grl_LA_Previous_Num",
    src_6."Physics59_Tot_LA_Current_Num" AS "Physics59_Tot_LA_Current_Num",
    COALESCE(src_3."Physics59_Tot_LA_Previous_Num", src_4."Physics59_Tot_LA_Previous_Num") AS "Physics59_Tot_LA_Previous_Num",
    src_2."Prog8_Avg_LA_Previous_Num" AS "Prog8_Avg_LA_Previous_Num",
    src_2."Prog8_Avg_LA_Previous2_Num" AS "Prog8_Avg_LA_Previous2_Num"
FROM src_1
LEFT JOIN src_2 ON src_2."Id" = src_1."Id"
LEFT JOIN src_3 ON src_3."Id" = src_1."Id"
LEFT JOIN src_4 ON src_4."Id" = src_1."Id"
LEFT JOIN src_5 ON src_5."Id" = src_1."Id"
LEFT JOIN src_6 ON src_6."Id" = src_1."Id"
;
