-- AUTO-GENERATED MATERIALIZED VIEW: v_england_destinations

DROP MATERIALIZED VIEW IF EXISTS v_england_destinations;

CREATE MATERIALIZED VIEW v_england_destinations AS
WITH
src_1 AS (
    SELECT
        t."geographic_level" AS "Id",
        MAX(CASE WHEN (t."breakdown" = 'Male') AND (t."data_type" = 'Number of Students') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."overall" END) AS "AllDest_Boy_Eng_Current_Num",
        MAX(CASE WHEN (t."breakdown" = 'Male') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."overall" END) AS "AllDest_Boy_Eng_Current_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Disadvantaged') AND (t."data_type" = 'Number of Students') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."overall" END) AS "AllDest_Dis_Eng_Current_Num",
        MAX(CASE WHEN (t."breakdown" = 'Disadvantaged') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."overall" END) AS "AllDest_Dis_Eng_Current_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Female') AND (t."data_type" = 'Number of Students') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."overall" END) AS "AllDest_Grl_Eng_Current_Num",
        MAX(CASE WHEN (t."breakdown" = 'Female') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."overall" END) AS "AllDest_Grl_Eng_Current_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Not disadvantaged') AND (t."data_type" = 'Number of Students') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."overall" END) AS "AllDest_NDi_Eng_Current_Num",
        MAX(CASE WHEN (t."breakdown" = 'Not disadvantaged') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."overall" END) AS "AllDest_NDi_Eng_Current_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Total') AND (t."data_type" = 'Number of Students') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."overall" END) AS "AllDest_Tot_Eng_Current_Num",
        MAX(CASE WHEN (t."breakdown" = 'Total') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."overall" END) AS "AllDest_Tot_Eng_Current_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Male') AND (t."data_type" = 'Number of Students') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."education" END) AS "Education_Boy_Eng_Current_Num",
        MAX(CASE WHEN (t."breakdown" = 'Male') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."education" END) AS "Education_Boy_Eng_Current_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Disadvantaged') AND (t."data_type" = 'Number of Students') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."education" END) AS "Education_Dis_Eng_Current_Num",
        MAX(CASE WHEN (t."breakdown" = 'Disadvantaged') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."education" END) AS "Education_Dis_Eng_Current_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Female') AND (t."data_type" = 'Number of Students') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."education" END) AS "Education_Grl_Eng_Current_Num",
        MAX(CASE WHEN (t."breakdown" = 'Female') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."education" END) AS "Education_Grl_Eng_Current_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Not disadvantaged') AND (t."data_type" = 'Number of Students') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."education" END) AS "Education_NDi_Eng_Current_Num",
        MAX(CASE WHEN (t."breakdown" = 'Not disadvantaged') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."education" END) AS "Education_NDi_Eng_Current_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Total') AND (t."data_type" = 'Number of Students') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."education" END) AS "Education_Tot_Eng_Current_Num",
        MAX(CASE WHEN (t."breakdown" = 'Total') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."education" END) AS "Education_Tot_Eng_Current_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Male') AND (t."data_type" = 'Number of Students') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."all_work" END) AS "Employment_Boy_Eng_Current_Num",
        MAX(CASE WHEN (t."breakdown" = 'Male') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."all_work" END) AS "Employment_Boy_Eng_Current_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Disadvantaged') AND (t."data_type" = 'Number of Students') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."all_work" END) AS "Employment_Dis_Eng_Current_Num",
        MAX(CASE WHEN (t."breakdown" = 'Disadvantaged') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."all_work" END) AS "Employment_Dis_Eng_Current_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Female') AND (t."data_type" = 'Number of Students') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."all_work" END) AS "Employment_Grl_Eng_Current_Num",
        MAX(CASE WHEN (t."breakdown" = 'Female') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."all_work" END) AS "Employment_Grl_Eng_Current_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Not disadvantaged') AND (t."data_type" = 'Number of Students') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."all_work" END) AS "Employment_NDi_Eng_Current_Num",
        MAX(CASE WHEN (t."breakdown" = 'Not disadvantaged') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."all_work" END) AS "Employment_NDi_Eng_Current_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Total') AND (t."data_type" = 'Number of Students') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."all_work" END) AS "Employment_Tot_Eng_Current_Num",
        MAX(CASE WHEN (t."breakdown" = 'Total') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."all_work" END) AS "Employment_Tot_Eng_Current_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Male') AND (t."data_type" = 'Number of Students') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."appren" END) AS "Apprentice_Boy_Eng_Current_Num",
        MAX(CASE WHEN (t."breakdown" = 'Male') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."appren" END) AS "Apprentice_Boy_Eng_Current_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Disadvantaged') AND (t."data_type" = 'Number of Students') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."appren" END) AS "Apprentice_Dis_Eng_Current_Num",
        MAX(CASE WHEN (t."breakdown" = 'Disadvantaged') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."appren" END) AS "Apprentice_Dis_Eng_Current_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Female') AND (t."data_type" = 'Number of Students') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."appren" END) AS "Apprentice_Grl_Eng_Current_Num",
        MAX(CASE WHEN (t."breakdown" = 'Female') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."appren" END) AS "Apprentice_Grl_Eng_Current_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Not disadvantaged') AND (t."data_type" = 'Number of Students') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."appren" END) AS "Apprentice_NDi_Eng_Current_Num",
        MAX(CASE WHEN (t."breakdown" = 'Not disadvantaged') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."appren" END) AS "Apprentice_NDi_Eng_Current_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Total') AND (t."data_type" = 'Number of Students') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."appren" END) AS "Apprentice_Tot_Eng_Current_Num",
        MAX(CASE WHEN (t."breakdown" = 'Total') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'Total state-funded mainstream and special') AND (t."time_period" = '202223') THEN t."appren" END) AS "Apprentice_Tot_Eng_Current_Pct"
    FROM t_ees_ks4_nat_202223_6f188ec9e6 t
    GROUP BY t."geographic_level"
)
,
src_2 AS (
    SELECT
        t."geographic_level" AS "Id",
        MAX(CASE WHEN (t."breakdown" = 'Male') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."overall" END) AS "AllDest_Boy_Eng_Previous_Num",
        MAX(CASE WHEN (t."breakdown" = 'Male') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."overall" END) AS "AllDest_Boy_Eng_Previous_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Disadvantaged') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."overall" END) AS "AllDest_Dis_Eng_Previous_Num",
        MAX(CASE WHEN (t."breakdown" = 'Disadvantaged') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."overall" END) AS "AllDest_Dis_Eng_Previous_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Female') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."overall" END) AS "AllDest_Grl_Eng_Previous_Num",
        MAX(CASE WHEN (t."breakdown" = 'Female') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."overall" END) AS "AllDest_Grl_Eng_Previous_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Not disadvantaged') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."overall" END) AS "AllDest_NDi_Eng_Previous_Num",
        MAX(CASE WHEN (t."breakdown" = 'Not disadvantaged') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."overall" END) AS "AllDest_NDi_Eng_Previous_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Total') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') AND (t."breakdown_topic" = 'Total') THEN t."overall" END) AS "AllDest_Tot_Eng_Previous_Num",
        MAX(CASE WHEN (t."breakdown" = 'Total') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') AND (t."breakdown_topic" = 'Total') THEN t."overall" END) AS "AllDest_Tot_Eng_Previous_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Male') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."education" END) AS "Education_Boy_Eng_Previous_Num",
        MAX(CASE WHEN (t."breakdown" = 'Male') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."education" END) AS "Education_Boy_Eng_Previous_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Disadvantaged') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."education" END) AS "Education_Dis_Eng_Previous_Num",
        MAX(CASE WHEN (t."breakdown" = 'Disadvantaged') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."education" END) AS "Education_Dis_Eng_Previous_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Female') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."education" END) AS "Education_Grl_Eng_Previous_Num",
        MAX(CASE WHEN (t."breakdown" = 'Female') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."education" END) AS "Education_Grl_Eng_Previous_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Not disadvantaged') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."education" END) AS "Education_NDi_Eng_Previous_Num",
        MAX(CASE WHEN (t."breakdown" = 'Not disadvantaged') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."education" END) AS "Education_NDi_Eng_Previous_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Total') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') AND (t."breakdown_topic" = 'Total') THEN t."education" END) AS "Education_Tot_Eng_Previous_Num",
        MAX(CASE WHEN (t."breakdown" = 'Total') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') AND (t."breakdown_topic" = 'Total') THEN t."education" END) AS "Education_Tot_Eng_Previous_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Male') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."all_work" END) AS "Employment_Boy_Eng_Previous_Num",
        MAX(CASE WHEN (t."breakdown" = 'Male') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."all_work" END) AS "Employment_Boy_Eng_Previous_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Disadvantaged') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."all_work" END) AS "Employment_Dis_Eng_Previous_Num",
        MAX(CASE WHEN (t."breakdown" = 'Disadvantaged') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."all_work" END) AS "Employment_Dis_Eng_Previous_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Female') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."all_work" END) AS "Employment_Grl_Eng_Previous_Num",
        MAX(CASE WHEN (t."breakdown" = 'Female') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."all_work" END) AS "Employment_Grl_Eng_Previous_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Not disadvantaged') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."all_work" END) AS "Employment_NDi_Eng_Previous_Num",
        MAX(CASE WHEN (t."breakdown" = 'Not disadvantaged') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."all_work" END) AS "Employment_NDi_Eng_Previous_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Total') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') AND (t."breakdown_topic" = 'Total') THEN t."all_work" END) AS "Employment_Tot_Eng_Previous_Num",
        MAX(CASE WHEN (t."breakdown" = 'Total') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') AND (t."breakdown_topic" = 'Total') THEN t."all_work" END) AS "Employment_Tot_Eng_Previous_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Male') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."appren" END) AS "Apprentice_Boy_Eng_Previous_Num",
        MAX(CASE WHEN (t."breakdown" = 'Male') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."appren" END) AS "Apprentice_Boy_Eng_Previous_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Disadvantaged') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."appren" END) AS "Apprentice_Dis_Eng_Previous_Num",
        MAX(CASE WHEN (t."breakdown" = 'Disadvantaged') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."appren" END) AS "Apprentice_Dis_Eng_Previous_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Female') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."appren" END) AS "Apprentice_Grl_Eng_Previous_Num",
        MAX(CASE WHEN (t."breakdown" = 'Female') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."appren" END) AS "Apprentice_Grl_Eng_Previous_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Not disadvantaged') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."appren" END) AS "Apprentice_NDi_Eng_Previous_Num",
        MAX(CASE WHEN (t."breakdown" = 'Not disadvantaged') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') THEN t."appren" END) AS "Apprentice_NDi_Eng_Previous_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Total') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') AND (t."breakdown_topic" = 'Total') THEN t."appren" END) AS "Apprentice_Tot_Eng_Previous_Num",
        MAX(CASE WHEN (t."breakdown" = 'Total') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202223') AND (t."breakdown_topic" = 'Total') THEN t."appren" END) AS "Apprentice_Tot_Eng_Previous_Pct"
    FROM t_ks4_dm_ud_202223_nat_8dfd44c9f0 t
    GROUP BY t."geographic_level"
)
,
src_3 AS (
    SELECT
        t."geographic_level" AS "Id",
        MAX(CASE WHEN (t."breakdown" = 'Male') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Gender') THEN t."overall" END) AS "AllDest_Boy_Eng_Previous2_Num",
        MAX(CASE WHEN (t."breakdown" = 'Male') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Gender') THEN t."overall" END) AS "AllDest_Boy_Eng_Previous2_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Disadvantaged') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Disadvantage Status') THEN t."overall" END) AS "AllDest_Dis_Eng_Previous2_Num",
        MAX(CASE WHEN (t."breakdown" = 'Disadvantaged') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Disadvantage Status') THEN t."overall" END) AS "AllDest_Dis_Eng_Previous2_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Female') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Gender') THEN t."overall" END) AS "AllDest_Grl_Eng_Previous2_Num",
        MAX(CASE WHEN (t."breakdown" = 'Female') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Gender') THEN t."overall" END) AS "AllDest_Grl_Eng_Previous2_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Not disadvantaged') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Disadvantage Status') THEN t."overall" END) AS "AllDest_NDi_Eng_Previous2_Num",
        MAX(CASE WHEN (t."breakdown" = 'Not disadvantaged') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Disadvantage Status') THEN t."overall" END) AS "AllDest_NDi_Eng_Previous2_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Total') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Total') THEN t."overall" END) AS "AllDest_Tot_Eng_Previous2_Num",
        MAX(CASE WHEN (t."breakdown" = 'Total') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Total') THEN t."overall" END) AS "AllDest_Tot_Eng_Previous2_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Male') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Gender') THEN t."education" END) AS "Education_Boy_Eng_Previous2_Num",
        MAX(CASE WHEN (t."breakdown" = 'Male') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Gender') THEN t."education" END) AS "Education_Boy_Eng_Previous2_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Disadvantaged') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Disadvantage Status') THEN t."education" END) AS "Education_Dis_Eng_Previous2_Num",
        MAX(CASE WHEN (t."breakdown" = 'Disadvantaged') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Disadvantage Status') THEN t."education" END) AS "Education_Dis_Eng_Previous2_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Female') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Gender') THEN t."education" END) AS "Education_Grl_Eng_Previous2_Num",
        MAX(CASE WHEN (t."breakdown" = 'Female') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Gender') THEN t."education" END) AS "Education_Grl_Eng_Previous2_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Not disadvantaged') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Disadvantage Status') THEN t."education" END) AS "Education_NDi_Eng_Previous2_Num",
        MAX(CASE WHEN (t."breakdown" = 'Not disadvantaged') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Disadvantage Status') THEN t."education" END) AS "Education_NDi_Eng_Previous2_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Total') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Total') THEN t."education" END) AS "Education_Tot_Eng_Previous2_Num",
        MAX(CASE WHEN (t."breakdown" = 'Total') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Total') THEN t."education" END) AS "Education_Tot_Eng_Previous2_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Male') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Gender') THEN t."all_work" END) AS "Employment_Boy_Eng_Previous2_Num",
        MAX(CASE WHEN (t."breakdown" = 'Male') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Gender') THEN t."all_work" END) AS "Employment_Boy_Eng_Previous2_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Disadvantaged') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Disadvantage Status') THEN t."all_work" END) AS "Employment_Dis_Eng_Previous2_Num",
        MAX(CASE WHEN (t."breakdown" = 'Disadvantaged') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Disadvantage Status') THEN t."all_work" END) AS "Employment_Dis_Eng_Previous2_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Female') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Gender') THEN t."all_work" END) AS "Employment_Grl_Eng_Previous2_Num",
        MAX(CASE WHEN (t."breakdown" = 'Female') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Gender') THEN t."all_work" END) AS "Employment_Grl_Eng_Previous2_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Not disadvantaged') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Disadvantage Status') THEN t."all_work" END) AS "Employment_NDi_Eng_Previous2_Num",
        MAX(CASE WHEN (t."breakdown" = 'Not disadvantaged') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Disadvantage Status') THEN t."all_work" END) AS "Employment_NDi_Eng_Previous2_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Total') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Total') THEN t."all_work" END) AS "Employment_Tot_Eng_Previous2_Num",
        MAX(CASE WHEN (t."breakdown" = 'Total') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Total') THEN t."all_work" END) AS "Employment_Tot_Eng_Previous2_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Male') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Gender') THEN t."appren" END) AS "Apprentice_Boy_Eng_Previous2_Num",
        MAX(CASE WHEN (t."breakdown" = 'Male') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Gender') THEN t."appren" END) AS "Apprentice_Boy_Eng_Previous2_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Disadvantaged') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Disadvantage Status') THEN t."appren" END) AS "Apprentice_Dis_Eng_Previous2_Num",
        MAX(CASE WHEN (t."breakdown" = 'Disadvantaged') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Disadvantage Status') THEN t."appren" END) AS "Apprentice_Dis_Eng_Previous2_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Female') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Gender') THEN t."appren" END) AS "Apprentice_Grl_Eng_Previous2_Num",
        MAX(CASE WHEN (t."breakdown" = 'Female') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Gender') THEN t."appren" END) AS "Apprentice_Grl_Eng_Previous2_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Not disadvantaged') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Disadvantage Status') THEN t."appren" END) AS "Apprentice_NDi_Eng_Previous2_Num",
        MAX(CASE WHEN (t."breakdown" = 'Not disadvantaged') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Disadvantage Status') THEN t."appren" END) AS "Apprentice_NDi_Eng_Previous2_Pct",
        MAX(CASE WHEN (t."breakdown" = 'Total') AND (t."data_type" = 'Number of pupils') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Total') THEN t."appren" END) AS "Apprentice_Tot_Eng_Previous2_Num",
        MAX(CASE WHEN (t."breakdown" = 'Total') AND (t."data_type" = 'Percentage') AND (t."institution_group" = 'State-funded mainstream & special schools') AND (t."time_period" = '202122') AND (t."breakdown_topic" = 'Total') THEN t."appren" END) AS "Apprentice_Tot_Eng_Previous2_Pct"
    FROM t_ks4_dm_ud_202122_nat_e9fce4c692 t
    GROUP BY t."geographic_level"
)
,
all_ids AS (
    SELECT "Id" FROM src_1
    UNION SELECT "Id" FROM src_2
    UNION SELECT "Id" FROM src_3
)

SELECT
    a."Id" AS "Id",
    src_1."AllDest_Boy_Eng_Current_Num" AS "AllDest_Boy_Eng_Current_Num",
    src_1."AllDest_Boy_Eng_Current_Pct" AS "AllDest_Boy_Eng_Current_Pct",
    src_2."AllDest_Boy_Eng_Previous_Num" AS "AllDest_Boy_Eng_Previous_Num",
    src_2."AllDest_Boy_Eng_Previous_Pct" AS "AllDest_Boy_Eng_Previous_Pct",
    src_3."AllDest_Boy_Eng_Previous2_Num" AS "AllDest_Boy_Eng_Previous2_Num",
    src_3."AllDest_Boy_Eng_Previous2_Pct" AS "AllDest_Boy_Eng_Previous2_Pct",
    src_1."AllDest_Dis_Eng_Current_Num" AS "AllDest_Dis_Eng_Current_Num",
    src_1."AllDest_Dis_Eng_Current_Pct" AS "AllDest_Dis_Eng_Current_Pct",
    src_2."AllDest_Dis_Eng_Previous_Num" AS "AllDest_Dis_Eng_Previous_Num",
    src_2."AllDest_Dis_Eng_Previous_Pct" AS "AllDest_Dis_Eng_Previous_Pct",
    src_3."AllDest_Dis_Eng_Previous2_Num" AS "AllDest_Dis_Eng_Previous2_Num",
    src_3."AllDest_Dis_Eng_Previous2_Pct" AS "AllDest_Dis_Eng_Previous2_Pct",
    src_1."AllDest_Grl_Eng_Current_Num" AS "AllDest_Grl_Eng_Current_Num",
    src_1."AllDest_Grl_Eng_Current_Pct" AS "AllDest_Grl_Eng_Current_Pct",
    src_2."AllDest_Grl_Eng_Previous_Num" AS "AllDest_Grl_Eng_Previous_Num",
    src_2."AllDest_Grl_Eng_Previous_Pct" AS "AllDest_Grl_Eng_Previous_Pct",
    src_3."AllDest_Grl_Eng_Previous2_Num" AS "AllDest_Grl_Eng_Previous2_Num",
    src_3."AllDest_Grl_Eng_Previous2_Pct" AS "AllDest_Grl_Eng_Previous2_Pct",
    src_1."AllDest_NDi_Eng_Current_Num" AS "AllDest_NDi_Eng_Current_Num",
    src_1."AllDest_NDi_Eng_Current_Pct" AS "AllDest_NDi_Eng_Current_Pct",
    src_2."AllDest_NDi_Eng_Previous_Num" AS "AllDest_NDi_Eng_Previous_Num",
    src_2."AllDest_NDi_Eng_Previous_Pct" AS "AllDest_NDi_Eng_Previous_Pct",
    src_3."AllDest_NDi_Eng_Previous2_Num" AS "AllDest_NDi_Eng_Previous2_Num",
    src_3."AllDest_NDi_Eng_Previous2_Pct" AS "AllDest_NDi_Eng_Previous2_Pct",
    src_1."AllDest_Tot_Eng_Current_Num" AS "AllDest_Tot_Eng_Current_Num",
    src_1."AllDest_Tot_Eng_Current_Pct" AS "AllDest_Tot_Eng_Current_Pct",
    src_2."AllDest_Tot_Eng_Previous_Num" AS "AllDest_Tot_Eng_Previous_Num",
    src_2."AllDest_Tot_Eng_Previous_Pct" AS "AllDest_Tot_Eng_Previous_Pct",
    src_3."AllDest_Tot_Eng_Previous2_Num" AS "AllDest_Tot_Eng_Previous2_Num",
    src_3."AllDest_Tot_Eng_Previous2_Pct" AS "AllDest_Tot_Eng_Previous2_Pct",
    src_1."Apprentice_Boy_Eng_Current_Num" AS "Apprentice_Boy_Eng_Current_Num",
    src_1."Apprentice_Boy_Eng_Current_Pct" AS "Apprentice_Boy_Eng_Current_Pct",
    src_2."Apprentice_Boy_Eng_Previous_Num" AS "Apprentice_Boy_Eng_Previous_Num",
    src_2."Apprentice_Boy_Eng_Previous_Pct" AS "Apprentice_Boy_Eng_Previous_Pct",
    src_3."Apprentice_Boy_Eng_Previous2_Num" AS "Apprentice_Boy_Eng_Previous2_Num",
    src_3."Apprentice_Boy_Eng_Previous2_Pct" AS "Apprentice_Boy_Eng_Previous2_Pct",
    src_1."Apprentice_Dis_Eng_Current_Num" AS "Apprentice_Dis_Eng_Current_Num",
    src_1."Apprentice_Dis_Eng_Current_Pct" AS "Apprentice_Dis_Eng_Current_Pct",
    src_2."Apprentice_Dis_Eng_Previous_Num" AS "Apprentice_Dis_Eng_Previous_Num",
    src_2."Apprentice_Dis_Eng_Previous_Pct" AS "Apprentice_Dis_Eng_Previous_Pct",
    src_3."Apprentice_Dis_Eng_Previous2_Num" AS "Apprentice_Dis_Eng_Previous2_Num",
    src_3."Apprentice_Dis_Eng_Previous2_Pct" AS "Apprentice_Dis_Eng_Previous2_Pct",
    src_1."Apprentice_Grl_Eng_Current_Num" AS "Apprentice_Grl_Eng_Current_Num",
    src_1."Apprentice_Grl_Eng_Current_Pct" AS "Apprentice_Grl_Eng_Current_Pct",
    src_2."Apprentice_Grl_Eng_Previous_Num" AS "Apprentice_Grl_Eng_Previous_Num",
    src_2."Apprentice_Grl_Eng_Previous_Pct" AS "Apprentice_Grl_Eng_Previous_Pct",
    src_3."Apprentice_Grl_Eng_Previous2_Num" AS "Apprentice_Grl_Eng_Previous2_Num",
    src_3."Apprentice_Grl_Eng_Previous2_Pct" AS "Apprentice_Grl_Eng_Previous2_Pct",
    src_1."Apprentice_NDi_Eng_Current_Num" AS "Apprentice_NDi_Eng_Current_Num",
    src_1."Apprentice_NDi_Eng_Current_Pct" AS "Apprentice_NDi_Eng_Current_Pct",
    src_2."Apprentice_NDi_Eng_Previous_Num" AS "Apprentice_NDi_Eng_Previous_Num",
    src_2."Apprentice_NDi_Eng_Previous_Pct" AS "Apprentice_NDi_Eng_Previous_Pct",
    src_3."Apprentice_NDi_Eng_Previous2_Num" AS "Apprentice_NDi_Eng_Previous2_Num",
    src_3."Apprentice_NDi_Eng_Previous2_Pct" AS "Apprentice_NDi_Eng_Previous2_Pct",
    src_1."Apprentice_Tot_Eng_Current_Num" AS "Apprentice_Tot_Eng_Current_Num",
    src_1."Apprentice_Tot_Eng_Current_Pct" AS "Apprentice_Tot_Eng_Current_Pct",
    src_2."Apprentice_Tot_Eng_Previous_Num" AS "Apprentice_Tot_Eng_Previous_Num",
    src_2."Apprentice_Tot_Eng_Previous_Pct" AS "Apprentice_Tot_Eng_Previous_Pct",
    src_3."Apprentice_Tot_Eng_Previous2_Num" AS "Apprentice_Tot_Eng_Previous2_Num",
    src_3."Apprentice_Tot_Eng_Previous2_Pct" AS "Apprentice_Tot_Eng_Previous2_Pct",
    src_1."Education_Boy_Eng_Current_Num" AS "Education_Boy_Eng_Current_Num",
    src_1."Education_Boy_Eng_Current_Pct" AS "Education_Boy_Eng_Current_Pct",
    src_2."Education_Boy_Eng_Previous_Num" AS "Education_Boy_Eng_Previous_Num",
    src_2."Education_Boy_Eng_Previous_Pct" AS "Education_Boy_Eng_Previous_Pct",
    src_3."Education_Boy_Eng_Previous2_Num" AS "Education_Boy_Eng_Previous2_Num",
    src_3."Education_Boy_Eng_Previous2_Pct" AS "Education_Boy_Eng_Previous2_Pct",
    src_1."Education_Dis_Eng_Current_Num" AS "Education_Dis_Eng_Current_Num",
    src_1."Education_Dis_Eng_Current_Pct" AS "Education_Dis_Eng_Current_Pct",
    src_2."Education_Dis_Eng_Previous_Num" AS "Education_Dis_Eng_Previous_Num",
    src_2."Education_Dis_Eng_Previous_Pct" AS "Education_Dis_Eng_Previous_Pct",
    src_3."Education_Dis_Eng_Previous2_Num" AS "Education_Dis_Eng_Previous2_Num",
    src_3."Education_Dis_Eng_Previous2_Pct" AS "Education_Dis_Eng_Previous2_Pct",
    src_1."Education_Grl_Eng_Current_Num" AS "Education_Grl_Eng_Current_Num",
    src_1."Education_Grl_Eng_Current_Pct" AS "Education_Grl_Eng_Current_Pct",
    src_2."Education_Grl_Eng_Previous_Num" AS "Education_Grl_Eng_Previous_Num",
    src_2."Education_Grl_Eng_Previous_Pct" AS "Education_Grl_Eng_Previous_Pct",
    src_3."Education_Grl_Eng_Previous2_Num" AS "Education_Grl_Eng_Previous2_Num",
    src_3."Education_Grl_Eng_Previous2_Pct" AS "Education_Grl_Eng_Previous2_Pct",
    src_1."Education_NDi_Eng_Current_Num" AS "Education_NDi_Eng_Current_Num",
    src_1."Education_NDi_Eng_Current_Pct" AS "Education_NDi_Eng_Current_Pct",
    src_2."Education_NDi_Eng_Previous_Num" AS "Education_NDi_Eng_Previous_Num",
    src_2."Education_NDi_Eng_Previous_Pct" AS "Education_NDi_Eng_Previous_Pct",
    src_3."Education_NDi_Eng_Previous2_Num" AS "Education_NDi_Eng_Previous2_Num",
    src_3."Education_NDi_Eng_Previous2_Pct" AS "Education_NDi_Eng_Previous2_Pct",
    src_1."Education_Tot_Eng_Current_Num" AS "Education_Tot_Eng_Current_Num",
    src_1."Education_Tot_Eng_Current_Pct" AS "Education_Tot_Eng_Current_Pct",
    src_2."Education_Tot_Eng_Previous_Num" AS "Education_Tot_Eng_Previous_Num",
    src_2."Education_Tot_Eng_Previous_Pct" AS "Education_Tot_Eng_Previous_Pct",
    src_3."Education_Tot_Eng_Previous2_Num" AS "Education_Tot_Eng_Previous2_Num",
    src_3."Education_Tot_Eng_Previous2_Pct" AS "Education_Tot_Eng_Previous2_Pct",
    src_1."Employment_Boy_Eng_Current_Num" AS "Employment_Boy_Eng_Current_Num",
    src_1."Employment_Boy_Eng_Current_Pct" AS "Employment_Boy_Eng_Current_Pct",
    src_2."Employment_Boy_Eng_Previous_Num" AS "Employment_Boy_Eng_Previous_Num",
    src_2."Employment_Boy_Eng_Previous_Pct" AS "Employment_Boy_Eng_Previous_Pct",
    src_3."Employment_Boy_Eng_Previous2_Num" AS "Employment_Boy_Eng_Previous2_Num",
    src_3."Employment_Boy_Eng_Previous2_Pct" AS "Employment_Boy_Eng_Previous2_Pct",
    src_1."Employment_Dis_Eng_Current_Num" AS "Employment_Dis_Eng_Current_Num",
    src_1."Employment_Dis_Eng_Current_Pct" AS "Employment_Dis_Eng_Current_Pct",
    src_2."Employment_Dis_Eng_Previous_Num" AS "Employment_Dis_Eng_Previous_Num",
    src_2."Employment_Dis_Eng_Previous_Pct" AS "Employment_Dis_Eng_Previous_Pct",
    src_3."Employment_Dis_Eng_Previous2_Num" AS "Employment_Dis_Eng_Previous2_Num",
    src_3."Employment_Dis_Eng_Previous2_Pct" AS "Employment_Dis_Eng_Previous2_Pct",
    src_1."Employment_Grl_Eng_Current_Num" AS "Employment_Grl_Eng_Current_Num",
    src_1."Employment_Grl_Eng_Current_Pct" AS "Employment_Grl_Eng_Current_Pct",
    src_2."Employment_Grl_Eng_Previous_Num" AS "Employment_Grl_Eng_Previous_Num",
    src_2."Employment_Grl_Eng_Previous_Pct" AS "Employment_Grl_Eng_Previous_Pct",
    src_3."Employment_Grl_Eng_Previous2_Num" AS "Employment_Grl_Eng_Previous2_Num",
    src_3."Employment_Grl_Eng_Previous2_Pct" AS "Employment_Grl_Eng_Previous2_Pct",
    src_1."Employment_NDi_Eng_Current_Num" AS "Employment_NDi_Eng_Current_Num",
    src_1."Employment_NDi_Eng_Current_Pct" AS "Employment_NDi_Eng_Current_Pct",
    src_2."Employment_NDi_Eng_Previous_Num" AS "Employment_NDi_Eng_Previous_Num",
    src_2."Employment_NDi_Eng_Previous_Pct" AS "Employment_NDi_Eng_Previous_Pct",
    src_3."Employment_NDi_Eng_Previous2_Num" AS "Employment_NDi_Eng_Previous2_Num",
    src_3."Employment_NDi_Eng_Previous2_Pct" AS "Employment_NDi_Eng_Previous2_Pct",
    src_1."Employment_Tot_Eng_Current_Num" AS "Employment_Tot_Eng_Current_Num",
    src_1."Employment_Tot_Eng_Current_Pct" AS "Employment_Tot_Eng_Current_Pct",
    src_2."Employment_Tot_Eng_Previous_Num" AS "Employment_Tot_Eng_Previous_Num",
    src_2."Employment_Tot_Eng_Previous_Pct" AS "Employment_Tot_Eng_Previous_Pct",
    src_3."Employment_Tot_Eng_Previous2_Num" AS "Employment_Tot_Eng_Previous2_Num",
    src_3."Employment_Tot_Eng_Previous2_Pct" AS "Employment_Tot_Eng_Previous2_Pct"
FROM all_ids a
LEFT JOIN src_1 ON src_1."Id" = a."Id"
LEFT JOIN src_2 ON src_2."Id" = a."Id"
LEFT JOIN src_3 ON src_3."Id" = a."Id"
;
