using Newtonsoft.Json;
using System.Text;

namespace SapSec.ModelGenerator;

public class Program
{
    public static async Task Main(string[] args)
    {
        string baseDir = FindProjectDirectoryDownwards("SapSec.ModelGenerator");
        string jsonDir = Path.Combine(baseDir, "..\\SAPSec.Infrastructure\\Data\\Files\\Generated");
        string csDir = Path.Combine(baseDir, "..\\SAPSec.Core\\Model\\Generated");

        foreach (var csFile in Directory.GetFiles(csDir))
        {
            File.Delete(csFile);
        }

        foreach (var jsonFile in Directory.GetFiles(jsonDir))
        {
            var fileName = new FileInfo(jsonFile).Name;

            if (fileName == "placeholder.txt")
            {
                continue;
            }

            Console.WriteLine($"Deserializing {jsonFile} ...");

            try
            {
                var json = await File.ReadAllTextAsync(jsonFile);
                var list = JsonConvert.DeserializeObject<List<Dictionary<string, object?>>>(json);

                var first = list?.FirstOrDefault();

                if (first is null)
                {
                    Console.WriteLine($"File {fileName} was empty.");
                    continue;
                }

                StringBuilder cs = new StringBuilder();
                var className = fileName.Replace(".json", "");

                cs.AppendLine("// This file is automatically generated by SAPSec.ModelGenerator.");
                cs.AppendLine("// Please do not manually edit this file or your changes will be lost when the file is regenerated.");
                cs.AppendLine();
                cs.AppendLine("using System.Diagnostics.CodeAnalysis;");
                cs.AppendLine();
                cs.AppendLine("namespace SAPSec.Core.Model.Generated");
                cs.AppendLine("{");
                cs.AppendLine("    [ExcludeFromCodeCoverage]");
                cs.AppendLine($"    public class {className}");
                cs.AppendLine("    {");

                foreach (var (key, value) in first)
                {
                    var (type, deflt) = value switch
                    {
                        int or long => ("int?", "null"),
                        double or float or decimal => ("decimal?", "null"),
                        _ => ("string", "string.Empty")
                    };
                    cs.AppendLine($"        public {type} {key} {{ get; set; }} = {deflt};");
                }

                cs.AppendLine("    }");
                cs.AppendLine("}");

                var csFilePath = Path.Combine(csDir, $"{className}.cs");
                Console.WriteLine($"Writing {csFilePath} ...");
                File.WriteAllText(csFilePath, cs.ToString(), new UTF8Encoding(false));
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }
        }
    }

    private static string FindProjectDirectoryDownwards(string projectName)
    {
        var projectFileName = $"{projectName}.csproj";
        var startDir = Directory.GetCurrentDirectory();

        // Fast path: if we're already in the project directory.
        var direct = Path.Combine(startDir, projectFileName);
        if (File.Exists(direct))
            return startDir;

        // Primary search (works in GitHub Actions)
        var matches = Directory.GetFiles(startDir, projectFileName, SearchOption.AllDirectories);

        if (matches.Length == 0)
        {
            // ---------- LOCAL FALLBACK ----------
            // If running from bin/Debug/... or bin/Release/..., walk up until we exit /bin
            var dir = new DirectoryInfo(startDir);
            while (dir != null && dir.Name.Equals("bin", StringComparison.OrdinalIgnoreCase) == false)
            {
                dir = dir.Parent;
            }

            // If we found /bin, move one level up (project root candidate)
            if (dir?.Parent != null)
            {
                var projectRootCandidate = dir.Parent.FullName;

                var fallbackMatches = Directory.GetFiles(
                    projectRootCandidate,
                    projectFileName,
                    SearchOption.AllDirectories);

                if (fallbackMatches.Length > 0)
                {
                    var preferredFallback = fallbackMatches
                        .FirstOrDefault(p =>
                            string.Equals(
                                new DirectoryInfo(Path.GetDirectoryName(p)!).Name,
                                projectName,
                                StringComparison.OrdinalIgnoreCase))
                        ?? fallbackMatches[0];

                    return Path.GetDirectoryName(preferredFallback)!;
                }
            }

            throw new DirectoryNotFoundException(
                $"Could not find {projectFileName} under {startDir} (including bin fallback)"
            );
        }

        // Prefer SAPData project if multiple found
        var preferred = matches
            .FirstOrDefault(p =>
                string.Equals(
                    new DirectoryInfo(Path.GetDirectoryName(p)!).Name,
                    projectName,
                    StringComparison.OrdinalIgnoreCase))
            ?? matches[0];

        return Path.GetDirectoryName(preferred)!;
    }
}
