---
ASPNETCORE_ENVIRONMENT: "Development"
FeatureManagement__EnablePrimarySchools: "true"
FeatureManagement__EnableAllThroughSchools: "false"
FeatureManagement__EnableRiseResources: "true"
reset_review_db: "true"
