apiVersion: v1
kind: Service
metadata:
  name: compare-connect-similar-schools-maintenance
  labels:
    app: compare-connect-similar-schools-maintenance
spec:
  selector:
    app: compare-connect-similar-schools-maintenance
  ports:
  - name: http
    port: 80
    targetPort: http
