name: CI - Lint

on:
  pull_request:
    branches:
      - "feature/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - name: Run dotnet format
        run: dotnet format SAPSec.sln --verify-no-changes
