name: CI - Terraform

on:
  pull_request:
    branches:
      - "feature/**"

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate
