name: Docker Test

on:
  workflow_run:
    workflows: ["Docker Build"]
    types:
      - completed

jobs:
  test-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Pull built image
        run: docker pull ${{ secrets.DOCKER_REGISTRY }}/sap-sector:${{ github.sha }}

      - name: Run container smoke tests
        run: |
          docker run --rm ${{ secrets.DOCKER_REGISTRY }}/sap-sector:${{ github.sha }} \
            dotnet --info
